// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AgentConversation struct {
	ID             string         `json:"id"`
	WorkspaceID    string         `json:"workspace_id"`
	PrincipalID    string         `json:"principal_id"`
	Title          string         `json:"title"`
	Status         string         `json:"status"`
	MetadataJson   string         `json:"metadata_json"`
	TranscriptJson string         `json:"transcript_json"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	ArchivedAt     sql.NullString `json:"archived_at"`
}

type AgentEvent struct {
	ID          string `json:"id"`
	RunID       string `json:"run_id"`
	Seq         int64  `json:"seq"`
	EventType   string `json:"event_type"`
	Severity    string `json:"severity"`
	PayloadJson string `json:"payload_json"`
	CreatedAt   string `json:"created_at"`
}

type AgentMessage struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	RunID          sql.NullString `json:"run_id"`
	Seq            int64          `json:"seq"`
	Role           string         `json:"role"`
	ContentText    string         `json:"content_text"`
	ContentJson    string         `json:"content_json"`
	ToolCallID     string         `json:"tool_call_id"`
	ToolName       string         `json:"tool_name"`
	IsError        bool           `json:"is_error"`
	CreatedAt      string         `json:"created_at"`
}

type AgentRun struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	Status         string         `json:"status"`
	Model          string         `json:"model"`
	StopReason     string         `json:"stop_reason"`
	InputTokens    int64          `json:"input_tokens"`
	OutputTokens   int64          `json:"output_tokens"`
	TotalTokens    int64          `json:"total_tokens"`
	Error          string         `json:"error"`
	StartedAt      string         `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	MetadataJson   string         `json:"metadata_json"`
}

type ApiToken struct {
	ID               string         `json:"id"`
	PrincipalID      string         `json:"principal_id"`
	WorkspaceID      sql.NullString `json:"workspace_id"`
	Name             string         `json:"name"`
	TokenFingerprint string         `json:"token_fingerprint"`
	TokenVerifier    string         `json:"token_verifier"`
	PrivilegesJson   string         `json:"privileges_json"`
	ExpiresAt        sql.NullString `json:"expires_at"`
	CreatedAt        string         `json:"created_at"`
	LastUsedAt       sql.NullString `json:"last_used_at"`
	RevokedAt        sql.NullString `json:"revoked_at"`
}

type Asset struct {
	SnapshotID           string `json:"snapshot_id"`
	LogicalAssetID       string `json:"logical_asset_id"`
	WorkspaceID          string `json:"workspace_id"`
	ServingStateID       string `json:"serving_state_id"`
	AssetType            string `json:"asset_type"`
	AssetKey             string `json:"asset_key"`
	ParentLogicalAssetID string `json:"parent_logical_asset_id"`
	Title                string `json:"title"`
	Description          string `json:"description"`
	SourceFile           string `json:"source_file"`
	PayloadSchema        string `json:"payload_schema"`
	PayloadJson          string `json:"payload_json"`
	ContentHash          string `json:"content_hash"`
	CreatedAt            string `json:"created_at"`
}

type AssetEdge struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	ServingStateID     string `json:"serving_state_id"`
	FromLogicalAssetID string `json:"from_logical_asset_id"`
	ToLogicalAssetID   string `json:"to_logical_asset_id"`
	EdgeType           string `json:"edge_type"`
	CreatedAt          string `json:"created_at"`
}

type AuditEvent struct {
	ID            string         `json:"id"`
	WorkspaceID   sql.NullString `json:"workspace_id"`
	PrincipalID   sql.NullString `json:"principal_id"`
	Action        string         `json:"action"`
	TargetType    string         `json:"target_type"`
	TargetID      string         `json:"target_id"`
	Privilege     string         `json:"privilege"`
	Status        string         `json:"status"`
	RequestID     string         `json:"request_id"`
	CorrelationID string         `json:"correlation_id"`
	MetadataJson  string         `json:"metadata_json"`
	CreatedAt     string         `json:"created_at"`
}

type DataPolicy struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	ObjectID       string `json:"object_id"`
	SubjectType    string `json:"subject_type"`
	SubjectID      string `json:"subject_id"`
	PolicyType     string `json:"policy_type"`
	ExpressionJson string `json:"expression_json"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type ExternalIdentity struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
	Provider    string `json:"provider"`
	TenantID    string `json:"tenant_id"`
	Subject     string `json:"subject"`
	Email       string `json:"email"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Grant struct {
	ID          string `json:"id"`
	ObjectID    string `json:"object_id"`
	SubjectType string `json:"subject_type"`
	SubjectID   string `json:"subject_id"`
	Privilege   string `json:"privilege"`
	CreatedAt   string `json:"created_at"`
}

type Group struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Provider    string `json:"provider"`
	ExternalID  string `json:"external_id"`
	Name        string `json:"name"`
	CreatedAt   string `json:"created_at"`
}

type GroupMember struct {
	GroupID     string `json:"group_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
	CreatedAt   string `json:"created_at"`
}

type OauthState struct {
	ID          string `json:"id"`
	StateHash   string `json:"state_hash"`
	RedirectUrl string `json:"redirect_url"`
	ExpiresAt   string `json:"expires_at"`
	CreatedAt   string `json:"created_at"`
}

type PlatformRoleBinding struct {
	ID          string `json:"id"`
	RoleID      string `json:"role_id"`
	PrincipalID string `json:"principal_id"`
	CreatedAt   string `json:"created_at"`
}

type PlatformSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Principal struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	Email       string         `json:"email"`
	DisplayName string         `json:"display_name"`
	DisabledAt  sql.NullString `json:"disabled_at"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type QueryEvent struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
	Surface        string `json:"surface"`
	Operation      string `json:"operation"`
	QueryKind      string `json:"query_kind"`
	ModelID        string `json:"model_id"`
	Target         string `json:"target"`
	ObjectType     string `json:"object_type"`
	ObjectID       string `json:"object_id"`
	RequestID      string `json:"request_id"`
	CorrelationID  string `json:"correlation_id"`
	Status         string `json:"status"`
	DurationMs     int64  `json:"duration_ms"`
	QueueWaitMs    int64  `json:"queue_wait_ms"`
	ExecutionMs    int64  `json:"execution_ms"`
	ExecutionState string `json:"execution_state"`
	RowsReturned   int64  `json:"rows_returned"`
	BytesEstimate  int64  `json:"bytes_estimate"`
	Error          string `json:"error"`
	SqlText        string `json:"sql_text"`
	PlanText       string `json:"plan_text"`
	QueryJson      string `json:"query_json"`
	CreatedAt      string `json:"created_at"`
}

type QuerySnapshotLease struct {
	ID                 string         `json:"id"`
	WorkspaceID        string         `json:"workspace_id"`
	Environment        string         `json:"environment"`
	ServingStateID     string         `json:"serving_state_id"`
	DucklakeSnapshotID int64          `json:"ducklake_snapshot_id"`
	OwnerID            string         `json:"owner_id"`
	AcquiredAt         string         `json:"acquired_at"`
	ExpiresAt          string         `json:"expires_at"`
	ReleasedAt         sql.NullString `json:"released_at"`
}

type RefreshJob struct {
	ID             string         `json:"id"`
	WorkspaceID    string         `json:"workspace_id"`
	ServingStateID sql.NullString `json:"serving_state_id"`
	ModelID        string         `json:"model_id"`
	Kind           string         `json:"kind"`
	PayloadJson    string         `json:"payload_json"`
	Status         string         `json:"status"`
	QueuedAt       string         `json:"queued_at"`
	StartedAt      sql.NullString `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	LeaseOwner     string         `json:"lease_owner"`
	LeaseExpiresAt sql.NullString `json:"lease_expires_at"`
	AttemptCount   int64          `json:"attempt_count"`
	LastError      string         `json:"last_error"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type RefreshJobRun struct {
	ID          string         `json:"id"`
	JobID       string         `json:"job_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	TargetType  string         `json:"target_type"`
	TargetID    string         `json:"target_id"`
	TriggerType string         `json:"trigger_type"`
	ParentRunID sql.NullString `json:"parent_run_id"`
	Status      string         `json:"status"`
	StartedAt   string         `json:"started_at"`
	FinishedAt  sql.NullString `json:"finished_at"`
	Error       string         `json:"error"`
}

type Role struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	PrivilegesJson string `json:"privileges_json"`
}

type RoleBinding struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	RoleID      string         `json:"role_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
	CreatedAt   string         `json:"created_at"`
}

type RoleGrantTemplate struct {
	RoleName  string `json:"role_name"`
	Privilege string `json:"privilege"`
	CreatedAt string `json:"created_at"`
}

type SecurableObject struct {
	ID               string `json:"id"`
	ObjectType       string `json:"object_type"`
	WorkspaceID      string `json:"workspace_id"`
	ParentID         string `json:"parent_id"`
	OwnerPrincipalID string `json:"owner_principal_id"`
	DisplayName      string `json:"display_name"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

type ServicePrincipalSecret struct {
	ID                 string         `json:"id"`
	ServicePrincipalID string         `json:"service_principal_id"`
	Name               string         `json:"name"`
	SecretFingerprint  string         `json:"secret_fingerprint"`
	SecretVerifier     string         `json:"secret_verifier"`
	ExpiresAt          sql.NullString `json:"expires_at"`
	CreatedAt          string         `json:"created_at"`
	RevokedAt          sql.NullString `json:"revoked_at"`
}

type ServingState struct {
	ID                 string         `json:"id"`
	WorkspaceID        string         `json:"workspace_id"`
	Environment        string         `json:"environment"`
	Status             string         `json:"status"`
	Source             string         `json:"source"`
	Digest             string         `json:"digest"`
	ManifestJson       string         `json:"manifest_json"`
	DucklakeSnapshotID int64          `json:"ducklake_snapshot_id"`
	CreatedBy          string         `json:"created_by"`
	CreatedAt          string         `json:"created_at"`
	ActivatedAt        sql.NullString `json:"activated_at"`
	SupersededAt       sql.NullString `json:"superseded_at"`
	Error              string         `json:"error"`
}

type ServingStateArtifact struct {
	ID             string `json:"id"`
	ServingStateID string `json:"serving_state_id"`
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	Digest         string `json:"digest"`
	Format         string `json:"format"`
	Path           string `json:"path"`
	DataRoot       string `json:"data_root"`
	ManifestJson   string `json:"manifest_json"`
	SizeBytes      int64  `json:"size_bytes"`
	CreatedAt      string `json:"created_at"`
}

type Session struct {
	ID               string         `json:"id"`
	PrincipalID      string         `json:"principal_id"`
	TokenFingerprint string         `json:"token_fingerprint"`
	TokenVerifier    string         `json:"token_verifier"`
	ExpiresAt        string         `json:"expires_at"`
	CreatedAt        string         `json:"created_at"`
	LastSeenAt       string         `json:"last_seen_at"`
	RevokedAt        sql.NullString `json:"revoked_at"`
}

type Workspace struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type WorkspaceActiveServingState struct {
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	ServingStateID string `json:"serving_state_id"`
	UpdatedAt      string `json:"updated_at"`
}
