// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AgentConversation struct {
	ID             string         `json:"id"`
	WorkspaceID    string         `json:"workspace_id"`
	PrincipalID    string         `json:"principal_id"`
	Title          string         `json:"title"`
	Status         string         `json:"status"`
	MetadataJson   string         `json:"metadata_json"`
	TranscriptJson string         `json:"transcript_json"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	ArchivedAt     sql.NullString `json:"archived_at"`
}

type AgentEvent struct {
	ID          string `json:"id"`
	RunID       string `json:"run_id"`
	Seq         int64  `json:"seq"`
	EventType   string `json:"event_type"`
	Severity    string `json:"severity"`
	PayloadJson string `json:"payload_json"`
	CreatedAt   string `json:"created_at"`
}

type AgentMessage struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	RunID          sql.NullString `json:"run_id"`
	Seq            int64          `json:"seq"`
	Role           string         `json:"role"`
	ContentText    string         `json:"content_text"`
	ContentJson    string         `json:"content_json"`
	ToolCallID     string         `json:"tool_call_id"`
	ToolName       string         `json:"tool_name"`
	IsError        bool           `json:"is_error"`
	CreatedAt      string         `json:"created_at"`
}

type AgentRun struct {
	ID             string         `json:"id"`
	ConversationID string         `json:"conversation_id"`
	Status         string         `json:"status"`
	Model          string         `json:"model"`
	StopReason     string         `json:"stop_reason"`
	InputTokens    int64          `json:"input_tokens"`
	OutputTokens   int64          `json:"output_tokens"`
	TotalTokens    int64          `json:"total_tokens"`
	Error          string         `json:"error"`
	StartedAt      string         `json:"started_at"`
	FinishedAt     sql.NullString `json:"finished_at"`
	MetadataJson   string         `json:"metadata_json"`
}

type ApiToken struct {
	ID              string         `json:"id"`
	PrincipalID     string         `json:"principal_id"`
	WorkspaceID     sql.NullString `json:"workspace_id"`
	Name            string         `json:"name"`
	TokenHash       string         `json:"token_hash"`
	PermissionsJson string         `json:"permissions_json"`
	ExpiresAt       sql.NullString `json:"expires_at"`
	CreatedAt       string         `json:"created_at"`
	LastUsedAt      sql.NullString `json:"last_used_at"`
	RevokedAt       sql.NullString `json:"revoked_at"`
}

type Asset struct {
	SnapshotID           string `json:"snapshot_id"`
	LogicalAssetID       string `json:"logical_asset_id"`
	WorkspaceID          string `json:"workspace_id"`
	DeploymentID         string `json:"deployment_id"`
	AssetType            string `json:"asset_type"`
	AssetKey             string `json:"asset_key"`
	ParentLogicalAssetID string `json:"parent_logical_asset_id"`
	Title                string `json:"title"`
	Description          string `json:"description"`
	SourceFile           string `json:"source_file"`
	PayloadSchema        string `json:"payload_schema"`
	PayloadJson          string `json:"payload_json"`
	ContentHash          string `json:"content_hash"`
	CreatedAt            string `json:"created_at"`
}

type AssetEdge struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	DeploymentID       string `json:"deployment_id"`
	FromLogicalAssetID string `json:"from_logical_asset_id"`
	ToLogicalAssetID   string `json:"to_logical_asset_id"`
	EdgeType           string `json:"edge_type"`
	CreatedAt          string `json:"created_at"`
}

type AuditEvent struct {
	ID           string         `json:"id"`
	WorkspaceID  sql.NullString `json:"workspace_id"`
	PrincipalID  sql.NullString `json:"principal_id"`
	Action       string         `json:"action"`
	TargetType   string         `json:"target_type"`
	TargetID     string         `json:"target_id"`
	MetadataJson string         `json:"metadata_json"`
	CreatedAt    string         `json:"created_at"`
}

type Deployment struct {
	ID           string         `json:"id"`
	WorkspaceID  string         `json:"workspace_id"`
	Environment  string         `json:"environment"`
	Status       string         `json:"status"`
	Digest       string         `json:"digest"`
	ManifestJson string         `json:"manifest_json"`
	CreatedBy    string         `json:"created_by"`
	CreatedAt    string         `json:"created_at"`
	ActivatedAt  sql.NullString `json:"activated_at"`
	Error        string         `json:"error"`
}

type DeploymentArtifact struct {
	ID           string `json:"id"`
	DeploymentID string `json:"deployment_id"`
	WorkspaceID  string `json:"workspace_id"`
	Environment  string `json:"environment"`
	Digest       string `json:"digest"`
	Format       string `json:"format"`
	Path         string `json:"path"`
	ManifestJson string `json:"manifest_json"`
	SizeBytes    int64  `json:"size_bytes"`
	CreatedAt    string `json:"created_at"`
}

type ExternalIdentity struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
	Provider    string `json:"provider"`
	TenantID    string `json:"tenant_id"`
	Subject     string `json:"subject"`
	Email       string `json:"email"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Group struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Provider    string `json:"provider"`
	ExternalID  string `json:"external_id"`
	Name        string `json:"name"`
	CreatedAt   string `json:"created_at"`
}

type GroupMember struct {
	GroupID     string `json:"group_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
	CreatedAt   string `json:"created_at"`
}

type MaterializationJob struct {
	ID           string         `json:"id"`
	WorkspaceID  string         `json:"workspace_id"`
	DeploymentID sql.NullString `json:"deployment_id"`
	ModelID      string         `json:"model_id"`
	Status       string         `json:"status"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type MaterializationJobRun struct {
	ID          string         `json:"id"`
	JobID       string         `json:"job_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	TargetType  string         `json:"target_type"`
	TargetID    string         `json:"target_id"`
	TriggerType string         `json:"trigger_type"`
	ParentRunID sql.NullString `json:"parent_run_id"`
	Status      string         `json:"status"`
	StartedAt   string         `json:"started_at"`
	FinishedAt  sql.NullString `json:"finished_at"`
	Error       string         `json:"error"`
}

type OauthState struct {
	ID          string `json:"id"`
	StateHash   string `json:"state_hash"`
	RedirectUrl string `json:"redirect_url"`
	ExpiresAt   string `json:"expires_at"`
	CreatedAt   string `json:"created_at"`
}

type Permission struct {
	Name      string `json:"name"`
	CreatedAt string `json:"created_at"`
}

type PlatformRoleBinding struct {
	ID          string `json:"id"`
	RoleID      string `json:"role_id"`
	PrincipalID string `json:"principal_id"`
	CreatedAt   string `json:"created_at"`
}

type Principal struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Role struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	PermissionsJson string `json:"permissions_json"`
}

type RoleBinding struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	RoleID      string         `json:"role_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
	CreatedAt   string         `json:"created_at"`
}

type RolePermission struct {
	RoleID         string `json:"role_id"`
	PermissionName string `json:"permission_name"`
	CreatedAt      string `json:"created_at"`
}

type Session struct {
	ID          string         `json:"id"`
	PrincipalID string         `json:"principal_id"`
	TokenHash   string         `json:"token_hash"`
	ExpiresAt   string         `json:"expires_at"`
	CreatedAt   string         `json:"created_at"`
	LastSeenAt  string         `json:"last_seen_at"`
	RevokedAt   sql.NullString `json:"revoked_at"`
}

type Workspace struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type WorkspaceActiveDeployment struct {
	WorkspaceID  string `json:"workspace_id"`
	Environment  string `json:"environment"`
	DeploymentID string `json:"deployment_id"`
	UpdatedAt    string `json:"updated_at"`
}
