// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const appendAgentEvent = `-- name: AppendAgentEvent :one
INSERT INTO agent_events (id, run_id, seq, event_type, severity, payload_json)
SELECT
  ?1,
  r.id,
  ?2,
  ?3,
  ?4,
  ?5
FROM agent_runs r
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE r.id = ?6
  AND c.workspace_id = ?7
  AND c.principal_id = ?8
RETURNING id, run_id, seq, event_type, severity, payload_json, created_at
`

type AppendAgentEventParams struct {
	ID          string `json:"id"`
	Seq         int64  `json:"seq"`
	EventType   string `json:"event_type"`
	Severity    string `json:"severity"`
	PayloadJson string `json:"payload_json"`
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) AppendAgentEvent(ctx context.Context, arg AppendAgentEventParams) (AgentEvent, error) {
	row := q.db.QueryRowContext(ctx, appendAgentEvent,
		arg.ID,
		arg.Seq,
		arg.EventType,
		arg.Severity,
		arg.PayloadJson,
		arg.RunID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.EventType,
		&i.Severity,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const appendAgentMessage = `-- name: AppendAgentMessage :one
INSERT INTO agent_messages (id, conversation_id, run_id, seq, role, content_text, content_json, tool_call_id, tool_name, is_error)
SELECT
  ?1,
  c.id,
  NULLIF(?2, ''),
  COALESCE((SELECT MAX(seq) + 1 FROM agent_messages WHERE conversation_id = c.id), 1),
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
FROM agent_conversations c
WHERE c.id = ?9
  AND c.workspace_id = ?10
  AND c.principal_id = ?11
RETURNING id, conversation_id, run_id, seq, role, content_text, content_json, tool_call_id, tool_name, is_error, created_at
`

type AppendAgentMessageParams struct {
	ID             string      `json:"id"`
	RunID          interface{} `json:"run_id"`
	Role           string      `json:"role"`
	ContentText    string      `json:"content_text"`
	ContentJson    string      `json:"content_json"`
	ToolCallID     string      `json:"tool_call_id"`
	ToolName       string      `json:"tool_name"`
	IsError        bool        `json:"is_error"`
	ConversationID string      `json:"conversation_id"`
	WorkspaceID    string      `json:"workspace_id"`
	PrincipalID    string      `json:"principal_id"`
}

func (q *Queries) AppendAgentMessage(ctx context.Context, arg AppendAgentMessageParams) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, appendAgentMessage,
		arg.ID,
		arg.RunID,
		arg.Role,
		arg.ContentText,
		arg.ContentJson,
		arg.ToolCallID,
		arg.ToolName,
		arg.IsError,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RunID,
		&i.Seq,
		&i.Role,
		&i.ContentText,
		&i.ContentJson,
		&i.ToolCallID,
		&i.ToolName,
		&i.IsError,
		&i.CreatedAt,
	)
	return i, err
}

const archiveAgentConversation = `-- name: ArchiveAgentConversation :one
UPDATE agent_conversations
SET status = 'archived',
    archived_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
  AND workspace_id = ?2
  AND principal_id = ?3
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type ArchiveAgentConversationParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) ArchiveAgentConversation(ctx context.Context, arg ArchiveAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, archiveAgentConversation, arg.ID, arg.WorkspaceID, arg.PrincipalID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const clearAssetEdgesForServingState = `-- name: ClearAssetEdgesForServingState :exec
DELETE FROM asset_edges WHERE serving_state_id = ?
`

func (q *Queries) ClearAssetEdgesForServingState(ctx context.Context, servingStateID string) error {
	_, err := q.db.ExecContext(ctx, clearAssetEdgesForServingState, servingStateID)
	return err
}

const clearAssetsForServingState = `-- name: ClearAssetsForServingState :exec
DELETE FROM assets WHERE serving_state_id = ?
`

func (q *Queries) ClearAssetsForServingState(ctx context.Context, servingStateID string) error {
	_, err := q.db.ExecContext(ctx, clearAssetsForServingState, servingStateID)
	return err
}

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (id, principal_id, workspace_id, name, token_fingerprint, token_verifier, privileges_json, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAPITokenParams struct {
	ID               string         `json:"id"`
	PrincipalID      string         `json:"principal_id"`
	WorkspaceID      sql.NullString `json:"workspace_id"`
	Name             string         `json:"name"`
	TokenFingerprint string         `json:"token_fingerprint"`
	TokenVerifier    string         `json:"token_verifier"`
	PrivilegesJson   string         `json:"privileges_json"`
	ExpiresAt        sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, createAPIToken,
		arg.ID,
		arg.PrincipalID,
		arg.WorkspaceID,
		arg.Name,
		arg.TokenFingerprint,
		arg.TokenVerifier,
		arg.PrivilegesJson,
		arg.ExpiresAt,
	)
	return err
}

const createAgentConversation = `-- name: CreateAgentConversation :one
INSERT INTO agent_conversations (id, workspace_id, principal_id, title, status, metadata_json, transcript_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type CreateAgentConversationParams struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
	Title          string `json:"title"`
	Status         string `json:"status"`
	MetadataJson   string `json:"metadata_json"`
	TranscriptJson string `json:"transcript_json"`
}

func (q *Queries) CreateAgentConversation(ctx context.Context, arg CreateAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, createAgentConversation,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Title,
		arg.Status,
		arg.MetadataJson,
		arg.TranscriptJson,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (id, conversation_id, status, model, metadata_json)
SELECT
  ?1,
  c.id,
  ?2,
  ?3,
  ?4
FROM agent_conversations c
WHERE c.id = ?5
  AND c.workspace_id = ?6
  AND c.principal_id = ?7
RETURNING id, conversation_id, status, model, stop_reason, input_tokens, output_tokens, total_tokens, error, started_at, finished_at, metadata_json
`

type CreateAgentRunParams struct {
	ID             string `json:"id"`
	Status         string `json:"status"`
	Model          string `json:"model"`
	MetadataJson   string `json:"metadata_json"`
	ConversationID string `json:"conversation_id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, createAgentRun,
		arg.ID,
		arg.Status,
		arg.Model,
		arg.MetadataJson,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.Model,
		&i.StopReason,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MetadataJson,
	)
	return i, err
}

const createQuerySnapshotLease = `-- name: CreateQuerySnapshotLease :exec
INSERT INTO query_snapshot_leases (id, workspace_id, environment, serving_state_id, ducklake_snapshot_id, owner_id, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateQuerySnapshotLeaseParams struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	Environment        string `json:"environment"`
	ServingStateID     string `json:"serving_state_id"`
	DucklakeSnapshotID int64  `json:"ducklake_snapshot_id"`
	OwnerID            string `json:"owner_id"`
	ExpiresAt          string `json:"expires_at"`
}

func (q *Queries) CreateQuerySnapshotLease(ctx context.Context, arg CreateQuerySnapshotLeaseParams) error {
	_, err := q.db.ExecContext(ctx, createQuerySnapshotLease,
		arg.ID,
		arg.WorkspaceID,
		arg.Environment,
		arg.ServingStateID,
		arg.DucklakeSnapshotID,
		arg.OwnerID,
		arg.ExpiresAt,
	)
	return err
}

const createServicePrincipalSecret = `-- name: CreateServicePrincipalSecret :exec
INSERT INTO service_principal_secrets (id, service_principal_id, name, secret_fingerprint, secret_verifier, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateServicePrincipalSecretParams struct {
	ID                 string         `json:"id"`
	ServicePrincipalID string         `json:"service_principal_id"`
	Name               string         `json:"name"`
	SecretFingerprint  string         `json:"secret_fingerprint"`
	SecretVerifier     string         `json:"secret_verifier"`
	ExpiresAt          sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateServicePrincipalSecret(ctx context.Context, arg CreateServicePrincipalSecretParams) error {
	_, err := q.db.ExecContext(ctx, createServicePrincipalSecret,
		arg.ID,
		arg.ServicePrincipalID,
		arg.Name,
		arg.SecretFingerprint,
		arg.SecretVerifier,
		arg.ExpiresAt,
	)
	return err
}

const createServingState = `-- name: CreateServingState :exec
INSERT INTO serving_states (id, workspace_id, environment, status, source, created_by)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateServingStateParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	Status      string `json:"status"`
	Source      string `json:"source"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateServingState(ctx context.Context, arg CreateServingStateParams) error {
	_, err := q.db.ExecContext(ctx, createServingState,
		arg.ID,
		arg.WorkspaceID,
		arg.Environment,
		arg.Status,
		arg.Source,
		arg.CreatedBy,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, principal_id, token_fingerprint, token_verifier, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID               string `json:"id"`
	PrincipalID      string `json:"principal_id"`
	TokenFingerprint string `json:"token_fingerprint"`
	TokenVerifier    string `json:"token_verifier"`
	ExpiresAt        string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.PrincipalID,
		arg.TokenFingerprint,
		arg.TokenVerifier,
		arg.ExpiresAt,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE workspace_id = ? AND id = ?
`

type DeleteGroupParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, arg.WorkspaceID, arg.ID)
	return err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM group_members
WHERE workspace_id = ? AND group_id = ? AND principal_id = ?
`

type DeleteGroupMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	GroupID     string `json:"group_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMember, arg.WorkspaceID, arg.GroupID, arg.PrincipalID)
	return err
}

const deletePrincipalRoleBindings = `-- name: DeletePrincipalRoleBindings :exec
DELETE FROM role_bindings
WHERE workspace_id = ? AND principal_id = ?
`

type DeletePrincipalRoleBindingsParams struct {
	WorkspaceID string         `json:"workspace_id"`
	PrincipalID sql.NullString `json:"principal_id"`
}

func (q *Queries) DeletePrincipalRoleBindings(ctx context.Context, arg DeletePrincipalRoleBindingsParams) error {
	_, err := q.db.ExecContext(ctx, deletePrincipalRoleBindings, arg.WorkspaceID, arg.PrincipalID)
	return err
}

const deleteRoleBindingByID = `-- name: DeleteRoleBindingByID :exec
DELETE FROM role_bindings
WHERE workspace_id = ? AND id = ?
`

type DeleteRoleBindingByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) DeleteRoleBindingByID(ctx context.Context, arg DeleteRoleBindingByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteRoleBindingByID, arg.WorkspaceID, arg.ID)
	return err
}

const deleteSCIMGroup = `-- name: DeleteSCIMGroup :exec
DELETE FROM groups
WHERE workspace_id = '' AND provider = 'scim' AND id = ?
`

func (q *Queries) DeleteSCIMGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSCIMGroup, id)
	return err
}

const deleteSCIMGroupMembers = `-- name: DeleteSCIMGroupMembers :exec
DELETE FROM group_members
WHERE workspace_id = '' AND group_id = ?
`

func (q *Queries) DeleteSCIMGroupMembers(ctx context.Context, groupID string) error {
	_, err := q.db.ExecContext(ctx, deleteSCIMGroupMembers, groupID)
	return err
}

const deleteSCIMGroupMembersByPrincipal = `-- name: DeleteSCIMGroupMembersByPrincipal :exec
DELETE FROM group_members
WHERE workspace_id = '' AND principal_id = ?
`

func (q *Queries) DeleteSCIMGroupMembersByPrincipal(ctx context.Context, principalID string) error {
	_, err := q.db.ExecContext(ctx, deleteSCIMGroupMembersByPrincipal, principalID)
	return err
}

const deleteServicePrincipal = `-- name: DeleteServicePrincipal :exec
DELETE FROM principals
WHERE id = ? AND kind = 'service_principal'
`

func (q *Queries) DeleteServicePrincipal(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteServicePrincipal, id)
	return err
}

const deleteSessionByTokenFingerprint = `-- name: DeleteSessionByTokenFingerprint :exec
DELETE FROM sessions WHERE token_fingerprint = ?
`

func (q *Queries) DeleteSessionByTokenFingerprint(ctx context.Context, tokenFingerprint string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenFingerprint, tokenFingerprint)
	return err
}

const disablePrincipal = `-- name: DisablePrincipal :exec
UPDATE principals
SET disabled_at = COALESCE(disabled_at, CURRENT_TIMESTAMP),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) DisablePrincipal(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, disablePrincipal, id)
	return err
}

const expireInactiveServingStates = `-- name: ExpireInactiveServingStates :exec
UPDATE serving_states
SET status = 'expired', error = ''
WHERE status = 'inactive'
`

func (q *Queries) ExpireInactiveServingStates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, expireInactiveServingStates)
	return err
}

const extendQuerySnapshotLease = `-- name: ExtendQuerySnapshotLease :exec
UPDATE query_snapshot_leases
SET expires_at = ?
WHERE id = ?
  AND released_at IS NULL
`

type ExtendQuerySnapshotLeaseParams struct {
	ExpiresAt string `json:"expires_at"`
	ID        string `json:"id"`
}

func (q *Queries) ExtendQuerySnapshotLease(ctx context.Context, arg ExtendQuerySnapshotLeaseParams) error {
	_, err := q.db.ExecContext(ctx, extendQuerySnapshotLease, arg.ExpiresAt, arg.ID)
	return err
}

const finishAgentRun = `-- name: FinishAgentRun :one
UPDATE agent_runs
SET status = ?1,
    stop_reason = ?2,
    input_tokens = ?3,
    output_tokens = ?4,
    total_tokens = ?5,
    error = ?6,
    finished_at = CURRENT_TIMESTAMP,
    metadata_json = ?7
WHERE agent_runs.id = ?8
  AND conversation_id IN (
    SELECT agent_conversations.id
    FROM agent_conversations
    WHERE agent_conversations.id = ?9
      AND workspace_id = ?10
      AND principal_id = ?11
  )
RETURNING id, conversation_id, status, model, stop_reason, input_tokens, output_tokens, total_tokens, error, started_at, finished_at, metadata_json
`

type FinishAgentRunParams struct {
	Status         string `json:"status"`
	StopReason     string `json:"stop_reason"`
	InputTokens    int64  `json:"input_tokens"`
	OutputTokens   int64  `json:"output_tokens"`
	TotalTokens    int64  `json:"total_tokens"`
	Error          string `json:"error"`
	MetadataJson   string `json:"metadata_json"`
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) FinishAgentRun(ctx context.Context, arg FinishAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, finishAgentRun,
		arg.Status,
		arg.StopReason,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.Error,
		arg.MetadataJson,
		arg.ID,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.Model,
		&i.StopReason,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MetadataJson,
	)
	return i, err
}

const getAPITokenByFingerprint = `-- name: GetAPITokenByFingerprint :one
SELECT id, principal_id, workspace_id, name, token_fingerprint, token_verifier, privileges_json, expires_at, created_at, last_used_at, revoked_at FROM api_tokens
WHERE token_fingerprint = ?
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR datetime(expires_at) > CURRENT_TIMESTAMP)
`

func (q *Queries) GetAPITokenByFingerprint(ctx context.Context, tokenFingerprint string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByFingerprint, tokenFingerprint)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.WorkspaceID,
		&i.Name,
		&i.TokenFingerprint,
		&i.TokenVerifier,
		&i.PrivilegesJson,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByFingerprintForAudit = `-- name: GetAPITokenByFingerprintForAudit :one
SELECT id, principal_id, workspace_id, name, token_fingerprint, token_verifier, privileges_json, expires_at, created_at, last_used_at, revoked_at FROM api_tokens
WHERE token_fingerprint = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetAPITokenByFingerprintForAudit(ctx context.Context, tokenFingerprint string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByFingerprintForAudit, tokenFingerprint)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.WorkspaceID,
		&i.Name,
		&i.TokenFingerprint,
		&i.TokenVerifier,
		&i.PrivilegesJson,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveServingState = `-- name: GetActiveServingState :one
SELECT d.id, d.workspace_id, d.environment, d.status, d.source, d.digest, d.manifest_json, d.ducklake_snapshot_id, d.created_by, d.created_at, d.activated_at, d.superseded_at, d.error
FROM serving_states d
JOIN workspace_active_serving_states active ON active.serving_state_id = d.id
WHERE active.workspace_id = ? AND active.environment = ?
`

type GetActiveServingStateParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

func (q *Queries) GetActiveServingState(ctx context.Context, arg GetActiveServingStateParams) (ServingState, error) {
	row := q.db.QueryRowContext(ctx, getActiveServingState, arg.WorkspaceID, arg.Environment)
	var i ServingState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Environment,
		&i.Status,
		&i.Source,
		&i.Digest,
		&i.ManifestJson,
		&i.DucklakeSnapshotID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.SupersededAt,
		&i.Error,
	)
	return i, err
}

const getAgentConversation = `-- name: GetAgentConversation :one
SELECT id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at FROM agent_conversations
WHERE id = ?1
  AND workspace_id = ?2
  AND principal_id = ?3
`

type GetAgentConversationParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) GetAgentConversation(ctx context.Context, arg GetAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, getAgentConversation, arg.ID, arg.WorkspaceID, arg.PrincipalID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getArtifactByServingState = `-- name: GetArtifactByServingState :one
SELECT id, serving_state_id, workspace_id, environment, digest, format, path, data_root, manifest_json, size_bytes, created_at FROM serving_state_artifacts WHERE serving_state_id = ?
`

func (q *Queries) GetArtifactByServingState(ctx context.Context, servingStateID string) (ServingStateArtifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByServingState, servingStateID)
	var i ServingStateArtifact
	err := row.Scan(
		&i.ID,
		&i.ServingStateID,
		&i.WorkspaceID,
		&i.Environment,
		&i.Digest,
		&i.Format,
		&i.Path,
		&i.DataRoot,
		&i.ManifestJson,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getExternalIdentity = `-- name: GetExternalIdentity :one
SELECT id, principal_id, provider, tenant_id, subject, email, created_at, updated_at FROM external_identities
WHERE provider = ? AND tenant_id = ? AND subject = ?
`

type GetExternalIdentityParams struct {
	Provider string `json:"provider"`
	TenantID string `json:"tenant_id"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetExternalIdentity(ctx context.Context, arg GetExternalIdentityParams) (ExternalIdentity, error) {
	row := q.db.QueryRowContext(ctx, getExternalIdentity, arg.Provider, arg.TenantID, arg.Subject)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Provider,
		&i.TenantID,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalIdentityByPrincipalProvider = `-- name: GetExternalIdentityByPrincipalProvider :one
SELECT id, principal_id, provider, tenant_id, subject, email, created_at, updated_at FROM external_identities
WHERE principal_id = ? AND provider = ?
LIMIT 1
`

type GetExternalIdentityByPrincipalProviderParams struct {
	PrincipalID string `json:"principal_id"`
	Provider    string `json:"provider"`
}

func (q *Queries) GetExternalIdentityByPrincipalProvider(ctx context.Context, arg GetExternalIdentityByPrincipalProviderParams) (ExternalIdentity, error) {
	row := q.db.QueryRowContext(ctx, getExternalIdentityByPrincipalProvider, arg.PrincipalID, arg.Provider)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Provider,
		&i.TenantID,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, workspace_id, provider, external_id, name, created_at FROM groups
WHERE workspace_id = ? AND id = ?
`

type GetGroupParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, arg.WorkspaceID, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByProviderExternalID = `-- name: GetGroupByProviderExternalID :one
SELECT id, workspace_id, provider, external_id, name, created_at FROM groups
WHERE workspace_id = ? AND provider = ? AND external_id = ?
`

type GetGroupByProviderExternalIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	Provider    string `json:"provider"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) GetGroupByProviderExternalID(ctx context.Context, arg GetGroupByProviderExternalIDParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByProviderExternalID, arg.WorkspaceID, arg.Provider, arg.ExternalID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, kind, email, display_name, disabled_at, created_at, updated_at FROM principals WHERE id = ?
`

func (q *Queries) GetPrincipal(ctx context.Context, id string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipal, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrincipalByEmail = `-- name: GetPrincipalByEmail :one
SELECT id, kind, email, display_name, disabled_at, created_at, updated_at FROM principals WHERE lower(email) = lower(?) AND email <> '' LIMIT 1
`

func (q *Queries) GetPrincipalByEmail(ctx context.Context, lower string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByEmail, lower)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.DisabledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueryEvent = `-- name: GetQueryEvent :one
SELECT id, workspace_id, principal_id, surface, operation, query_kind, model_id, target, object_type, object_id, request_id, correlation_id, status, duration_ms, queue_wait_ms, execution_ms, execution_state, rows_returned, bytes_estimate, error, sql_text, plan_text, query_json, created_at
FROM query_events
WHERE id = ?1
`

func (q *Queries) GetQueryEvent(ctx context.Context, id string) (QueryEvent, error) {
	row := q.db.QueryRowContext(ctx, getQueryEvent, id)
	var i QueryEvent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Surface,
		&i.Operation,
		&i.QueryKind,
		&i.ModelID,
		&i.Target,
		&i.ObjectType,
		&i.ObjectID,
		&i.RequestID,
		&i.CorrelationID,
		&i.Status,
		&i.DurationMs,
		&i.QueueWaitMs,
		&i.ExecutionMs,
		&i.ExecutionState,
		&i.RowsReturned,
		&i.BytesEstimate,
		&i.Error,
		&i.SqlText,
		&i.PlanText,
		&i.QueryJson,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleBindingByID = `-- name: GetRoleBindingByID :one
SELECT
  rb.id,
  rb.workspace_id,
  CASE
    WHEN NULLIF(rb.principal_id, '') IS NOT NULL AND p.kind = 'service_principal' THEN 'service_principal'
    WHEN NULLIF(rb.principal_id, '') IS NOT NULL THEN 'principal'
    ELSE 'group'
  END AS subject_type,
  COALESCE(NULLIF(rb.principal_id, ''), rb.group_id, '') AS subject_id,
  rb.principal_id,
  rb.group_id,
  p.email,
  p.display_name,
  g.name AS group_name,
  r.name AS role_name,
  rb.created_at
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
LEFT JOIN principals p ON p.id = NULLIF(rb.principal_id, '')
LEFT JOIN groups g ON g.id = rb.group_id
WHERE rb.workspace_id = ? AND rb.id = ?
`

type GetRoleBindingByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

type GetRoleBindingByIDRow struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	SubjectType string         `json:"subject_type"`
	SubjectID   string         `json:"subject_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
	Email       sql.NullString `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	GroupName   sql.NullString `json:"group_name"`
	RoleName    string         `json:"role_name"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetRoleBindingByID(ctx context.Context, arg GetRoleBindingByIDParams) (GetRoleBindingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRoleBindingByID, arg.WorkspaceID, arg.ID)
	var i GetRoleBindingByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.PrincipalID,
		&i.GroupID,
		&i.Email,
		&i.DisplayName,
		&i.GroupName,
		&i.RoleName,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, privileges_json FROM roles WHERE name = ?
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.PrivilegesJson)
	return i, err
}

const getSCIMGroup = `-- name: GetSCIMGroup :one
SELECT id, workspace_id, provider, external_id, name, created_at FROM groups
WHERE provider = 'scim' AND id = ?
`

func (q *Queries) GetSCIMGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getSCIMGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getServicePrincipalSecretByFingerprint = `-- name: GetServicePrincipalSecretByFingerprint :one
SELECT s.id, s.service_principal_id, s.name, s.secret_fingerprint, s.secret_verifier, s.expires_at, s.created_at, s.revoked_at
FROM service_principal_secrets s
JOIN principals p ON p.id = s.service_principal_id
WHERE p.kind = 'service_principal'
  AND s.service_principal_id = ?
  AND s.secret_fingerprint = ?
  AND s.revoked_at IS NULL
  AND (s.expires_at IS NULL OR datetime(s.expires_at) > CURRENT_TIMESTAMP)
`

type GetServicePrincipalSecretByFingerprintParams struct {
	ServicePrincipalID string `json:"service_principal_id"`
	SecretFingerprint  string `json:"secret_fingerprint"`
}

func (q *Queries) GetServicePrincipalSecretByFingerprint(ctx context.Context, arg GetServicePrincipalSecretByFingerprintParams) (ServicePrincipalSecret, error) {
	row := q.db.QueryRowContext(ctx, getServicePrincipalSecretByFingerprint, arg.ServicePrincipalID, arg.SecretFingerprint)
	var i ServicePrincipalSecret
	err := row.Scan(
		&i.ID,
		&i.ServicePrincipalID,
		&i.Name,
		&i.SecretFingerprint,
		&i.SecretVerifier,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getServingState = `-- name: GetServingState :one
SELECT id, workspace_id, environment, status, source, digest, manifest_json, ducklake_snapshot_id, created_by, created_at, activated_at, superseded_at, error FROM serving_states WHERE id = ?
`

func (q *Queries) GetServingState(ctx context.Context, id string) (ServingState, error) {
	row := q.db.QueryRowContext(ctx, getServingState, id)
	var i ServingState
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Environment,
		&i.Status,
		&i.Source,
		&i.Digest,
		&i.ManifestJson,
		&i.DucklakeSnapshotID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.SupersededAt,
		&i.Error,
	)
	return i, err
}

const getSessionByTokenFingerprint = `-- name: GetSessionByTokenFingerprint :one
SELECT id, principal_id, token_fingerprint, token_verifier, expires_at, created_at, last_seen_at, revoked_at FROM sessions
WHERE token_fingerprint = ? AND datetime(expires_at) > CURRENT_TIMESTAMP AND revoked_at IS NULL
`

func (q *Queries) GetSessionByTokenFingerprint(ctx context.Context, tokenFingerprint string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenFingerprint, tokenFingerprint)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenFingerprint,
		&i.TokenVerifier,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByTokenFingerprintForAudit = `-- name: GetSessionByTokenFingerprintForAudit :one
SELECT id, principal_id, token_fingerprint, token_verifier, expires_at, created_at, last_seen_at, revoked_at FROM sessions
WHERE token_fingerprint = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSessionByTokenFingerprintForAudit(ctx context.Context, tokenFingerprint string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenFingerprintForAudit, tokenFingerprint)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenFingerprint,
		&i.TokenVerifier,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, title, description, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceWithActiveMetadata = `-- name: GetWorkspaceWithActiveMetadata :one
SELECT
  w.id,
  CASE WHEN a.title IS NOT NULL AND a.title <> '' THEN a.title ELSE w.title END AS title,
  CASE WHEN a.description IS NOT NULL THEN a.description ELSE w.description END AS description,
  COALESCE(active.serving_state_id, '') AS active_serving_state_id,
  w.created_at,
  w.updated_at
FROM workspaces w
LEFT JOIN workspace_active_serving_states active
  ON active.workspace_id = w.id AND active.environment = ?
LEFT JOIN assets a
  ON a.serving_state_id = active.serving_state_id
 AND a.asset_type = 'catalog'
 AND a.logical_asset_id = 'catalog:' || w.id
WHERE w.id = ?
`

type GetWorkspaceWithActiveMetadataParams struct {
	Environment string `json:"environment"`
	ID          string `json:"id"`
}

type GetWorkspaceWithActiveMetadataRow struct {
	ID                   string      `json:"id"`
	Title                interface{} `json:"title"`
	Description          interface{} `json:"description"`
	ActiveServingStateID string      `json:"active_serving_state_id"`
	CreatedAt            string      `json:"created_at"`
	UpdatedAt            string      `json:"updated_at"`
}

func (q *Queries) GetWorkspaceWithActiveMetadata(ctx context.Context, arg GetWorkspaceWithActiveMetadataParams) (GetWorkspaceWithActiveMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceWithActiveMetadata, arg.Environment, arg.ID)
	var i GetWorkspaceWithActiveMetadataRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ActiveServingStateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :exec
INSERT INTO assets (snapshot_id, logical_asset_id, workspace_id, serving_state_id, asset_type, asset_key, parent_logical_asset_id, title, description, source_file, payload_schema, payload_json, content_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAssetParams struct {
	SnapshotID           string `json:"snapshot_id"`
	LogicalAssetID       string `json:"logical_asset_id"`
	WorkspaceID          string `json:"workspace_id"`
	ServingStateID       string `json:"serving_state_id"`
	AssetType            string `json:"asset_type"`
	AssetKey             string `json:"asset_key"`
	ParentLogicalAssetID string `json:"parent_logical_asset_id"`
	Title                string `json:"title"`
	Description          string `json:"description"`
	SourceFile           string `json:"source_file"`
	PayloadSchema        string `json:"payload_schema"`
	PayloadJson          string `json:"payload_json"`
	ContentHash          string `json:"content_hash"`
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, insertAsset,
		arg.SnapshotID,
		arg.LogicalAssetID,
		arg.WorkspaceID,
		arg.ServingStateID,
		arg.AssetType,
		arg.AssetKey,
		arg.ParentLogicalAssetID,
		arg.Title,
		arg.Description,
		arg.SourceFile,
		arg.PayloadSchema,
		arg.PayloadJson,
		arg.ContentHash,
	)
	return err
}

const insertAssetEdge = `-- name: InsertAssetEdge :exec
INSERT INTO asset_edges (id, workspace_id, serving_state_id, from_logical_asset_id, to_logical_asset_id, edge_type)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAssetEdgeParams struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	ServingStateID     string `json:"serving_state_id"`
	FromLogicalAssetID string `json:"from_logical_asset_id"`
	ToLogicalAssetID   string `json:"to_logical_asset_id"`
	EdgeType           string `json:"edge_type"`
}

func (q *Queries) InsertAssetEdge(ctx context.Context, arg InsertAssetEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetEdge,
		arg.ID,
		arg.WorkspaceID,
		arg.ServingStateID,
		arg.FromLogicalAssetID,
		arg.ToLogicalAssetID,
		arg.EdgeType,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, workspace_id, principal_id, action, target_type, target_id, privilege, status, request_id, correlation_id, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	ID            string         `json:"id"`
	WorkspaceID   sql.NullString `json:"workspace_id"`
	PrincipalID   sql.NullString `json:"principal_id"`
	Action        string         `json:"action"`
	TargetType    string         `json:"target_type"`
	TargetID      string         `json:"target_id"`
	Privilege     string         `json:"privilege"`
	Status        string         `json:"status"`
	RequestID     string         `json:"request_id"`
	CorrelationID string         `json:"correlation_id"`
	MetadataJson  string         `json:"metadata_json"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Privilege,
		arg.Status,
		arg.RequestID,
		arg.CorrelationID,
		arg.MetadataJson,
	)
	return err
}

const insertGroupMember = `-- name: InsertGroupMember :exec
INSERT OR IGNORE INTO group_members (workspace_id, group_id, principal_id)
VALUES (?, ?, ?)
`

type InsertGroupMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	GroupID     string `json:"group_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertGroupMember, arg.WorkspaceID, arg.GroupID, arg.PrincipalID)
	return err
}

const insertPlatformRoleBinding = `-- name: InsertPlatformRoleBinding :exec
INSERT OR IGNORE INTO platform_role_bindings (id, role_id, principal_id)
VALUES (?, ?, ?)
`

type InsertPlatformRoleBindingParams struct {
	ID          string `json:"id"`
	RoleID      string `json:"role_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) InsertPlatformRoleBinding(ctx context.Context, arg InsertPlatformRoleBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertPlatformRoleBinding, arg.ID, arg.RoleID, arg.PrincipalID)
	return err
}

const insertQueryEvent = `-- name: InsertQueryEvent :exec
INSERT INTO query_events (
  id,
  workspace_id,
  principal_id,
  surface,
  operation,
  query_kind,
  model_id,
  target,
  object_type,
  object_id,
  request_id,
  correlation_id,
  status,
  duration_ms,
  queue_wait_ms,
  execution_ms,
  execution_state,
  rows_returned,
  bytes_estimate,
  error,
  sql_text,
  plan_text,
  query_json
)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12,
  ?13,
  ?14,
  ?15,
  ?16,
  ?17,
  ?18,
  ?19,
  ?20,
  ?21,
  ?22,
  ?23
)
`

type InsertQueryEventParams struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
	Surface        string `json:"surface"`
	Operation      string `json:"operation"`
	QueryKind      string `json:"query_kind"`
	ModelID        string `json:"model_id"`
	Target         string `json:"target"`
	ObjectType     string `json:"object_type"`
	ObjectID       string `json:"object_id"`
	RequestID      string `json:"request_id"`
	CorrelationID  string `json:"correlation_id"`
	Status         string `json:"status"`
	DurationMs     int64  `json:"duration_ms"`
	QueueWaitMs    int64  `json:"queue_wait_ms"`
	ExecutionMs    int64  `json:"execution_ms"`
	ExecutionState string `json:"execution_state"`
	RowsReturned   int64  `json:"rows_returned"`
	BytesEstimate  int64  `json:"bytes_estimate"`
	Error          string `json:"error"`
	SqlText        string `json:"sql_text"`
	PlanText       string `json:"plan_text"`
	QueryJson      string `json:"query_json"`
}

func (q *Queries) InsertQueryEvent(ctx context.Context, arg InsertQueryEventParams) error {
	_, err := q.db.ExecContext(ctx, insertQueryEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Surface,
		arg.Operation,
		arg.QueryKind,
		arg.ModelID,
		arg.Target,
		arg.ObjectType,
		arg.ObjectID,
		arg.RequestID,
		arg.CorrelationID,
		arg.Status,
		arg.DurationMs,
		arg.QueueWaitMs,
		arg.ExecutionMs,
		arg.ExecutionState,
		arg.RowsReturned,
		arg.BytesEstimate,
		arg.Error,
		arg.SqlText,
		arg.PlanText,
		arg.QueryJson,
	)
	return err
}

const insertRoleBinding = `-- name: InsertRoleBinding :exec
INSERT OR IGNORE INTO role_bindings (id, workspace_id, role_id, principal_id, group_id)
VALUES (?, ?, ?, ?, ?)
`

type InsertRoleBindingParams struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	RoleID      string         `json:"role_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
}

func (q *Queries) InsertRoleBinding(ctx context.Context, arg InsertRoleBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertRoleBinding,
		arg.ID,
		arg.WorkspaceID,
		arg.RoleID,
		arg.PrincipalID,
		arg.GroupID,
	)
	return err
}

const insertServingStateArtifact = `-- name: InsertServingStateArtifact :exec
INSERT INTO serving_state_artifacts (id, serving_state_id, workspace_id, environment, digest, format, path, data_root, manifest_json, size_bytes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(serving_state_id) DO UPDATE SET
  environment = excluded.environment,
  digest = excluded.digest,
  format = excluded.format,
  path = excluded.path,
  data_root = excluded.data_root,
  manifest_json = excluded.manifest_json,
  size_bytes = excluded.size_bytes
`

type InsertServingStateArtifactParams struct {
	ID             string `json:"id"`
	ServingStateID string `json:"serving_state_id"`
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	Digest         string `json:"digest"`
	Format         string `json:"format"`
	Path           string `json:"path"`
	DataRoot       string `json:"data_root"`
	ManifestJson   string `json:"manifest_json"`
	SizeBytes      int64  `json:"size_bytes"`
}

func (q *Queries) InsertServingStateArtifact(ctx context.Context, arg InsertServingStateArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertServingStateArtifact,
		arg.ID,
		arg.ServingStateID,
		arg.WorkspaceID,
		arg.Environment,
		arg.Digest,
		arg.Format,
		arg.Path,
		arg.DataRoot,
		arg.ManifestJson,
		arg.SizeBytes,
	)
	return err
}

const listAPITokensByPrincipal = `-- name: ListAPITokensByPrincipal :many
SELECT id, principal_id, workspace_id, name, token_fingerprint, token_verifier, privileges_json, expires_at, created_at, last_used_at, revoked_at FROM api_tokens
WHERE principal_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByPrincipal(ctx context.Context, principalID string) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.WorkspaceID,
			&i.Name,
			&i.TokenFingerprint,
			&i.TokenVerifier,
			&i.PrivilegesJson,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDuckLakeSnapshots = `-- name: ListActiveDuckLakeSnapshots :many
SELECT DISTINCT ducklake_snapshot_id
FROM serving_states
WHERE ducklake_snapshot_id > 0
  AND status = 'active'
ORDER BY ducklake_snapshot_id
`

func (q *Queries) ListActiveDuckLakeSnapshots(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDuckLakeSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentConversations = `-- name: ListAgentConversations :many
SELECT id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at FROM agent_conversations
WHERE workspace_id = ?1
  AND principal_id = ?2
  AND status = 'active'
ORDER BY updated_at DESC, created_at DESC
`

type ListAgentConversationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) ListAgentConversations(ctx context.Context, arg ListAgentConversationsParams) ([]AgentConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConversations, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversation{}
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Title,
			&i.Status,
			&i.MetadataJson,
			&i.TranscriptJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentEvents = `-- name: ListAgentEvents :many
SELECT e.id, e.run_id, e.seq, e.event_type, e.severity, e.payload_json, e.created_at
FROM agent_events e
JOIN agent_runs r ON r.id = e.run_id
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE r.id = ?1
  AND c.workspace_id = ?2
  AND c.principal_id = ?3
ORDER BY e.seq
`

type ListAgentEventsParams struct {
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) ListAgentEvents(ctx context.Context, arg ListAgentEventsParams) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentEvents, arg.RunID, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.EventType,
			&i.Severity,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessages = `-- name: ListAgentMessages :many
SELECT m.id, m.conversation_id, m.run_id, m.seq, m.role, m.content_text, m.content_json, m.tool_call_id, m.tool_name, m.is_error, m.created_at
FROM agent_messages m
JOIN agent_conversations c ON c.id = m.conversation_id
WHERE c.id = ?1
  AND c.workspace_id = ?2
  AND c.principal_id = ?3
ORDER BY m.seq
`

type ListAgentMessagesParams struct {
	ConversationID string `json:"conversation_id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) ListAgentMessages(ctx context.Context, arg ListAgentMessagesParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessages, arg.ConversationID, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Seq,
			&i.Role,
			&i.ContentText,
			&i.ContentJson,
			&i.ToolCallID,
			&i.ToolName,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRuns = `-- name: ListAgentRuns :many
SELECT r.id, r.conversation_id, r.status, r.model, r.stop_reason, r.input_tokens, r.output_tokens, r.total_tokens, r.error, r.started_at, r.finished_at, r.metadata_json
FROM agent_runs r
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE c.id = ?1
  AND c.workspace_id = ?2
  AND c.principal_id = ?3
ORDER BY r.started_at DESC
`

type ListAgentRunsParams struct {
	ConversationID string `json:"conversation_id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) ListAgentRuns(ctx context.Context, arg ListAgentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRuns, arg.ConversationID, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Status,
			&i.Model,
			&i.StopReason,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEdgesByServingState = `-- name: ListAssetEdgesByServingState :many
SELECT id, workspace_id, serving_state_id, from_logical_asset_id, to_logical_asset_id, edge_type, created_at FROM asset_edges WHERE serving_state_id = ? ORDER BY edge_type, from_logical_asset_id, to_logical_asset_id
`

func (q *Queries) ListAssetEdgesByServingState(ctx context.Context, servingStateID string) ([]AssetEdge, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEdgesByServingState, servingStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetEdge{}
	for rows.Next() {
		var i AssetEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ServingStateID,
			&i.FromLogicalAssetID,
			&i.ToLogicalAssetID,
			&i.EdgeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetVersions = `-- name: ListAssetVersions :many
SELECT
  d.id AS serving_state_id,
  d.workspace_id,
  d.environment,
  d.status,
  d.digest,
  d.created_by,
  d.created_at,
  d.activated_at,
  a.snapshot_id,
  a.logical_asset_id,
  a.source_file,
  a.content_hash
FROM serving_states d
JOIN assets a ON a.serving_state_id = d.id
WHERE d.workspace_id = ?
  AND d.environment = ?
  AND a.logical_asset_id = ?
  AND d.source = 'publish'
  AND d.status IN ('active', 'draining', 'inactive', 'validated')
  AND NOT EXISTS (
    SELECT 1
    FROM serving_states newer
    JOIN assets newer_asset ON newer_asset.serving_state_id = newer.id
    WHERE newer.workspace_id = d.workspace_id
      AND newer.environment = d.environment
      AND newer.source = 'publish'
      AND newer.status IN ('active', 'draining', 'inactive', 'validated')
      AND newer_asset.logical_asset_id = a.logical_asset_id
      AND newer_asset.content_hash = a.content_hash
      AND (
        COALESCE(newer.activated_at, newer.created_at) > COALESCE(d.activated_at, d.created_at)
        OR (
          COALESCE(newer.activated_at, newer.created_at) = COALESCE(d.activated_at, d.created_at)
          AND newer.created_at > d.created_at
        )
        OR (
          COALESCE(newer.activated_at, newer.created_at) = COALESCE(d.activated_at, d.created_at)
          AND newer.created_at = d.created_at
          AND newer.id > d.id
        )
      )
  )
ORDER BY
  COALESCE(d.activated_at, d.created_at) DESC,
  d.created_at DESC,
  d.id DESC
`

type ListAssetVersionsParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	LogicalAssetID string `json:"logical_asset_id"`
}

type ListAssetVersionsRow struct {
	ServingStateID string         `json:"serving_state_id"`
	WorkspaceID    string         `json:"workspace_id"`
	Environment    string         `json:"environment"`
	Status         string         `json:"status"`
	Digest         string         `json:"digest"`
	CreatedBy      string         `json:"created_by"`
	CreatedAt      string         `json:"created_at"`
	ActivatedAt    sql.NullString `json:"activated_at"`
	SnapshotID     string         `json:"snapshot_id"`
	LogicalAssetID string         `json:"logical_asset_id"`
	SourceFile     string         `json:"source_file"`
	ContentHash    string         `json:"content_hash"`
}

func (q *Queries) ListAssetVersions(ctx context.Context, arg ListAssetVersionsParams) ([]ListAssetVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetVersions, arg.WorkspaceID, arg.Environment, arg.LogicalAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetVersionsRow{}
	for rows.Next() {
		var i ListAssetVersionsRow
		if err := rows.Scan(
			&i.ServingStateID,
			&i.WorkspaceID,
			&i.Environment,
			&i.Status,
			&i.Digest,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.SourceFile,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByServingState = `-- name: ListAssetsByServingState :many
SELECT snapshot_id, logical_asset_id, workspace_id, serving_state_id, asset_type, asset_key, parent_logical_asset_id, title, description, source_file, payload_schema, payload_json, content_hash, created_at FROM assets WHERE serving_state_id = ? ORDER BY asset_type, asset_key
`

func (q *Queries) ListAssetsByServingState(ctx context.Context, servingStateID string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByServingState, servingStateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.WorkspaceID,
			&i.ServingStateID,
			&i.AssetType,
			&i.AssetKey,
			&i.ParentLogicalAssetID,
			&i.Title,
			&i.Description,
			&i.SourceFile,
			&i.PayloadSchema,
			&i.PayloadJson,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, workspace_id, principal_id, "action", target_type, target_id, privilege, status, request_id, correlation_id, metadata_json, created_at FROM audit_events
WHERE (? = '' OR workspace_id = ?)
  AND (? = '' OR principal_id = ?)
  AND (? = '' OR action = ?)
  AND (? = '' OR target_type = ?)
  AND (? = '' OR target_id = ?)
  AND (? = '' OR created_at >= ?)
  AND (? = '' OR created_at <= ?)
  AND (? = '' OR created_at < ? OR (created_at = ? AND id < ?))
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListAuditEventsParams struct {
	Column1     interface{}    `json:"column_1"`
	WorkspaceID sql.NullString `json:"workspace_id"`
	Column3     interface{}    `json:"column_3"`
	PrincipalID sql.NullString `json:"principal_id"`
	Column5     interface{}    `json:"column_5"`
	Action      string         `json:"action"`
	Column7     interface{}    `json:"column_7"`
	TargetType  string         `json:"target_type"`
	Column9     interface{}    `json:"column_9"`
	TargetID    string         `json:"target_id"`
	Column11    interface{}    `json:"column_11"`
	CreatedAt   string         `json:"created_at"`
	Column13    interface{}    `json:"column_13"`
	CreatedAt_2 string         `json:"created_at_2"`
	Column15    interface{}    `json:"column_15"`
	CreatedAt_3 string         `json:"created_at_3"`
	CreatedAt_4 string         `json:"created_at_4"`
	ID          string         `json:"id"`
	Limit       int64          `json:"limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents,
		arg.Column1,
		arg.WorkspaceID,
		arg.Column3,
		arg.PrincipalID,
		arg.Column5,
		arg.Action,
		arg.Column7,
		arg.TargetType,
		arg.Column9,
		arg.TargetID,
		arg.Column11,
		arg.CreatedAt,
		arg.Column13,
		arg.CreatedAt_2,
		arg.Column15,
		arg.CreatedAt_3,
		arg.CreatedAt_4,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Privilege,
			&i.Status,
			&i.RequestID,
			&i.CorrelationID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT
  gm.group_id,
  gm.workspace_id,
  gm.principal_id,
  p.email,
  p.display_name,
  gm.created_at
FROM group_members gm
JOIN principals p ON p.id = gm.principal_id
WHERE gm.workspace_id = ? AND gm.group_id = ?
ORDER BY p.email, p.display_name, gm.principal_id
`

type ListGroupMembersParams struct {
	WorkspaceID string `json:"workspace_id"`
	GroupID     string `json:"group_id"`
}

type ListGroupMembersRow struct {
	GroupID     string `json:"group_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, arg.WorkspaceID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByWorkspace = `-- name: ListGroupsByWorkspace :many
SELECT id, workspace_id, provider, external_id, name, created_at FROM groups
WHERE workspace_id = ?
   OR (workspace_id = '' AND provider = 'scim')
ORDER BY name, id
`

func (q *Queries) ListGroupsByWorkspace(ctx context.Context, workspaceID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.ExternalID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeasedDuckLakeSnapshots = `-- name: ListLeasedDuckLakeSnapshots :many
SELECT DISTINCT ducklake_snapshot_id
FROM query_snapshot_leases
WHERE ducklake_snapshot_id > 0
  AND released_at IS NULL
  AND expires_at > CURRENT_TIMESTAMP
ORDER BY ducklake_snapshot_id
`

func (q *Queries) ListLeasedDuckLakeSnapshots(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listLeasedDuckLakeSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueryEvents = `-- name: ListQueryEvents :many
SELECT id, workspace_id, principal_id, surface, operation, query_kind, model_id, target, object_type, object_id, request_id, correlation_id, status, duration_ms, queue_wait_ms, execution_ms, execution_state, rows_returned, bytes_estimate, error, sql_text, plan_text, query_json, created_at
FROM query_events
WHERE (?1 = '' OR workspace_id = ?1)
  AND (?2 = '' OR principal_id = ?2)
  AND (?3 = '' OR surface = ?3)
  AND (?4 = '' OR operation = ?4)
  AND (?5 = '' OR query_kind = ?5)
  AND (?6 = '' OR model_id = ?6)
  AND (?7 = '' OR target = ?7)
  AND (?8 = '' OR status = ?8)
  AND (?9 = '' OR created_at >= ?9)
  AND (?10 = '' OR created_at <= ?10)
  AND (
    ?11 = ''
    OR target LIKE '%' || ?11 || '%'
    OR sql_text LIKE '%' || ?11 || '%'
    OR query_json LIKE '%' || ?11 || '%'
  )
  AND (
    ?12 = ''
    OR created_at < ?12
    OR (created_at = ?12 AND id < ?13)
  )
ORDER BY created_at DESC, id DESC
LIMIT ?14
`

type ListQueryEventsParams struct {
	WorkspaceID interface{} `json:"workspace_id"`
	PrincipalID interface{} `json:"principal_id"`
	Surface     interface{} `json:"surface"`
	Operation   interface{} `json:"operation"`
	QueryKind   interface{} `json:"query_kind"`
	ModelID     interface{} `json:"model_id"`
	Target      interface{} `json:"target"`
	Status      interface{} `json:"status"`
	FromTime    interface{} `json:"from_time"`
	ToTime      interface{} `json:"to_time"`
	Search      interface{} `json:"search"`
	CursorTime  interface{} `json:"cursor_time"`
	CursorID    string      `json:"cursor_id"`
	Limit       int64       `json:"limit"`
}

func (q *Queries) ListQueryEvents(ctx context.Context, arg ListQueryEventsParams) ([]QueryEvent, error) {
	rows, err := q.db.QueryContext(ctx, listQueryEvents,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Surface,
		arg.Operation,
		arg.QueryKind,
		arg.ModelID,
		arg.Target,
		arg.Status,
		arg.FromTime,
		arg.ToTime,
		arg.Search,
		arg.CursorTime,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryEvent{}
	for rows.Next() {
		var i QueryEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Surface,
			&i.Operation,
			&i.QueryKind,
			&i.ModelID,
			&i.Target,
			&i.ObjectType,
			&i.ObjectID,
			&i.RequestID,
			&i.CorrelationID,
			&i.Status,
			&i.DurationMs,
			&i.QueueWaitMs,
			&i.ExecutionMs,
			&i.ExecutionState,
			&i.RowsReturned,
			&i.BytesEstimate,
			&i.Error,
			&i.SqlText,
			&i.PlanText,
			&i.QueryJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferencedDuckLakeSnapshots = `-- name: ListReferencedDuckLakeSnapshots :many
SELECT DISTINCT ducklake_snapshot_id
FROM serving_states
WHERE ducklake_snapshot_id > 0
  AND status = 'active'
ORDER BY ducklake_snapshot_id
`

func (q *Queries) ListReferencedDuckLakeSnapshots(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listReferencedDuckLakeSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var ducklake_snapshot_id int64
		if err := rows.Scan(&ducklake_snapshot_id); err != nil {
			return nil, err
		}
		items = append(items, ducklake_snapshot_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsByWorkspace = `-- name: ListRoleBindingsByWorkspace :many
SELECT
  rb.id,
  rb.workspace_id,
  CASE
    WHEN NULLIF(rb.principal_id, '') IS NOT NULL AND p.kind = 'service_principal' THEN 'service_principal'
    WHEN NULLIF(rb.principal_id, '') IS NOT NULL THEN 'principal'
    ELSE 'group'
  END AS subject_type,
  COALESCE(NULLIF(rb.principal_id, ''), rb.group_id, '') AS subject_id,
  rb.principal_id,
  rb.group_id,
  p.email,
  p.display_name,
  g.name AS group_name,
  r.name AS role_name,
  rb.created_at
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
LEFT JOIN principals p ON p.id = NULLIF(rb.principal_id, '')
LEFT JOIN groups g ON g.id = rb.group_id
WHERE rb.workspace_id = ?
ORDER BY subject_type, p.email, g.name, r.name
`

type ListRoleBindingsByWorkspaceRow struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	SubjectType string         `json:"subject_type"`
	SubjectID   string         `json:"subject_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
	Email       sql.NullString `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	GroupName   sql.NullString `json:"group_name"`
	RoleName    string         `json:"role_name"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) ListRoleBindingsByWorkspace(ctx context.Context, workspaceID string) ([]ListRoleBindingsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoleBindingsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleBindingsByWorkspaceRow{}
	for rows.Next() {
		var i ListRoleBindingsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubjectType,
			&i.SubjectID,
			&i.PrincipalID,
			&i.GroupID,
			&i.Email,
			&i.DisplayName,
			&i.GroupName,
			&i.RoleName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, privileges_json FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.PrivilegesJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroupMembers = `-- name: ListSCIMGroupMembers :many
SELECT
  gm.group_id,
  gm.workspace_id,
  gm.principal_id,
  p.email,
  p.display_name,
  gm.created_at
FROM group_members gm
JOIN principals p ON p.id = gm.principal_id
WHERE gm.workspace_id = '' AND gm.group_id = ?
ORDER BY p.email, p.display_name, gm.principal_id
`

type ListSCIMGroupMembersRow struct {
	GroupID     string `json:"group_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) ListSCIMGroupMembers(ctx context.Context, groupID string) ([]ListSCIMGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSCIMGroupMembersRow{}
	for rows.Next() {
		var i ListSCIMGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMGroups = `-- name: ListSCIMGroups :many
SELECT id, workspace_id, provider, external_id, name, created_at FROM groups
WHERE workspace_id = ''
  AND provider = 'scim'
  AND (?1 = '' OR external_id = ?1)
  AND (?2 = '' OR lower(name) = lower(?2))
ORDER BY name, id
`

type ListSCIMGroupsParams struct {
	ExternalID  interface{} `json:"external_id"`
	DisplayName interface{} `json:"display_name"`
}

func (q *Queries) ListSCIMGroups(ctx context.Context, arg ListSCIMGroupsParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMGroups, arg.ExternalID, arg.DisplayName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.ExternalID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCIMPrincipals = `-- name: ListSCIMPrincipals :many
SELECT p.id, p.kind, p.email, p.display_name, p.disabled_at, p.created_at, p.updated_at
FROM principals p
JOIN external_identities ei ON ei.principal_id = p.id
WHERE p.kind = 'user'
  AND ei.provider = 'scim'
  AND (?1 = '' OR ei.subject = ?1)
  AND (
    ?2 = ''
    OR lower(p.email) = lower(?2)
    OR lower(ei.email) = lower(?2)
  )
ORDER BY p.email, p.display_name, p.id
`

type ListSCIMPrincipalsParams struct {
	Subject  interface{} `json:"subject"`
	UserName interface{} `json:"user_name"`
}

func (q *Queries) ListSCIMPrincipals(ctx context.Context, arg ListSCIMPrincipalsParams) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listSCIMPrincipals, arg.Subject, arg.UserName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Email,
			&i.DisplayName,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicePrincipals = `-- name: ListServicePrincipals :many
SELECT id, kind, email, display_name, disabled_at, created_at, updated_at FROM principals
WHERE kind = 'service_principal'
ORDER BY display_name, id
`

func (q *Queries) ListServicePrincipals(ctx context.Context) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listServicePrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Principal{}
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Email,
			&i.DisplayName,
			&i.DisabledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServingStates = `-- name: ListServingStates :many
SELECT id, workspace_id, environment, status, source, digest, manifest_json, ducklake_snapshot_id, created_by, created_at, activated_at, superseded_at, error FROM serving_states
WHERE workspace_id = ? AND environment = ?
ORDER BY created_at DESC
`

type ListServingStatesParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

func (q *Queries) ListServingStates(ctx context.Context, arg ListServingStatesParams) ([]ServingState, error) {
	rows, err := q.db.QueryContext(ctx, listServingStates, arg.WorkspaceID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServingState{}
	for rows.Next() {
		var i ServingState
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Environment,
			&i.Status,
			&i.Source,
			&i.Digest,
			&i.ManifestJson,
			&i.DucklakeSnapshotID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.SupersededAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByPrincipal = `-- name: ListSessionsByPrincipal :many
SELECT id, principal_id, token_fingerprint, token_verifier, expires_at, created_at, last_seen_at, revoked_at FROM sessions
WHERE principal_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByPrincipal(ctx context.Context, principalID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.TokenFingerprint,
			&i.TokenVerifier,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, title, description, created_at, updated_at FROM workspaces ORDER BY created_at
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithActiveMetadata = `-- name: ListWorkspacesWithActiveMetadata :many
SELECT
  w.id,
  CASE WHEN a.title IS NOT NULL AND a.title <> '' THEN a.title ELSE w.title END AS title,
  CASE WHEN a.description IS NOT NULL THEN a.description ELSE w.description END AS description,
  COALESCE(active.serving_state_id, '') AS active_serving_state_id,
  w.created_at,
  w.updated_at
FROM workspaces w
LEFT JOIN workspace_active_serving_states active
  ON active.workspace_id = w.id AND active.environment = ?
LEFT JOIN assets a
  ON a.serving_state_id = active.serving_state_id
 AND a.asset_type = 'catalog'
 AND a.logical_asset_id = 'catalog:' || w.id
ORDER BY w.created_at
`

type ListWorkspacesWithActiveMetadataRow struct {
	ID                   string      `json:"id"`
	Title                interface{} `json:"title"`
	Description          interface{} `json:"description"`
	ActiveServingStateID string      `json:"active_serving_state_id"`
	CreatedAt            string      `json:"created_at"`
	UpdatedAt            string      `json:"updated_at"`
}

func (q *Queries) ListWorkspacesWithActiveMetadata(ctx context.Context, environment string) ([]ListWorkspacesWithActiveMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesWithActiveMetadata, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesWithActiveMetadataRow{}
	for rows.Next() {
		var i ListWorkspacesWithActiveMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ActiveServingStateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeleteScheduledServingStatesDeleted = `-- name: MarkDeleteScheduledServingStatesDeleted :exec
UPDATE serving_states
SET status = 'deleted', error = ''
WHERE status = 'delete_scheduled'
`

func (q *Queries) MarkDeleteScheduledServingStatesDeleted(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markDeleteScheduledServingStatesDeleted)
	return err
}

const markDrainingServingStatesDeleteScheduled = `-- name: MarkDrainingServingStatesDeleteScheduled :exec
UPDATE serving_states
SET status = 'delete_scheduled', error = ''
WHERE status = 'draining'
`

func (q *Queries) MarkDrainingServingStatesDeleteScheduled(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markDrainingServingStatesDeleteScheduled)
	return err
}

const markOtherServingStatesDraining = `-- name: MarkOtherServingStatesDraining :exec
UPDATE serving_states
SET status = 'draining',
    superseded_at = CURRENT_TIMESTAMP,
    error = ''
WHERE workspace_id = ?
  AND environment = ?
  AND id <> ?
  AND status = 'active'
`

type MarkOtherServingStatesDrainingParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	ID          string `json:"id"`
}

func (q *Queries) MarkOtherServingStatesDraining(ctx context.Context, arg MarkOtherServingStatesDrainingParams) error {
	_, err := q.db.ExecContext(ctx, markOtherServingStatesDraining, arg.WorkspaceID, arg.Environment, arg.ID)
	return err
}

const markOtherServingStatesInactive = `-- name: MarkOtherServingStatesInactive :exec
UPDATE serving_states
SET status = 'inactive'
WHERE workspace_id = ? AND environment = ? AND id <> ? AND status = 'active'
`

type MarkOtherServingStatesInactiveParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	ID          string `json:"id"`
}

func (q *Queries) MarkOtherServingStatesInactive(ctx context.Context, arg MarkOtherServingStatesInactiveParams) error {
	_, err := q.db.ExecContext(ctx, markOtherServingStatesInactive, arg.WorkspaceID, arg.Environment, arg.ID)
	return err
}

const markServingStateActive = `-- name: MarkServingStateActive :exec
UPDATE serving_states
SET status = 'active', activated_at = CURRENT_TIMESTAMP, error = ''
WHERE id = ?
`

func (q *Queries) MarkServingStateActive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markServingStateActive, id)
	return err
}

const releaseExpiredQuerySnapshotLeases = `-- name: ReleaseExpiredQuerySnapshotLeases :exec
UPDATE query_snapshot_leases
SET released_at = CURRENT_TIMESTAMP
WHERE released_at IS NULL
  AND expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) ReleaseExpiredQuerySnapshotLeases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, releaseExpiredQuerySnapshotLeases)
	return err
}

const releaseQuerySnapshotLease = `-- name: ReleaseQuerySnapshotLease :exec
UPDATE query_snapshot_leases
SET released_at = COALESCE(released_at, CURRENT_TIMESTAMP)
WHERE id = ?
`

func (q *Queries) ReleaseQuerySnapshotLease(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, releaseQuerySnapshotLease, id)
	return err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE id = ?
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeAPIToken, id)
	return err
}

const revokeAPITokenForPrincipal = `-- name: RevokeAPITokenForPrincipal :one
UPDATE api_tokens
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE principal_id = ? AND id = ?
RETURNING id, principal_id, workspace_id, name, token_fingerprint, token_verifier, privileges_json, expires_at, created_at, last_used_at, revoked_at
`

type RevokeAPITokenForPrincipalParams struct {
	PrincipalID string `json:"principal_id"`
	ID          string `json:"id"`
}

func (q *Queries) RevokeAPITokenForPrincipal(ctx context.Context, arg RevokeAPITokenForPrincipalParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, revokeAPITokenForPrincipal, arg.PrincipalID, arg.ID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.WorkspaceID,
		&i.Name,
		&i.TokenFingerprint,
		&i.TokenVerifier,
		&i.PrivilegesJson,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAPITokensByPrincipal = `-- name: RevokeAPITokensByPrincipal :exec
UPDATE api_tokens
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE principal_id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeAPITokensByPrincipal(ctx context.Context, principalID string) error {
	_, err := q.db.ExecContext(ctx, revokeAPITokensByPrincipal, principalID)
	return err
}

const revokeServicePrincipalSecret = `-- name: RevokeServicePrincipalSecret :exec
UPDATE service_principal_secrets
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE service_principal_id = ? AND id = ?
`

type RevokeServicePrincipalSecretParams struct {
	ServicePrincipalID string `json:"service_principal_id"`
	ID                 string `json:"id"`
}

func (q *Queries) RevokeServicePrincipalSecret(ctx context.Context, arg RevokeServicePrincipalSecretParams) error {
	_, err := q.db.ExecContext(ctx, revokeServicePrincipalSecret, arg.ServicePrincipalID, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE id = ?
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const revokeSessionForPrincipal = `-- name: RevokeSessionForPrincipal :one
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE principal_id = ? AND id = ?
RETURNING id, principal_id, token_fingerprint, token_verifier, expires_at, created_at, last_seen_at, revoked_at
`

type RevokeSessionForPrincipalParams struct {
	PrincipalID string `json:"principal_id"`
	ID          string `json:"id"`
}

func (q *Queries) RevokeSessionForPrincipal(ctx context.Context, arg RevokeSessionForPrincipalParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, revokeSessionForPrincipal, arg.PrincipalID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenFingerprint,
		&i.TokenVerifier,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSessionsByPrincipal = `-- name: RevokeSessionsByPrincipal :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE principal_id = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsByPrincipal(ctx context.Context, principalID string) error {
	_, err := q.db.ExecContext(ctx, revokeSessionsByPrincipal, principalID)
	return err
}

const scheduleExpiredServingStateDeletion = `-- name: ScheduleExpiredServingStateDeletion :exec
UPDATE serving_states
SET status = 'delete_scheduled', error = ''
WHERE status = 'expired'
`

func (q *Queries) ScheduleExpiredServingStateDeletion(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, scheduleExpiredServingStateDeletion)
	return err
}

const setActiveServingState = `-- name: SetActiveServingState :exec
INSERT INTO workspace_active_serving_states (workspace_id, environment, serving_state_id, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(workspace_id, environment) DO UPDATE SET
  serving_state_id = excluded.serving_state_id,
  updated_at = CURRENT_TIMESTAMP
`

type SetActiveServingStateParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	ServingStateID string `json:"serving_state_id"`
}

func (q *Queries) SetActiveServingState(ctx context.Context, arg SetActiveServingStateParams) error {
	_, err := q.db.ExecContext(ctx, setActiveServingState, arg.WorkspaceID, arg.Environment, arg.ServingStateID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}

const updateAgentConversationTranscript = `-- name: UpdateAgentConversationTranscript :one
UPDATE agent_conversations
SET transcript_json = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND workspace_id = ?3
  AND principal_id = ?4
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type UpdateAgentConversationTranscriptParams struct {
	TranscriptJson string `json:"transcript_json"`
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) UpdateAgentConversationTranscript(ctx context.Context, arg UpdateAgentConversationTranscriptParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, updateAgentConversationTranscript,
		arg.TranscriptJson,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateDefaultAgentConversationTitle = `-- name: UpdateDefaultAgentConversationTitle :one
UPDATE agent_conversations
SET title = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND workspace_id = ?3
  AND principal_id = ?4
  AND status = 'active'
  AND title = 'New conversation'
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type UpdateDefaultAgentConversationTitleParams struct {
	Title       string `json:"title"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) UpdateDefaultAgentConversationTitle(ctx context.Context, arg UpdateDefaultAgentConversationTitleParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, updateDefaultAgentConversationTitle,
		arg.Title,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateRoleBindingByID = `-- name: UpdateRoleBindingByID :exec
UPDATE role_bindings
SET role_id = ?, principal_id = ?, group_id = ?
WHERE workspace_id = ? AND id = ?
`

type UpdateRoleBindingByIDParams struct {
	RoleID      string         `json:"role_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
	WorkspaceID string         `json:"workspace_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateRoleBindingByID(ctx context.Context, arg UpdateRoleBindingByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateRoleBindingByID,
		arg.RoleID,
		arg.PrincipalID,
		arg.GroupID,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const updateServingStateDuckLakeSnapshot = `-- name: UpdateServingStateDuckLakeSnapshot :exec
UPDATE serving_states
SET ducklake_snapshot_id = ?
WHERE id = ?
`

type UpdateServingStateDuckLakeSnapshotParams struct {
	DucklakeSnapshotID int64  `json:"ducklake_snapshot_id"`
	ID                 string `json:"id"`
}

func (q *Queries) UpdateServingStateDuckLakeSnapshot(ctx context.Context, arg UpdateServingStateDuckLakeSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, updateServingStateDuckLakeSnapshot, arg.DucklakeSnapshotID, arg.ID)
	return err
}

const updateServingStateStatus = `-- name: UpdateServingStateStatus :exec
UPDATE serving_states
SET status = ?, error = ?
WHERE id = ?
`

type UpdateServingStateStatusParams struct {
	Status string `json:"status"`
	Error  string `json:"error"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateServingStateStatus(ctx context.Context, arg UpdateServingStateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateServingStateStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const updateServingStateValidated = `-- name: UpdateServingStateValidated :exec
UPDATE serving_states
SET status = ?, digest = ?, manifest_json = ?, error = ''
WHERE id = ?
`

type UpdateServingStateValidatedParams struct {
	Status       string `json:"status"`
	Digest       string `json:"digest"`
	ManifestJson string `json:"manifest_json"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateServingStateValidated(ctx context.Context, arg UpdateServingStateValidatedParams) error {
	_, err := q.db.ExecContext(ctx, updateServingStateValidated,
		arg.Status,
		arg.Digest,
		arg.ManifestJson,
		arg.ID,
	)
	return err
}

const upsertExternalIdentity = `-- name: UpsertExternalIdentity :exec
INSERT INTO external_identities (id, principal_id, provider, tenant_id, subject, email, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(provider, tenant_id, subject) DO UPDATE SET
  principal_id = excluded.principal_id,
  email = excluded.email,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertExternalIdentityParams struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
	Provider    string `json:"provider"`
	TenantID    string `json:"tenant_id"`
	Subject     string `json:"subject"`
	Email       string `json:"email"`
}

func (q *Queries) UpsertExternalIdentity(ctx context.Context, arg UpsertExternalIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertExternalIdentity,
		arg.ID,
		arg.PrincipalID,
		arg.Provider,
		arg.TenantID,
		arg.Subject,
		arg.Email,
	)
	return err
}

const upsertGroup = `-- name: UpsertGroup :exec
INSERT INTO groups (id, workspace_id, provider, external_id, name)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(workspace_id, provider, external_id) DO UPDATE SET
  name = excluded.name
`

type UpsertGroupParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Provider    string `json:"provider"`
	ExternalID  string `json:"external_id"`
	Name        string `json:"name"`
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertGroup,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.ExternalID,
		arg.Name,
	)
	return err
}

const upsertPrincipal = `-- name: UpsertPrincipal :exec
INSERT INTO principals (id, kind, email, display_name, updated_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  kind = excluded.kind,
  email = excluded.email,
  display_name = excluded.display_name,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertPrincipalParams struct {
	ID          string `json:"id"`
	Kind        string `json:"kind"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpsertPrincipal(ctx context.Context, arg UpsertPrincipalParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrincipal,
		arg.ID,
		arg.Kind,
		arg.Email,
		arg.DisplayName,
	)
	return err
}

const upsertRole = `-- name: UpsertRole :exec
INSERT INTO roles (id, name, privileges_json)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET privileges_json = excluded.privileges_json
`

type UpsertRoleParams struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	PrivilegesJson string `json:"privileges_json"`
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) error {
	_, err := q.db.ExecContext(ctx, upsertRole, arg.ID, arg.Name, arg.PrivilegesJson)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
INSERT INTO workspaces (id, title, description, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertWorkspaceParams struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspace, arg.ID, arg.Title, arg.Description)
	return err
}
