// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const appendAgentEvent = `-- name: AppendAgentEvent :one
INSERT INTO agent_events (id, run_id, seq, event_type, severity, payload_json)
SELECT
  ?1,
  r.id,
  ?2,
  ?3,
  ?4,
  ?5
FROM agent_runs r
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE r.id = ?6
  AND c.principal_id = ?7
RETURNING id, run_id, seq, event_type, severity, payload_json, created_at
`

type AppendAgentEventParams struct {
	ID          string `json:"id"`
	Seq         int64  `json:"seq"`
	EventType   string `json:"event_type"`
	Severity    string `json:"severity"`
	PayloadJson string `json:"payload_json"`
	RunID       string `json:"run_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) AppendAgentEvent(ctx context.Context, arg AppendAgentEventParams) (AgentEvent, error) {
	row := q.db.QueryRowContext(ctx, appendAgentEvent,
		arg.ID,
		arg.Seq,
		arg.EventType,
		arg.Severity,
		arg.PayloadJson,
		arg.RunID,
		arg.PrincipalID,
	)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.EventType,
		&i.Severity,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const appendAgentMessage = `-- name: AppendAgentMessage :one
INSERT INTO agent_messages (id, conversation_id, run_id, seq, role, content_text, content_json, tool_call_id, tool_name, is_error)
SELECT
  ?1,
  c.id,
  NULLIF(?2, ''),
  COALESCE((SELECT MAX(seq) + 1 FROM agent_messages WHERE conversation_id = c.id), 1),
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
FROM agent_conversations c
WHERE c.id = ?9
  AND c.principal_id = ?10
RETURNING id, conversation_id, run_id, seq, role, content_text, content_json, tool_call_id, tool_name, is_error, created_at
`

type AppendAgentMessageParams struct {
	ID             string      `json:"id"`
	RunID          interface{} `json:"run_id"`
	Role           string      `json:"role"`
	ContentText    string      `json:"content_text"`
	ContentJson    string      `json:"content_json"`
	ToolCallID     string      `json:"tool_call_id"`
	ToolName       string      `json:"tool_name"`
	IsError        bool        `json:"is_error"`
	ConversationID string      `json:"conversation_id"`
	PrincipalID    string      `json:"principal_id"`
}

func (q *Queries) AppendAgentMessage(ctx context.Context, arg AppendAgentMessageParams) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, appendAgentMessage,
		arg.ID,
		arg.RunID,
		arg.Role,
		arg.ContentText,
		arg.ContentJson,
		arg.ToolCallID,
		arg.ToolName,
		arg.IsError,
		arg.ConversationID,
		arg.PrincipalID,
	)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RunID,
		&i.Seq,
		&i.Role,
		&i.ContentText,
		&i.ContentJson,
		&i.ToolCallID,
		&i.ToolName,
		&i.IsError,
		&i.CreatedAt,
	)
	return i, err
}

const archiveAgentConversation = `-- name: ArchiveAgentConversation :one
UPDATE agent_conversations
SET status = 'archived',
    archived_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
  AND principal_id = ?2
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type ArchiveAgentConversationParams struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) ArchiveAgentConversation(ctx context.Context, arg ArchiveAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, archiveAgentConversation, arg.ID, arg.PrincipalID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const clearAssetEdgesForDeployment = `-- name: ClearAssetEdgesForDeployment :exec
DELETE FROM asset_edges WHERE deployment_id = ?
`

func (q *Queries) ClearAssetEdgesForDeployment(ctx context.Context, deploymentID string) error {
	_, err := q.db.ExecContext(ctx, clearAssetEdgesForDeployment, deploymentID)
	return err
}

const clearAssetsForDeployment = `-- name: ClearAssetsForDeployment :exec
DELETE FROM assets WHERE deployment_id = ?
`

func (q *Queries) ClearAssetsForDeployment(ctx context.Context, deploymentID string) error {
	_, err := q.db.ExecContext(ctx, clearAssetsForDeployment, deploymentID)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = ?
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID string) error {
	_, err := q.db.ExecContext(ctx, clearRolePermissions, roleID)
	return err
}

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (id, principal_id, workspace_id, name, token_hash, permissions_json, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAPITokenParams struct {
	ID              string         `json:"id"`
	PrincipalID     string         `json:"principal_id"`
	WorkspaceID     sql.NullString `json:"workspace_id"`
	Name            string         `json:"name"`
	TokenHash       string         `json:"token_hash"`
	PermissionsJson string         `json:"permissions_json"`
	ExpiresAt       sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, createAPIToken,
		arg.ID,
		arg.PrincipalID,
		arg.WorkspaceID,
		arg.Name,
		arg.TokenHash,
		arg.PermissionsJson,
		arg.ExpiresAt,
	)
	return err
}

const createAgentConversation = `-- name: CreateAgentConversation :one
INSERT INTO agent_conversations (id, workspace_id, principal_id, title, status, metadata_json, transcript_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type CreateAgentConversationParams struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
	Title          string `json:"title"`
	Status         string `json:"status"`
	MetadataJson   string `json:"metadata_json"`
	TranscriptJson string `json:"transcript_json"`
}

func (q *Queries) CreateAgentConversation(ctx context.Context, arg CreateAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, createAgentConversation,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Title,
		arg.Status,
		arg.MetadataJson,
		arg.TranscriptJson,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (id, conversation_id, status, model, metadata_json)
SELECT
  ?1,
  c.id,
  ?2,
  ?3,
  ?4
FROM agent_conversations c
WHERE c.id = ?5
  AND c.principal_id = ?6
RETURNING id, conversation_id, status, model, stop_reason, input_tokens, output_tokens, total_tokens, error, started_at, finished_at, metadata_json
`

type CreateAgentRunParams struct {
	ID             string `json:"id"`
	Status         string `json:"status"`
	Model          string `json:"model"`
	MetadataJson   string `json:"metadata_json"`
	ConversationID string `json:"conversation_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, createAgentRun,
		arg.ID,
		arg.Status,
		arg.Model,
		arg.MetadataJson,
		arg.ConversationID,
		arg.PrincipalID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.Model,
		&i.StopReason,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MetadataJson,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO deployments (id, workspace_id, environment, status, created_by)
VALUES (?, ?, ?, ?, ?)
`

type CreateDeploymentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	Status      string `json:"status"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment,
		arg.ID,
		arg.WorkspaceID,
		arg.Environment,
		arg.Status,
		arg.CreatedBy,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, principal_id, token_hash, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
	TokenHash   string `json:"token_hash"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.PrincipalID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups
WHERE workspace_id = ? AND id = ?
`

type DeleteGroupParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, arg.WorkspaceID, arg.ID)
	return err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM group_members
WHERE workspace_id = ? AND group_id = ? AND principal_id = ?
`

type DeleteGroupMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	GroupID     string `json:"group_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMember, arg.WorkspaceID, arg.GroupID, arg.PrincipalID)
	return err
}

const deletePrincipalRoleBindings = `-- name: DeletePrincipalRoleBindings :exec
DELETE FROM role_bindings
WHERE workspace_id = ? AND principal_id = ?
`

type DeletePrincipalRoleBindingsParams struct {
	WorkspaceID string         `json:"workspace_id"`
	PrincipalID sql.NullString `json:"principal_id"`
}

func (q *Queries) DeletePrincipalRoleBindings(ctx context.Context, arg DeletePrincipalRoleBindingsParams) error {
	_, err := q.db.ExecContext(ctx, deletePrincipalRoleBindings, arg.WorkspaceID, arg.PrincipalID)
	return err
}

const deleteRoleBindingByID = `-- name: DeleteRoleBindingByID :exec
DELETE FROM role_bindings
WHERE workspace_id = ? AND id = ?
`

type DeleteRoleBindingByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) DeleteRoleBindingByID(ctx context.Context, arg DeleteRoleBindingByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteRoleBindingByID, arg.WorkspaceID, arg.ID)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const finishAgentRun = `-- name: FinishAgentRun :one
UPDATE agent_runs
SET status = ?1,
    stop_reason = ?2,
    input_tokens = ?3,
    output_tokens = ?4,
    total_tokens = ?5,
    error = ?6,
    finished_at = CURRENT_TIMESTAMP,
    metadata_json = ?7
WHERE agent_runs.id = ?8
  AND conversation_id IN (
    SELECT agent_conversations.id
    FROM agent_conversations
    WHERE agent_conversations.id = ?9
      AND principal_id = ?10
  )
RETURNING id, conversation_id, status, model, stop_reason, input_tokens, output_tokens, total_tokens, error, started_at, finished_at, metadata_json
`

type FinishAgentRunParams struct {
	Status         string `json:"status"`
	StopReason     string `json:"stop_reason"`
	InputTokens    int64  `json:"input_tokens"`
	OutputTokens   int64  `json:"output_tokens"`
	TotalTokens    int64  `json:"total_tokens"`
	Error          string `json:"error"`
	MetadataJson   string `json:"metadata_json"`
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) FinishAgentRun(ctx context.Context, arg FinishAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, finishAgentRun,
		arg.Status,
		arg.StopReason,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.Error,
		arg.MetadataJson,
		arg.ID,
		arg.ConversationID,
		arg.PrincipalID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.Model,
		&i.StopReason,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MetadataJson,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, principal_id, workspace_id, name, token_hash, permissions_json, expires_at, created_at, last_used_at, revoked_at FROM api_tokens
WHERE token_hash = ?
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.WorkspaceID,
		&i.Name,
		&i.TokenHash,
		&i.PermissionsJson,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveDeployment = `-- name: GetActiveDeployment :one
SELECT d.id, d.workspace_id, d.environment, d.status, d.digest, d.manifest_json, d.created_by, d.created_at, d.activated_at, d.error
FROM deployments d
JOIN workspace_active_deployments active ON active.deployment_id = d.id
WHERE active.workspace_id = ? AND active.environment = ?
`

type GetActiveDeploymentParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

func (q *Queries) GetActiveDeployment(ctx context.Context, arg GetActiveDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getActiveDeployment, arg.WorkspaceID, arg.Environment)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Environment,
		&i.Status,
		&i.Digest,
		&i.ManifestJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Error,
	)
	return i, err
}

const getAgentConversation = `-- name: GetAgentConversation :one
SELECT id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at FROM agent_conversations
WHERE id = ?1
  AND principal_id = ?2
`

type GetAgentConversationParams struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) GetAgentConversation(ctx context.Context, arg GetAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, getAgentConversation, arg.ID, arg.PrincipalID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getArtifactByDeployment = `-- name: GetArtifactByDeployment :one
SELECT id, deployment_id, workspace_id, environment, digest, format, path, manifest_json, size_bytes, created_at FROM deployment_artifacts WHERE deployment_id = ?
`

func (q *Queries) GetArtifactByDeployment(ctx context.Context, deploymentID string) (DeploymentArtifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByDeployment, deploymentID)
	var i DeploymentArtifact
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.WorkspaceID,
		&i.Environment,
		&i.Digest,
		&i.Format,
		&i.Path,
		&i.ManifestJson,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, workspace_id, environment, status, digest, manifest_json, created_by, created_at, activated_at, error FROM deployments WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Environment,
		&i.Status,
		&i.Digest,
		&i.ManifestJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Error,
	)
	return i, err
}

const getExternalIdentity = `-- name: GetExternalIdentity :one
SELECT id, principal_id, provider, tenant_id, subject, email, created_at, updated_at FROM external_identities
WHERE provider = ? AND tenant_id = ? AND subject = ?
`

type GetExternalIdentityParams struct {
	Provider string `json:"provider"`
	TenantID string `json:"tenant_id"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetExternalIdentity(ctx context.Context, arg GetExternalIdentityParams) (ExternalIdentity, error) {
	row := q.db.QueryRowContext(ctx, getExternalIdentity, arg.Provider, arg.TenantID, arg.Subject)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Provider,
		&i.TenantID,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, workspace_id, provider, external_id, name, created_at FROM groups
WHERE workspace_id = ? AND id = ?
`

type GetGroupParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, arg.WorkspaceID, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByProviderExternalID = `-- name: GetGroupByProviderExternalID :one
SELECT id, workspace_id, provider, external_id, name, created_at FROM groups
WHERE workspace_id = ? AND provider = ? AND external_id = ?
`

type GetGroupByProviderExternalIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	Provider    string `json:"provider"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) GetGroupByProviderExternalID(ctx context.Context, arg GetGroupByProviderExternalIDParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByProviderExternalID, arg.WorkspaceID, arg.Provider, arg.ExternalID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, email, display_name, created_at, updated_at FROM principals WHERE id = ?
`

func (q *Queries) GetPrincipal(ctx context.Context, id string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipal, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrincipalByEmail = `-- name: GetPrincipalByEmail :one
SELECT id, email, display_name, created_at, updated_at FROM principals WHERE lower(email) = lower(?) AND email <> '' LIMIT 1
`

func (q *Queries) GetPrincipalByEmail(ctx context.Context, lower string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByEmail, lower)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleBindingByID = `-- name: GetRoleBindingByID :one
SELECT
  rb.id,
  rb.workspace_id,
  CASE WHEN NULLIF(rb.principal_id, '') IS NOT NULL THEN 'principal' ELSE 'group' END AS subject_type,
  COALESCE(NULLIF(rb.principal_id, ''), rb.group_id, '') AS subject_id,
  rb.principal_id,
  rb.group_id,
  p.email,
  p.display_name,
  g.name AS group_name,
  r.name AS role_name,
  rb.created_at
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
LEFT JOIN principals p ON p.id = NULLIF(rb.principal_id, '')
LEFT JOIN groups g ON g.id = rb.group_id
WHERE rb.workspace_id = ? AND rb.id = ?
`

type GetRoleBindingByIDParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

type GetRoleBindingByIDRow struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	SubjectType string         `json:"subject_type"`
	SubjectID   string         `json:"subject_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
	Email       sql.NullString `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	GroupName   sql.NullString `json:"group_name"`
	RoleName    string         `json:"role_name"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) GetRoleBindingByID(ctx context.Context, arg GetRoleBindingByIDParams) (GetRoleBindingByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRoleBindingByID, arg.WorkspaceID, arg.ID)
	var i GetRoleBindingByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.SubjectType,
		&i.SubjectID,
		&i.PrincipalID,
		&i.GroupID,
		&i.Email,
		&i.DisplayName,
		&i.GroupName,
		&i.RoleName,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, permissions_json FROM roles WHERE name = ?
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.PermissionsJson)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, principal_id, token_hash, expires_at, created_at, last_seen_at, revoked_at FROM sessions
WHERE token_hash = ? AND expires_at > CURRENT_TIMESTAMP AND revoked_at IS NULL
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, title, description, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceWithActiveMetadata = `-- name: GetWorkspaceWithActiveMetadata :one
SELECT
  w.id,
  CASE WHEN a.title IS NOT NULL AND a.title <> '' THEN a.title ELSE w.title END AS title,
  CASE WHEN a.description IS NOT NULL THEN a.description ELSE w.description END AS description,
  COALESCE(active.deployment_id, '') AS active_deployment_id,
  w.created_at,
  w.updated_at
FROM workspaces w
LEFT JOIN workspace_active_deployments active
  ON active.workspace_id = w.id AND active.environment = ?
LEFT JOIN assets a
  ON a.deployment_id = active.deployment_id
 AND a.asset_type = 'catalog'
 AND a.logical_asset_id = 'catalog:' || w.id
WHERE w.id = ?
`

type GetWorkspaceWithActiveMetadataParams struct {
	Environment string `json:"environment"`
	ID          string `json:"id"`
}

type GetWorkspaceWithActiveMetadataRow struct {
	ID                 string      `json:"id"`
	Title              interface{} `json:"title"`
	Description        interface{} `json:"description"`
	ActiveDeploymentID string      `json:"active_deployment_id"`
	CreatedAt          string      `json:"created_at"`
	UpdatedAt          string      `json:"updated_at"`
}

func (q *Queries) GetWorkspaceWithActiveMetadata(ctx context.Context, arg GetWorkspaceWithActiveMetadataParams) (GetWorkspaceWithActiveMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceWithActiveMetadata, arg.Environment, arg.ID)
	var i GetWorkspaceWithActiveMetadataRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :exec
INSERT INTO assets (snapshot_id, logical_asset_id, workspace_id, deployment_id, asset_type, asset_key, parent_logical_asset_id, title, description, source_file, payload_schema, payload_json, content_hash)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAssetParams struct {
	SnapshotID           string `json:"snapshot_id"`
	LogicalAssetID       string `json:"logical_asset_id"`
	WorkspaceID          string `json:"workspace_id"`
	DeploymentID         string `json:"deployment_id"`
	AssetType            string `json:"asset_type"`
	AssetKey             string `json:"asset_key"`
	ParentLogicalAssetID string `json:"parent_logical_asset_id"`
	Title                string `json:"title"`
	Description          string `json:"description"`
	SourceFile           string `json:"source_file"`
	PayloadSchema        string `json:"payload_schema"`
	PayloadJson          string `json:"payload_json"`
	ContentHash          string `json:"content_hash"`
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, insertAsset,
		arg.SnapshotID,
		arg.LogicalAssetID,
		arg.WorkspaceID,
		arg.DeploymentID,
		arg.AssetType,
		arg.AssetKey,
		arg.ParentLogicalAssetID,
		arg.Title,
		arg.Description,
		arg.SourceFile,
		arg.PayloadSchema,
		arg.PayloadJson,
		arg.ContentHash,
	)
	return err
}

const insertAssetEdge = `-- name: InsertAssetEdge :exec
INSERT INTO asset_edges (id, workspace_id, deployment_id, from_logical_asset_id, to_logical_asset_id, edge_type)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAssetEdgeParams struct {
	ID                 string `json:"id"`
	WorkspaceID        string `json:"workspace_id"`
	DeploymentID       string `json:"deployment_id"`
	FromLogicalAssetID string `json:"from_logical_asset_id"`
	ToLogicalAssetID   string `json:"to_logical_asset_id"`
	EdgeType           string `json:"edge_type"`
}

func (q *Queries) InsertAssetEdge(ctx context.Context, arg InsertAssetEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetEdge,
		arg.ID,
		arg.WorkspaceID,
		arg.DeploymentID,
		arg.FromLogicalAssetID,
		arg.ToLogicalAssetID,
		arg.EdgeType,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, workspace_id, principal_id, action, target_type, target_id, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	ID           string         `json:"id"`
	WorkspaceID  sql.NullString `json:"workspace_id"`
	PrincipalID  sql.NullString `json:"principal_id"`
	Action       string         `json:"action"`
	TargetType   string         `json:"target_type"`
	TargetID     string         `json:"target_id"`
	MetadataJson string         `json:"metadata_json"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.MetadataJson,
	)
	return err
}

const insertDeploymentArtifact = `-- name: InsertDeploymentArtifact :exec
INSERT INTO deployment_artifacts (id, deployment_id, workspace_id, environment, digest, format, path, manifest_json, size_bytes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(deployment_id) DO UPDATE SET
  environment = excluded.environment,
  digest = excluded.digest,
  format = excluded.format,
  path = excluded.path,
  manifest_json = excluded.manifest_json,
  size_bytes = excluded.size_bytes
`

type InsertDeploymentArtifactParams struct {
	ID           string `json:"id"`
	DeploymentID string `json:"deployment_id"`
	WorkspaceID  string `json:"workspace_id"`
	Environment  string `json:"environment"`
	Digest       string `json:"digest"`
	Format       string `json:"format"`
	Path         string `json:"path"`
	ManifestJson string `json:"manifest_json"`
	SizeBytes    int64  `json:"size_bytes"`
}

func (q *Queries) InsertDeploymentArtifact(ctx context.Context, arg InsertDeploymentArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentArtifact,
		arg.ID,
		arg.DeploymentID,
		arg.WorkspaceID,
		arg.Environment,
		arg.Digest,
		arg.Format,
		arg.Path,
		arg.ManifestJson,
		arg.SizeBytes,
	)
	return err
}

const insertGroupMember = `-- name: InsertGroupMember :exec
INSERT OR IGNORE INTO group_members (workspace_id, group_id, principal_id)
VALUES (?, ?, ?)
`

type InsertGroupMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	GroupID     string `json:"group_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) InsertGroupMember(ctx context.Context, arg InsertGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, insertGroupMember, arg.WorkspaceID, arg.GroupID, arg.PrincipalID)
	return err
}

const insertPlatformRoleBinding = `-- name: InsertPlatformRoleBinding :exec
INSERT OR IGNORE INTO platform_role_bindings (id, role_id, principal_id)
VALUES (?, ?, ?)
`

type InsertPlatformRoleBindingParams struct {
	ID          string `json:"id"`
	RoleID      string `json:"role_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) InsertPlatformRoleBinding(ctx context.Context, arg InsertPlatformRoleBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertPlatformRoleBinding, arg.ID, arg.RoleID, arg.PrincipalID)
	return err
}

const insertRoleBinding = `-- name: InsertRoleBinding :exec
INSERT OR IGNORE INTO role_bindings (id, workspace_id, role_id, principal_id, group_id)
VALUES (?, ?, ?, ?, ?)
`

type InsertRoleBindingParams struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	RoleID      string         `json:"role_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
}

func (q *Queries) InsertRoleBinding(ctx context.Context, arg InsertRoleBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertRoleBinding,
		arg.ID,
		arg.WorkspaceID,
		arg.RoleID,
		arg.PrincipalID,
		arg.GroupID,
	)
	return err
}

const insertRolePermission = `-- name: InsertRolePermission :exec
INSERT OR IGNORE INTO role_permissions (role_id, permission_name)
VALUES (?, ?)
`

type InsertRolePermissionParams struct {
	RoleID         string `json:"role_id"`
	PermissionName string `json:"permission_name"`
}

func (q *Queries) InsertRolePermission(ctx context.Context, arg InsertRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, insertRolePermission, arg.RoleID, arg.PermissionName)
	return err
}

const listAPITokensByPrincipal = `-- name: ListAPITokensByPrincipal :many
SELECT id, principal_id, workspace_id, name, token_hash, permissions_json, expires_at, created_at, last_used_at, revoked_at FROM api_tokens
WHERE principal_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByPrincipal(ctx context.Context, principalID string) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensByPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.WorkspaceID,
			&i.Name,
			&i.TokenHash,
			&i.PermissionsJson,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentConversations = `-- name: ListAgentConversations :many
SELECT id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at FROM agent_conversations
WHERE principal_id = ?1
  AND status = 'active'
ORDER BY updated_at DESC, created_at DESC
`

func (q *Queries) ListAgentConversations(ctx context.Context, principalID string) ([]AgentConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConversations, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversation{}
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Title,
			&i.Status,
			&i.MetadataJson,
			&i.TranscriptJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentEvents = `-- name: ListAgentEvents :many
SELECT e.id, e.run_id, e.seq, e.event_type, e.severity, e.payload_json, e.created_at
FROM agent_events e
JOIN agent_runs r ON r.id = e.run_id
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE r.id = ?1
  AND c.principal_id = ?2
ORDER BY e.seq
`

type ListAgentEventsParams struct {
	RunID       string `json:"run_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) ListAgentEvents(ctx context.Context, arg ListAgentEventsParams) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentEvents, arg.RunID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.EventType,
			&i.Severity,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessages = `-- name: ListAgentMessages :many
SELECT m.id, m.conversation_id, m.run_id, m.seq, m.role, m.content_text, m.content_json, m.tool_call_id, m.tool_name, m.is_error, m.created_at
FROM agent_messages m
JOIN agent_conversations c ON c.id = m.conversation_id
WHERE c.id = ?1
  AND c.principal_id = ?2
ORDER BY m.seq
`

type ListAgentMessagesParams struct {
	ConversationID string `json:"conversation_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) ListAgentMessages(ctx context.Context, arg ListAgentMessagesParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessages, arg.ConversationID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Seq,
			&i.Role,
			&i.ContentText,
			&i.ContentJson,
			&i.ToolCallID,
			&i.ToolName,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRuns = `-- name: ListAgentRuns :many
SELECT r.id, r.conversation_id, r.status, r.model, r.stop_reason, r.input_tokens, r.output_tokens, r.total_tokens, r.error, r.started_at, r.finished_at, r.metadata_json
FROM agent_runs r
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE c.id = ?1
  AND c.principal_id = ?2
ORDER BY r.started_at DESC
`

type ListAgentRunsParams struct {
	ConversationID string `json:"conversation_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) ListAgentRuns(ctx context.Context, arg ListAgentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRuns, arg.ConversationID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Status,
			&i.Model,
			&i.StopReason,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEdgesByDeployment = `-- name: ListAssetEdgesByDeployment :many
SELECT id, workspace_id, deployment_id, from_logical_asset_id, to_logical_asset_id, edge_type, created_at FROM asset_edges WHERE deployment_id = ? ORDER BY edge_type, from_logical_asset_id, to_logical_asset_id
`

func (q *Queries) ListAssetEdgesByDeployment(ctx context.Context, deploymentID string) ([]AssetEdge, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEdgesByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetEdge{}
	for rows.Next() {
		var i AssetEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DeploymentID,
			&i.FromLogicalAssetID,
			&i.ToLogicalAssetID,
			&i.EdgeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetVersions = `-- name: ListAssetVersions :many
SELECT
  d.id AS deployment_id,
  d.workspace_id,
  d.environment,
  d.status,
  d.digest,
  d.created_by,
  d.created_at,
  d.activated_at,
  a.snapshot_id,
  a.logical_asset_id,
  a.content_hash
FROM deployments d
JOIN assets a ON a.deployment_id = d.id
WHERE d.workspace_id = ?
  AND d.environment = ?
  AND a.logical_asset_id = ?
  AND d.status IN ('active', 'inactive', 'validated')
ORDER BY
  COALESCE(d.activated_at, d.created_at) DESC,
  d.created_at DESC,
  d.id DESC
`

type ListAssetVersionsParams struct {
	WorkspaceID    string `json:"workspace_id"`
	Environment    string `json:"environment"`
	LogicalAssetID string `json:"logical_asset_id"`
}

type ListAssetVersionsRow struct {
	DeploymentID   string         `json:"deployment_id"`
	WorkspaceID    string         `json:"workspace_id"`
	Environment    string         `json:"environment"`
	Status         string         `json:"status"`
	Digest         string         `json:"digest"`
	CreatedBy      string         `json:"created_by"`
	CreatedAt      string         `json:"created_at"`
	ActivatedAt    sql.NullString `json:"activated_at"`
	SnapshotID     string         `json:"snapshot_id"`
	LogicalAssetID string         `json:"logical_asset_id"`
	ContentHash    string         `json:"content_hash"`
}

func (q *Queries) ListAssetVersions(ctx context.Context, arg ListAssetVersionsParams) ([]ListAssetVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetVersions, arg.WorkspaceID, arg.Environment, arg.LogicalAssetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssetVersionsRow{}
	for rows.Next() {
		var i ListAssetVersionsRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.WorkspaceID,
			&i.Environment,
			&i.Status,
			&i.Digest,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByDeployment = `-- name: ListAssetsByDeployment :many
SELECT snapshot_id, logical_asset_id, workspace_id, deployment_id, asset_type, asset_key, parent_logical_asset_id, title, description, source_file, payload_schema, payload_json, content_hash, created_at FROM assets WHERE deployment_id = ? ORDER BY asset_type, asset_key
`

func (q *Queries) ListAssetsByDeployment(ctx context.Context, deploymentID string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.SnapshotID,
			&i.LogicalAssetID,
			&i.WorkspaceID,
			&i.DeploymentID,
			&i.AssetType,
			&i.AssetKey,
			&i.ParentLogicalAssetID,
			&i.Title,
			&i.Description,
			&i.SourceFile,
			&i.PayloadSchema,
			&i.PayloadJson,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, workspace_id, principal_id, "action", target_type, target_id, metadata_json, created_at FROM audit_events
WHERE (? = '' OR workspace_id = ?)
  AND (? = '' OR principal_id = ?)
  AND (? = '' OR action = ?)
  AND (? = '' OR target_type = ?)
  AND (? = '' OR target_id = ?)
  AND (? = '' OR created_at >= ?)
  AND (? = '' OR created_at <= ?)
  AND (? = '' OR created_at < ? OR (created_at = ? AND id < ?))
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListAuditEventsParams struct {
	Column1     interface{}    `json:"column_1"`
	WorkspaceID sql.NullString `json:"workspace_id"`
	Column3     interface{}    `json:"column_3"`
	PrincipalID sql.NullString `json:"principal_id"`
	Column5     interface{}    `json:"column_5"`
	Action      string         `json:"action"`
	Column7     interface{}    `json:"column_7"`
	TargetType  string         `json:"target_type"`
	Column9     interface{}    `json:"column_9"`
	TargetID    string         `json:"target_id"`
	Column11    interface{}    `json:"column_11"`
	CreatedAt   string         `json:"created_at"`
	Column13    interface{}    `json:"column_13"`
	CreatedAt_2 string         `json:"created_at_2"`
	Column15    interface{}    `json:"column_15"`
	CreatedAt_3 string         `json:"created_at_3"`
	CreatedAt_4 string         `json:"created_at_4"`
	ID          string         `json:"id"`
	Limit       int64          `json:"limit"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEvents,
		arg.Column1,
		arg.WorkspaceID,
		arg.Column3,
		arg.PrincipalID,
		arg.Column5,
		arg.Action,
		arg.Column7,
		arg.TargetType,
		arg.Column9,
		arg.TargetID,
		arg.Column11,
		arg.CreatedAt,
		arg.Column13,
		arg.CreatedAt_2,
		arg.Column15,
		arg.CreatedAt_3,
		arg.CreatedAt_4,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, workspace_id, environment, status, digest, manifest_json, created_by, created_at, activated_at, error FROM deployments
WHERE workspace_id = ? AND environment = ?
ORDER BY created_at DESC
`

type ListDeploymentsParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
}

func (q *Queries) ListDeployments(ctx context.Context, arg ListDeploymentsParams) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments, arg.WorkspaceID, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Environment,
			&i.Status,
			&i.Digest,
			&i.ManifestJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT
  gm.group_id,
  gm.workspace_id,
  gm.principal_id,
  p.email,
  p.display_name,
  gm.created_at
FROM group_members gm
JOIN principals p ON p.id = gm.principal_id
WHERE gm.workspace_id = ? AND gm.group_id = ?
ORDER BY p.email, p.display_name, gm.principal_id
`

type ListGroupMembersParams struct {
	WorkspaceID string `json:"workspace_id"`
	GroupID     string `json:"group_id"`
}

type ListGroupMembersRow struct {
	GroupID     string `json:"group_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, arg.WorkspaceID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Email,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByWorkspace = `-- name: ListGroupsByWorkspace :many
SELECT id, workspace_id, provider, external_id, name, created_at FROM groups
WHERE workspace_id = ?
ORDER BY name, id
`

func (q *Queries) ListGroupsByWorkspace(ctx context.Context, workspaceID string) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Provider,
			&i.ExternalID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT name, created_at FROM permissions ORDER BY name
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalRolePermissions = `-- name: ListPrincipalRolePermissions :many
SELECT DISTINCT permission_name
FROM (
  SELECT rp.permission_name
  FROM role_bindings rb
  JOIN role_permissions rp ON rp.role_id = rb.role_id
  LEFT JOIN group_members gm
    ON gm.workspace_id = rb.workspace_id
   AND gm.group_id = rb.group_id
  WHERE rb.workspace_id = ?
    AND (
      rb.principal_id = ?
      OR gm.principal_id = ?
    )
  UNION
  SELECT rp.permission_name
  FROM platform_role_bindings prb
  JOIN role_permissions rp ON rp.role_id = prb.role_id
  WHERE prb.principal_id = ?
)
ORDER BY permission_name
`

type ListPrincipalRolePermissionsParams struct {
	WorkspaceID   string         `json:"workspace_id"`
	PrincipalID   sql.NullString `json:"principal_id"`
	PrincipalID_2 string         `json:"principal_id_2"`
	PrincipalID_3 string         `json:"principal_id_3"`
}

func (q *Queries) ListPrincipalRolePermissions(ctx context.Context, arg ListPrincipalRolePermissionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipalRolePermissions,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.PrincipalID_2,
		arg.PrincipalID_3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_name string
		if err := rows.Scan(&permission_name); err != nil {
			return nil, err
		}
		items = append(items, permission_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsByWorkspace = `-- name: ListRoleBindingsByWorkspace :many
SELECT
  rb.id,
  rb.workspace_id,
  CASE WHEN NULLIF(rb.principal_id, '') IS NOT NULL THEN 'principal' ELSE 'group' END AS subject_type,
  COALESCE(NULLIF(rb.principal_id, ''), rb.group_id, '') AS subject_id,
  rb.principal_id,
  rb.group_id,
  p.email,
  p.display_name,
  g.name AS group_name,
  r.name AS role_name,
  rb.created_at
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
LEFT JOIN principals p ON p.id = NULLIF(rb.principal_id, '')
LEFT JOIN groups g ON g.id = rb.group_id
WHERE rb.workspace_id = ?
ORDER BY subject_type, p.email, g.name, r.name
`

type ListRoleBindingsByWorkspaceRow struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	SubjectType string         `json:"subject_type"`
	SubjectID   string         `json:"subject_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
	Email       sql.NullString `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	GroupName   sql.NullString `json:"group_name"`
	RoleName    string         `json:"role_name"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) ListRoleBindingsByWorkspace(ctx context.Context, workspaceID string) ([]ListRoleBindingsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoleBindingsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleBindingsByWorkspaceRow{}
	for rows.Next() {
		var i ListRoleBindingsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.SubjectType,
			&i.SubjectID,
			&i.PrincipalID,
			&i.GroupID,
			&i.Email,
			&i.DisplayName,
			&i.GroupName,
			&i.RoleName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, permissions_json FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.PermissionsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByPrincipal = `-- name: ListSessionsByPrincipal :many
SELECT id, principal_id, token_hash, expires_at, created_at, last_seen_at, revoked_at FROM sessions
WHERE principal_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByPrincipal(ctx context.Context, principalID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, title, description, created_at, updated_at FROM workspaces ORDER BY created_at
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithActiveMetadata = `-- name: ListWorkspacesWithActiveMetadata :many
SELECT
  w.id,
  CASE WHEN a.title IS NOT NULL AND a.title <> '' THEN a.title ELSE w.title END AS title,
  CASE WHEN a.description IS NOT NULL THEN a.description ELSE w.description END AS description,
  COALESCE(active.deployment_id, '') AS active_deployment_id,
  w.created_at,
  w.updated_at
FROM workspaces w
LEFT JOIN workspace_active_deployments active
  ON active.workspace_id = w.id AND active.environment = ?
LEFT JOIN assets a
  ON a.deployment_id = active.deployment_id
 AND a.asset_type = 'catalog'
 AND a.logical_asset_id = 'catalog:' || w.id
ORDER BY w.created_at
`

type ListWorkspacesWithActiveMetadataRow struct {
	ID                 string      `json:"id"`
	Title              interface{} `json:"title"`
	Description        interface{} `json:"description"`
	ActiveDeploymentID string      `json:"active_deployment_id"`
	CreatedAt          string      `json:"created_at"`
	UpdatedAt          string      `json:"updated_at"`
}

func (q *Queries) ListWorkspacesWithActiveMetadata(ctx context.Context, environment string) ([]ListWorkspacesWithActiveMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesWithActiveMetadata, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesWithActiveMetadataRow{}
	for rows.Next() {
		var i ListWorkspacesWithActiveMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ActiveDeploymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentActive = `-- name: MarkDeploymentActive :exec
UPDATE deployments
SET status = 'active', activated_at = CURRENT_TIMESTAMP, error = ''
WHERE id = ?
`

func (q *Queries) MarkDeploymentActive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markDeploymentActive, id)
	return err
}

const markOtherDeploymentsInactive = `-- name: MarkOtherDeploymentsInactive :exec
UPDATE deployments
SET status = 'inactive'
WHERE workspace_id = ? AND environment = ? AND id <> ? AND status = 'active'
`

type MarkOtherDeploymentsInactiveParams struct {
	WorkspaceID string `json:"workspace_id"`
	Environment string `json:"environment"`
	ID          string `json:"id"`
}

func (q *Queries) MarkOtherDeploymentsInactive(ctx context.Context, arg MarkOtherDeploymentsInactiveParams) error {
	_, err := q.db.ExecContext(ctx, markOtherDeploymentsInactive, arg.WorkspaceID, arg.Environment, arg.ID)
	return err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE id = ?
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeAPIToken, id)
	return err
}

const revokeAPITokenForPrincipal = `-- name: RevokeAPITokenForPrincipal :one
UPDATE api_tokens
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE principal_id = ? AND id = ?
RETURNING id, principal_id, workspace_id, name, token_hash, permissions_json, expires_at, created_at, last_used_at, revoked_at
`

type RevokeAPITokenForPrincipalParams struct {
	PrincipalID string `json:"principal_id"`
	ID          string `json:"id"`
}

func (q *Queries) RevokeAPITokenForPrincipal(ctx context.Context, arg RevokeAPITokenForPrincipalParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, revokeAPITokenForPrincipal, arg.PrincipalID, arg.ID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.WorkspaceID,
		&i.Name,
		&i.TokenHash,
		&i.PermissionsJson,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE id = ?
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const revokeSessionForPrincipal = `-- name: RevokeSessionForPrincipal :one
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, CURRENT_TIMESTAMP)
WHERE principal_id = ? AND id = ?
RETURNING id, principal_id, token_hash, expires_at, created_at, last_seen_at, revoked_at
`

type RevokeSessionForPrincipalParams struct {
	PrincipalID string `json:"principal_id"`
	ID          string `json:"id"`
}

func (q *Queries) RevokeSessionForPrincipal(ctx context.Context, arg RevokeSessionForPrincipalParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, revokeSessionForPrincipal, arg.PrincipalID, arg.ID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const setActiveDeployment = `-- name: SetActiveDeployment :exec
INSERT INTO workspace_active_deployments (workspace_id, environment, deployment_id, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(workspace_id, environment) DO UPDATE SET
  deployment_id = excluded.deployment_id,
  updated_at = CURRENT_TIMESTAMP
`

type SetActiveDeploymentParams struct {
	WorkspaceID  string `json:"workspace_id"`
	Environment  string `json:"environment"`
	DeploymentID string `json:"deployment_id"`
}

func (q *Queries) SetActiveDeployment(ctx context.Context, arg SetActiveDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, setActiveDeployment, arg.WorkspaceID, arg.Environment, arg.DeploymentID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}

const updateAgentConversationTranscript = `-- name: UpdateAgentConversationTranscript :one
UPDATE agent_conversations
SET transcript_json = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND principal_id = ?3
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type UpdateAgentConversationTranscriptParams struct {
	TranscriptJson string `json:"transcript_json"`
	ID             string `json:"id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) UpdateAgentConversationTranscript(ctx context.Context, arg UpdateAgentConversationTranscriptParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, updateAgentConversationTranscript, arg.TranscriptJson, arg.ID, arg.PrincipalID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateDefaultAgentConversationTitle = `-- name: UpdateDefaultAgentConversationTitle :one
UPDATE agent_conversations
SET title = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND principal_id = ?3
  AND status = 'active'
  AND title = 'New conversation'
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type UpdateDefaultAgentConversationTitleParams struct {
	Title       string `json:"title"`
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) UpdateDefaultAgentConversationTitle(ctx context.Context, arg UpdateDefaultAgentConversationTitleParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, updateDefaultAgentConversationTitle, arg.Title, arg.ID, arg.PrincipalID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = ?, error = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status string `json:"status"`
	Error  string `json:"error"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const updateDeploymentValidated = `-- name: UpdateDeploymentValidated :exec
UPDATE deployments
SET status = ?, digest = ?, manifest_json = ?, error = ''
WHERE id = ?
`

type UpdateDeploymentValidatedParams struct {
	Status       string `json:"status"`
	Digest       string `json:"digest"`
	ManifestJson string `json:"manifest_json"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateDeploymentValidated(ctx context.Context, arg UpdateDeploymentValidatedParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentValidated,
		arg.Status,
		arg.Digest,
		arg.ManifestJson,
		arg.ID,
	)
	return err
}

const updateRoleBindingByID = `-- name: UpdateRoleBindingByID :exec
UPDATE role_bindings
SET role_id = ?, principal_id = ?, group_id = ?
WHERE workspace_id = ? AND id = ?
`

type UpdateRoleBindingByIDParams struct {
	RoleID      string         `json:"role_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
	WorkspaceID string         `json:"workspace_id"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateRoleBindingByID(ctx context.Context, arg UpdateRoleBindingByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateRoleBindingByID,
		arg.RoleID,
		arg.PrincipalID,
		arg.GroupID,
		arg.WorkspaceID,
		arg.ID,
	)
	return err
}

const upsertExternalIdentity = `-- name: UpsertExternalIdentity :exec
INSERT INTO external_identities (id, principal_id, provider, tenant_id, subject, email, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(provider, tenant_id, subject) DO UPDATE SET
  principal_id = excluded.principal_id,
  email = excluded.email,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertExternalIdentityParams struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
	Provider    string `json:"provider"`
	TenantID    string `json:"tenant_id"`
	Subject     string `json:"subject"`
	Email       string `json:"email"`
}

func (q *Queries) UpsertExternalIdentity(ctx context.Context, arg UpsertExternalIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertExternalIdentity,
		arg.ID,
		arg.PrincipalID,
		arg.Provider,
		arg.TenantID,
		arg.Subject,
		arg.Email,
	)
	return err
}

const upsertGroup = `-- name: UpsertGroup :exec
INSERT INTO groups (id, workspace_id, provider, external_id, name)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(workspace_id, provider, external_id) DO UPDATE SET
  name = excluded.name
`

type UpsertGroupParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Provider    string `json:"provider"`
	ExternalID  string `json:"external_id"`
	Name        string `json:"name"`
}

func (q *Queries) UpsertGroup(ctx context.Context, arg UpsertGroupParams) error {
	_, err := q.db.ExecContext(ctx, upsertGroup,
		arg.ID,
		arg.WorkspaceID,
		arg.Provider,
		arg.ExternalID,
		arg.Name,
	)
	return err
}

const upsertPermission = `-- name: UpsertPermission :exec
INSERT INTO permissions (name)
VALUES (?)
ON CONFLICT(name) DO NOTHING
`

func (q *Queries) UpsertPermission(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, upsertPermission, name)
	return err
}

const upsertPrincipal = `-- name: UpsertPrincipal :exec
INSERT INTO principals (id, email, display_name, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  email = excluded.email,
  display_name = excluded.display_name,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertPrincipalParams struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpsertPrincipal(ctx context.Context, arg UpsertPrincipalParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrincipal, arg.ID, arg.Email, arg.DisplayName)
	return err
}

const upsertRole = `-- name: UpsertRole :exec
INSERT INTO roles (id, name, permissions_json)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET permissions_json = excluded.permissions_json
`

type UpsertRoleParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	PermissionsJson string `json:"permissions_json"`
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) error {
	_, err := q.db.ExecContext(ctx, upsertRole, arg.ID, arg.Name, arg.PermissionsJson)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
INSERT INTO workspaces (id, title, description, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertWorkspaceParams struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspace, arg.ID, arg.Title, arg.Description)
	return err
}
