// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const appendAgentEvent = `-- name: AppendAgentEvent :one
INSERT INTO agent_events (id, run_id, seq, event_type, severity, payload_json)
SELECT
  ?1,
  r.id,
  ?2,
  ?3,
  ?4,
  ?5
FROM agent_runs r
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE r.id = ?6
  AND c.workspace_id = ?7
  AND c.principal_id = ?8
RETURNING id, run_id, seq, event_type, severity, payload_json, created_at
`

type AppendAgentEventParams struct {
	ID          string `json:"id"`
	Seq         int64  `json:"seq"`
	EventType   string `json:"event_type"`
	Severity    string `json:"severity"`
	PayloadJson string `json:"payload_json"`
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) AppendAgentEvent(ctx context.Context, arg AppendAgentEventParams) (AgentEvent, error) {
	row := q.db.QueryRowContext(ctx, appendAgentEvent,
		arg.ID,
		arg.Seq,
		arg.EventType,
		arg.Severity,
		arg.PayloadJson,
		arg.RunID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Seq,
		&i.EventType,
		&i.Severity,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const appendAgentMessage = `-- name: AppendAgentMessage :one
INSERT INTO agent_messages (id, conversation_id, run_id, seq, role, content_text, content_json, tool_call_id, tool_name, is_error)
SELECT
  ?1,
  c.id,
  NULLIF(?2, ''),
  COALESCE((SELECT MAX(seq) + 1 FROM agent_messages WHERE conversation_id = c.id), 1),
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
FROM agent_conversations c
WHERE c.id = ?9
  AND c.workspace_id = ?10
  AND c.principal_id = ?11
RETURNING id, conversation_id, run_id, seq, role, content_text, content_json, tool_call_id, tool_name, is_error, created_at
`

type AppendAgentMessageParams struct {
	ID             string      `json:"id"`
	RunID          interface{} `json:"run_id"`
	Role           string      `json:"role"`
	ContentText    string      `json:"content_text"`
	ContentJson    string      `json:"content_json"`
	ToolCallID     string      `json:"tool_call_id"`
	ToolName       string      `json:"tool_name"`
	IsError        bool        `json:"is_error"`
	ConversationID string      `json:"conversation_id"`
	WorkspaceID    string      `json:"workspace_id"`
	PrincipalID    string      `json:"principal_id"`
}

func (q *Queries) AppendAgentMessage(ctx context.Context, arg AppendAgentMessageParams) (AgentMessage, error) {
	row := q.db.QueryRowContext(ctx, appendAgentMessage,
		arg.ID,
		arg.RunID,
		arg.Role,
		arg.ContentText,
		arg.ContentJson,
		arg.ToolCallID,
		arg.ToolName,
		arg.IsError,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RunID,
		&i.Seq,
		&i.Role,
		&i.ContentText,
		&i.ContentJson,
		&i.ToolCallID,
		&i.ToolName,
		&i.IsError,
		&i.CreatedAt,
	)
	return i, err
}

const archiveAgentConversation = `-- name: ArchiveAgentConversation :one
UPDATE agent_conversations
SET status = 'archived',
    archived_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
  AND workspace_id = ?2
  AND principal_id = ?3
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type ArchiveAgentConversationParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) ArchiveAgentConversation(ctx context.Context, arg ArchiveAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, archiveAgentConversation, arg.ID, arg.WorkspaceID, arg.PrincipalID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const clearAssetsForDeployment = `-- name: ClearAssetsForDeployment :exec
DELETE FROM assets WHERE deployment_id = ?
`

func (q *Queries) ClearAssetsForDeployment(ctx context.Context, deploymentID string) error {
	_, err := q.db.ExecContext(ctx, clearAssetsForDeployment, deploymentID)
	return err
}

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (id, principal_id, name, token_hash, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateAPITokenParams struct {
	ID          string         `json:"id"`
	PrincipalID string         `json:"principal_id"`
	Name        string         `json:"name"`
	TokenHash   string         `json:"token_hash"`
	ExpiresAt   sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, createAPIToken,
		arg.ID,
		arg.PrincipalID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createAgentConversation = `-- name: CreateAgentConversation :one
INSERT INTO agent_conversations (id, workspace_id, principal_id, title, status, metadata_json, transcript_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type CreateAgentConversationParams struct {
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
	Title          string `json:"title"`
	Status         string `json:"status"`
	MetadataJson   string `json:"metadata_json"`
	TranscriptJson string `json:"transcript_json"`
}

func (q *Queries) CreateAgentConversation(ctx context.Context, arg CreateAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, createAgentConversation,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Title,
		arg.Status,
		arg.MetadataJson,
		arg.TranscriptJson,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (id, conversation_id, status, model, metadata_json)
SELECT
  ?1,
  c.id,
  ?2,
  ?3,
  ?4
FROM agent_conversations c
WHERE c.id = ?5
  AND c.workspace_id = ?6
  AND c.principal_id = ?7
RETURNING id, conversation_id, status, model, stop_reason, input_tokens, output_tokens, total_tokens, error, started_at, finished_at, metadata_json
`

type CreateAgentRunParams struct {
	ID             string `json:"id"`
	Status         string `json:"status"`
	Model          string `json:"model"`
	MetadataJson   string `json:"metadata_json"`
	ConversationID string `json:"conversation_id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, createAgentRun,
		arg.ID,
		arg.Status,
		arg.Model,
		arg.MetadataJson,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.Model,
		&i.StopReason,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MetadataJson,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :exec
INSERT INTO deployments (id, workspace_id, status, created_by)
VALUES (?, ?, ?, ?)
`

type CreateDeploymentParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Status      string `json:"status"`
	CreatedBy   string `json:"created_by"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, createDeployment,
		arg.ID,
		arg.WorkspaceID,
		arg.Status,
		arg.CreatedBy,
	)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, principal_id, token_hash, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
	TokenHash   string `json:"token_hash"`
	ExpiresAt   string `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.PrincipalID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deletePrincipalRoleBindings = `-- name: DeletePrincipalRoleBindings :exec
DELETE FROM role_bindings
WHERE workspace_id = ? AND principal_id = ?
`

type DeletePrincipalRoleBindingsParams struct {
	WorkspaceID string         `json:"workspace_id"`
	PrincipalID sql.NullString `json:"principal_id"`
}

func (q *Queries) DeletePrincipalRoleBindings(ctx context.Context, arg DeletePrincipalRoleBindingsParams) error {
	_, err := q.db.ExecContext(ctx, deletePrincipalRoleBindings, arg.WorkspaceID, arg.PrincipalID)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const finishAgentRun = `-- name: FinishAgentRun :one
UPDATE agent_runs
SET status = ?1,
    stop_reason = ?2,
    input_tokens = ?3,
    output_tokens = ?4,
    total_tokens = ?5,
    error = ?6,
    finished_at = CURRENT_TIMESTAMP,
    metadata_json = ?7
WHERE agent_runs.id = ?8
  AND conversation_id IN (
    SELECT agent_conversations.id
    FROM agent_conversations
    WHERE agent_conversations.id = ?9
      AND workspace_id = ?10
      AND principal_id = ?11
  )
RETURNING id, conversation_id, status, model, stop_reason, input_tokens, output_tokens, total_tokens, error, started_at, finished_at, metadata_json
`

type FinishAgentRunParams struct {
	Status         string `json:"status"`
	StopReason     string `json:"stop_reason"`
	InputTokens    int64  `json:"input_tokens"`
	OutputTokens   int64  `json:"output_tokens"`
	TotalTokens    int64  `json:"total_tokens"`
	Error          string `json:"error"`
	MetadataJson   string `json:"metadata_json"`
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) FinishAgentRun(ctx context.Context, arg FinishAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, finishAgentRun,
		arg.Status,
		arg.StopReason,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.Error,
		arg.MetadataJson,
		arg.ID,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.Model,
		&i.StopReason,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.MetadataJson,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, principal_id, name, token_hash, expires_at, created_at, last_used_at FROM api_tokens
WHERE token_hash = ? AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getActiveDeployment = `-- name: GetActiveDeployment :one
SELECT d.id, d.workspace_id, d.status, d.digest, d.manifest_json, d.created_by, d.created_at, d.activated_at, d.error
FROM deployments d
JOIN workspaces w ON w.active_deployment_id = d.id
WHERE w.id = ?
`

func (q *Queries) GetActiveDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getActiveDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.Digest,
		&i.ManifestJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Error,
	)
	return i, err
}

const getAgentConversation = `-- name: GetAgentConversation :one
SELECT id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at FROM agent_conversations
WHERE id = ?1
  AND workspace_id = ?2
  AND principal_id = ?3
`

type GetAgentConversationParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) GetAgentConversation(ctx context.Context, arg GetAgentConversationParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, getAgentConversation, arg.ID, arg.WorkspaceID, arg.PrincipalID)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getArtifactByDeployment = `-- name: GetArtifactByDeployment :one
SELECT id, deployment_id, workspace_id, digest, format, path, manifest_json, size_bytes, created_at FROM deployment_artifacts WHERE deployment_id = ?
`

func (q *Queries) GetArtifactByDeployment(ctx context.Context, deploymentID string) (DeploymentArtifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactByDeployment, deploymentID)
	var i DeploymentArtifact
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.WorkspaceID,
		&i.Digest,
		&i.Format,
		&i.Path,
		&i.ManifestJson,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, workspace_id, status, digest, manifest_json, created_by, created_at, activated_at, error FROM deployments WHERE id = ?
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Status,
		&i.Digest,
		&i.ManifestJson,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ActivatedAt,
		&i.Error,
	)
	return i, err
}

const getExternalIdentity = `-- name: GetExternalIdentity :one
SELECT id, principal_id, provider, tenant_id, subject, email, created_at, updated_at FROM external_identities
WHERE provider = ? AND tenant_id = ? AND subject = ?
`

type GetExternalIdentityParams struct {
	Provider string `json:"provider"`
	TenantID string `json:"tenant_id"`
	Subject  string `json:"subject"`
}

func (q *Queries) GetExternalIdentity(ctx context.Context, arg GetExternalIdentityParams) (ExternalIdentity, error) {
	row := q.db.QueryRowContext(ctx, getExternalIdentity, arg.Provider, arg.TenantID, arg.Subject)
	var i ExternalIdentity
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Provider,
		&i.TenantID,
		&i.Subject,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, email, display_name, created_at, updated_at FROM principals WHERE id = ?
`

func (q *Queries) GetPrincipal(ctx context.Context, id string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipal, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPrincipalByEmail = `-- name: GetPrincipalByEmail :one
SELECT id, email, display_name, created_at, updated_at FROM principals WHERE lower(email) = lower(?) AND email <> '' LIMIT 1
`

func (q *Queries) GetPrincipalByEmail(ctx context.Context, lower string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByEmail, lower)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, permissions_json FROM roles WHERE name = ?
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.PermissionsJson)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, principal_id, token_hash, expires_at, created_at, last_seen_at FROM sessions WHERE token_hash = ? AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, title, description, active_deployment_id, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :exec
INSERT INTO assets (id, workspace_id, deployment_id, asset_type, asset_key, parent_asset_id, title, description, content_json, content_hash, content_version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAssetParams struct {
	ID             string         `json:"id"`
	WorkspaceID    string         `json:"workspace_id"`
	DeploymentID   string         `json:"deployment_id"`
	AssetType      string         `json:"asset_type"`
	AssetKey       string         `json:"asset_key"`
	ParentAssetID  sql.NullString `json:"parent_asset_id"`
	Title          string         `json:"title"`
	Description    string         `json:"description"`
	ContentJson    string         `json:"content_json"`
	ContentHash    string         `json:"content_hash"`
	ContentVersion int64          `json:"content_version"`
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) error {
	_, err := q.db.ExecContext(ctx, insertAsset,
		arg.ID,
		arg.WorkspaceID,
		arg.DeploymentID,
		arg.AssetType,
		arg.AssetKey,
		arg.ParentAssetID,
		arg.Title,
		arg.Description,
		arg.ContentJson,
		arg.ContentHash,
		arg.ContentVersion,
	)
	return err
}

const insertAssetEdge = `-- name: InsertAssetEdge :exec
INSERT INTO asset_edges (id, workspace_id, deployment_id, from_asset_id, to_asset_id, edge_type)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAssetEdgeParams struct {
	ID           string `json:"id"`
	WorkspaceID  string `json:"workspace_id"`
	DeploymentID string `json:"deployment_id"`
	FromAssetID  string `json:"from_asset_id"`
	ToAssetID    string `json:"to_asset_id"`
	EdgeType     string `json:"edge_type"`
}

func (q *Queries) InsertAssetEdge(ctx context.Context, arg InsertAssetEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetEdge,
		arg.ID,
		arg.WorkspaceID,
		arg.DeploymentID,
		arg.FromAssetID,
		arg.ToAssetID,
		arg.EdgeType,
	)
	return err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (id, workspace_id, principal_id, action, target_type, target_id, metadata_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditEventParams struct {
	ID           string         `json:"id"`
	WorkspaceID  sql.NullString `json:"workspace_id"`
	PrincipalID  sql.NullString `json:"principal_id"`
	Action       string         `json:"action"`
	TargetType   string         `json:"target_type"`
	TargetID     string         `json:"target_id"`
	MetadataJson string         `json:"metadata_json"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.MetadataJson,
	)
	return err
}

const insertDeploymentArtifact = `-- name: InsertDeploymentArtifact :exec
INSERT INTO deployment_artifacts (id, deployment_id, workspace_id, digest, format, path, manifest_json, size_bytes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(deployment_id) DO UPDATE SET
  digest = excluded.digest,
  format = excluded.format,
  path = excluded.path,
  manifest_json = excluded.manifest_json,
  size_bytes = excluded.size_bytes
`

type InsertDeploymentArtifactParams struct {
	ID           string `json:"id"`
	DeploymentID string `json:"deployment_id"`
	WorkspaceID  string `json:"workspace_id"`
	Digest       string `json:"digest"`
	Format       string `json:"format"`
	Path         string `json:"path"`
	ManifestJson string `json:"manifest_json"`
	SizeBytes    int64  `json:"size_bytes"`
}

func (q *Queries) InsertDeploymentArtifact(ctx context.Context, arg InsertDeploymentArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentArtifact,
		arg.ID,
		arg.DeploymentID,
		arg.WorkspaceID,
		arg.Digest,
		arg.Format,
		arg.Path,
		arg.ManifestJson,
		arg.SizeBytes,
	)
	return err
}

const insertRoleBinding = `-- name: InsertRoleBinding :exec
INSERT OR IGNORE INTO role_bindings (id, workspace_id, role_id, principal_id, group_id)
VALUES (?, ?, ?, ?, ?)
`

type InsertRoleBindingParams struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	RoleID      string         `json:"role_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	GroupID     sql.NullString `json:"group_id"`
}

func (q *Queries) InsertRoleBinding(ctx context.Context, arg InsertRoleBindingParams) error {
	_, err := q.db.ExecContext(ctx, insertRoleBinding,
		arg.ID,
		arg.WorkspaceID,
		arg.RoleID,
		arg.PrincipalID,
		arg.GroupID,
	)
	return err
}

const listAgentConversations = `-- name: ListAgentConversations :many
SELECT id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at FROM agent_conversations
WHERE workspace_id = ?1
  AND principal_id = ?2
  AND status = 'active'
ORDER BY updated_at DESC, created_at DESC
`

type ListAgentConversationsParams struct {
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) ListAgentConversations(ctx context.Context, arg ListAgentConversationsParams) ([]AgentConversation, error) {
	rows, err := q.db.QueryContext(ctx, listAgentConversations, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConversation{}
	for rows.Next() {
		var i AgentConversation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Title,
			&i.Status,
			&i.MetadataJson,
			&i.TranscriptJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentEvents = `-- name: ListAgentEvents :many
SELECT e.id, e.run_id, e.seq, e.event_type, e.severity, e.payload_json, e.created_at
FROM agent_events e
JOIN agent_runs r ON r.id = e.run_id
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE r.id = ?1
  AND c.workspace_id = ?2
  AND c.principal_id = ?3
ORDER BY e.seq
`

type ListAgentEventsParams struct {
	RunID       string `json:"run_id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) ListAgentEvents(ctx context.Context, arg ListAgentEventsParams) ([]AgentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentEvents, arg.RunID, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentEvent{}
	for rows.Next() {
		var i AgentEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.EventType,
			&i.Severity,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessages = `-- name: ListAgentMessages :many
SELECT m.id, m.conversation_id, m.run_id, m.seq, m.role, m.content_text, m.content_json, m.tool_call_id, m.tool_name, m.is_error, m.created_at
FROM agent_messages m
JOIN agent_conversations c ON c.id = m.conversation_id
WHERE c.id = ?1
  AND c.workspace_id = ?2
  AND c.principal_id = ?3
ORDER BY m.seq
`

type ListAgentMessagesParams struct {
	ConversationID string `json:"conversation_id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) ListAgentMessages(ctx context.Context, arg ListAgentMessagesParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessages, arg.ConversationID, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Seq,
			&i.Role,
			&i.ContentText,
			&i.ContentJson,
			&i.ToolCallID,
			&i.ToolName,
			&i.IsError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRuns = `-- name: ListAgentRuns :many
SELECT r.id, r.conversation_id, r.status, r.model, r.stop_reason, r.input_tokens, r.output_tokens, r.total_tokens, r.error, r.started_at, r.finished_at, r.metadata_json
FROM agent_runs r
JOIN agent_conversations c ON c.id = r.conversation_id
WHERE c.id = ?1
  AND c.workspace_id = ?2
  AND c.principal_id = ?3
ORDER BY r.started_at DESC
`

type ListAgentRunsParams struct {
	ConversationID string `json:"conversation_id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) ListAgentRuns(ctx context.Context, arg ListAgentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRuns, arg.ConversationID, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentRun{}
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Status,
			&i.Model,
			&i.StopReason,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetEdgesByDeployment = `-- name: ListAssetEdgesByDeployment :many
SELECT id, workspace_id, deployment_id, from_asset_id, to_asset_id, edge_type, created_at FROM asset_edges WHERE deployment_id = ? ORDER BY edge_type, from_asset_id, to_asset_id
`

func (q *Queries) ListAssetEdgesByDeployment(ctx context.Context, deploymentID string) ([]AssetEdge, error) {
	rows, err := q.db.QueryContext(ctx, listAssetEdgesByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetEdge{}
	for rows.Next() {
		var i AssetEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DeploymentID,
			&i.FromAssetID,
			&i.ToAssetID,
			&i.EdgeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByDeployment = `-- name: ListAssetsByDeployment :many
SELECT id, workspace_id, deployment_id, asset_type, asset_key, parent_asset_id, title, description, content_json, content_hash, content_version, created_at FROM assets WHERE deployment_id = ? ORDER BY asset_type, asset_key
`

func (q *Queries) ListAssetsByDeployment(ctx context.Context, deploymentID string) ([]Asset, error) {
	rows, err := q.db.QueryContext(ctx, listAssetsByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DeploymentID,
			&i.AssetType,
			&i.AssetKey,
			&i.ParentAssetID,
			&i.Title,
			&i.Description,
			&i.ContentJson,
			&i.ContentHash,
			&i.ContentVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, workspace_id, status, digest, manifest_json, created_by, created_at, activated_at, error FROM deployments
WHERE workspace_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListDeployments(ctx context.Context, workspaceID string) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Status,
			&i.Digest,
			&i.ManifestJson,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ActivatedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalRolePermissions = `-- name: ListPrincipalRolePermissions :many
SELECT r.permissions_json
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
WHERE rb.workspace_id = ? AND rb.principal_id = ?
`

type ListPrincipalRolePermissionsParams struct {
	WorkspaceID string         `json:"workspace_id"`
	PrincipalID sql.NullString `json:"principal_id"`
}

func (q *Queries) ListPrincipalRolePermissions(ctx context.Context, arg ListPrincipalRolePermissionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipalRolePermissions, arg.WorkspaceID, arg.PrincipalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permissions_json string
		if err := rows.Scan(&permissions_json); err != nil {
			return nil, err
		}
		items = append(items, permissions_json)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleBindingsByWorkspace = `-- name: ListRoleBindingsByWorkspace :many
SELECT
  rb.id,
  rb.workspace_id,
  rb.principal_id,
  p.email,
  p.display_name,
  r.name AS role_name,
  rb.created_at
FROM role_bindings rb
JOIN roles r ON r.id = rb.role_id
LEFT JOIN principals p ON p.id = rb.principal_id
WHERE rb.workspace_id = ? AND rb.principal_id IS NOT NULL
ORDER BY p.email, r.name
`

type ListRoleBindingsByWorkspaceRow struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	PrincipalID sql.NullString `json:"principal_id"`
	Email       sql.NullString `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	RoleName    string         `json:"role_name"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) ListRoleBindingsByWorkspace(ctx context.Context, workspaceID string) ([]ListRoleBindingsByWorkspaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoleBindingsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleBindingsByWorkspaceRow{}
	for rows.Next() {
		var i ListRoleBindingsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PrincipalID,
			&i.Email,
			&i.DisplayName,
			&i.RoleName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, permissions_json FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.PermissionsJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, title, description, active_deployment_id, created_at, updated_at FROM workspaces ORDER BY created_at
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ActiveDeploymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeploymentActive = `-- name: MarkDeploymentActive :exec
UPDATE deployments
SET status = 'active', activated_at = CURRENT_TIMESTAMP, error = ''
WHERE id = ?
`

func (q *Queries) MarkDeploymentActive(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markDeploymentActive, id)
	return err
}

const markOtherDeploymentsInactive = `-- name: MarkOtherDeploymentsInactive :exec
UPDATE deployments
SET status = 'inactive'
WHERE workspace_id = ? AND id <> ? AND status = 'active'
`

type MarkOtherDeploymentsInactiveParams struct {
	WorkspaceID string `json:"workspace_id"`
	ID          string `json:"id"`
}

func (q *Queries) MarkOtherDeploymentsInactive(ctx context.Context, arg MarkOtherDeploymentsInactiveParams) error {
	_, err := q.db.ExecContext(ctx, markOtherDeploymentsInactive, arg.WorkspaceID, arg.ID)
	return err
}

const setWorkspaceActiveDeployment = `-- name: SetWorkspaceActiveDeployment :exec
UPDATE workspaces
SET active_deployment_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetWorkspaceActiveDeploymentParams struct {
	ActiveDeploymentID sql.NullString `json:"active_deployment_id"`
	ID                 string         `json:"id"`
}

func (q *Queries) SetWorkspaceActiveDeployment(ctx context.Context, arg SetWorkspaceActiveDeploymentParams) error {
	_, err := q.db.ExecContext(ctx, setWorkspaceActiveDeployment, arg.ActiveDeploymentID, arg.ID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchAPIToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchSession, id)
	return err
}

const updateAgentConversationTranscript = `-- name: UpdateAgentConversationTranscript :one
UPDATE agent_conversations
SET transcript_json = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND workspace_id = ?3
  AND principal_id = ?4
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type UpdateAgentConversationTranscriptParams struct {
	TranscriptJson string `json:"transcript_json"`
	ID             string `json:"id"`
	WorkspaceID    string `json:"workspace_id"`
	PrincipalID    string `json:"principal_id"`
}

func (q *Queries) UpdateAgentConversationTranscript(ctx context.Context, arg UpdateAgentConversationTranscriptParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, updateAgentConversationTranscript,
		arg.TranscriptJson,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateDefaultAgentConversationTitle = `-- name: UpdateDefaultAgentConversationTitle :one
UPDATE agent_conversations
SET title = ?1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?2
  AND workspace_id = ?3
  AND principal_id = ?4
  AND status = 'active'
  AND title = 'New conversation'
RETURNING id, workspace_id, principal_id, title, status, metadata_json, transcript_json, created_at, updated_at, archived_at
`

type UpdateDefaultAgentConversationTitleParams struct {
	Title       string `json:"title"`
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	PrincipalID string `json:"principal_id"`
}

func (q *Queries) UpdateDefaultAgentConversationTitle(ctx context.Context, arg UpdateDefaultAgentConversationTitleParams) (AgentConversation, error) {
	row := q.db.QueryRowContext(ctx, updateDefaultAgentConversationTitle,
		arg.Title,
		arg.ID,
		arg.WorkspaceID,
		arg.PrincipalID,
	)
	var i AgentConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PrincipalID,
		&i.Title,
		&i.Status,
		&i.MetadataJson,
		&i.TranscriptJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE deployments
SET status = ?, error = ?
WHERE id = ?
`

type UpdateDeploymentStatusParams struct {
	Status string `json:"status"`
	Error  string `json:"error"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentStatus, arg.Status, arg.Error, arg.ID)
	return err
}

const updateDeploymentValidated = `-- name: UpdateDeploymentValidated :exec
UPDATE deployments
SET status = ?, digest = ?, manifest_json = ?, error = ''
WHERE id = ?
`

type UpdateDeploymentValidatedParams struct {
	Status       string `json:"status"`
	Digest       string `json:"digest"`
	ManifestJson string `json:"manifest_json"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateDeploymentValidated(ctx context.Context, arg UpdateDeploymentValidatedParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentValidated,
		arg.Status,
		arg.Digest,
		arg.ManifestJson,
		arg.ID,
	)
	return err
}

const upsertExternalIdentity = `-- name: UpsertExternalIdentity :exec
INSERT INTO external_identities (id, principal_id, provider, tenant_id, subject, email, updated_at)
VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(provider, tenant_id, subject) DO UPDATE SET
  principal_id = excluded.principal_id,
  email = excluded.email,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertExternalIdentityParams struct {
	ID          string `json:"id"`
	PrincipalID string `json:"principal_id"`
	Provider    string `json:"provider"`
	TenantID    string `json:"tenant_id"`
	Subject     string `json:"subject"`
	Email       string `json:"email"`
}

func (q *Queries) UpsertExternalIdentity(ctx context.Context, arg UpsertExternalIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertExternalIdentity,
		arg.ID,
		arg.PrincipalID,
		arg.Provider,
		arg.TenantID,
		arg.Subject,
		arg.Email,
	)
	return err
}

const upsertPrincipal = `-- name: UpsertPrincipal :exec
INSERT INTO principals (id, email, display_name, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  email = excluded.email,
  display_name = excluded.display_name,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertPrincipalParams struct {
	ID          string `json:"id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpsertPrincipal(ctx context.Context, arg UpsertPrincipalParams) error {
	_, err := q.db.ExecContext(ctx, upsertPrincipal, arg.ID, arg.Email, arg.DisplayName)
	return err
}

const upsertRole = `-- name: UpsertRole :exec
INSERT INTO roles (id, name, permissions_json)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET permissions_json = excluded.permissions_json
`

type UpsertRoleParams struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	PermissionsJson string `json:"permissions_json"`
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) error {
	_, err := q.db.ExecContext(ctx, upsertRole, arg.ID, arg.Name, arg.PermissionsJson)
	return err
}

const upsertWorkspace = `-- name: UpsertWorkspace :exec
INSERT INTO workspaces (id, title, description, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  updated_at = CURRENT_TIMESTAMP
`

type UpsertWorkspaceParams struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) UpsertWorkspace(ctx context.Context, arg UpsertWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspace, arg.ID, arg.Title, arg.Description)
	return err
}
