version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      container-images:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: terraform
    directory: /deploy/hetzner
    schedule:
      interval: weekly
    groups:
      terraform-providers:
        patterns:
          - "*"
