// Command openapidocgen turns the generated LibreDash OpenAPI contract into
// the Markdown sources consumed by the public documentation site.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

const generatedMarkdownMarker = "<!-- Code generated by internal/tools/openapidocgen; DO NOT EDIT. -->"

func main() {
	specPath := flag.String("spec", "api/gen/openapi.yaml", "OpenAPI YAML source")
	outDir := flag.String("out", "docs/api", "generated Markdown output directory")
	flag.Parse()
	if err := generate(*specPath, *outDir); err != nil {
		fmt.Fprintf(os.Stderr, "generate OpenAPI documentation: %v\n", err)
		os.Exit(1)
	}
}

type openAPISpec struct {
	Info struct {
		Title       string `yaml:"title"`
		Version     string `yaml:"version"`
		Description string `yaml:"description"`
	} `yaml:"info"`
	Tags  []openAPITag                    `yaml:"tags"`
	Paths map[string]map[string]operation `yaml:"paths"`
}

type openAPITag struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

type operation struct {
	Summary     string              `yaml:"summary"`
	Description string              `yaml:"description"`
	Tags        []string            `yaml:"tags"`
	Parameters  []parameter         `yaml:"parameters"`
	RequestBody requestBody         `yaml:"requestBody"`
	Responses   map[string]response `yaml:"responses"`
}

type parameter struct {
	Name        string         `yaml:"name"`
	In          string         `yaml:"in"`
	Required    bool           `yaml:"required"`
	Description string         `yaml:"description"`
	Schema      map[string]any `yaml:"schema"`
}

type requestBody struct {
	Description string         `yaml:"description"`
	Required    bool           `yaml:"required"`
	Content     map[string]any `yaml:"content"`
}

type response struct {
	Description string `yaml:"description"`
}

type generatedCatalog struct {
	Title       string              `json:"title"`
	Version     string              `json:"version"`
	Description string              `json:"description"`
	Documents   []generatedDocument `json:"documents"`
}

type generatedDocument struct {
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

type taggedOperation struct {
	Path   string
	Method string
	Value  operation
}

func generate(specPath, outDir string) error {
	source, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", specPath, err)
	}
	var spec openAPISpec
	if err := yaml.Unmarshal(source, &spec); err != nil {
		return fmt.Errorf("decode %s: %w", specPath, err)
	}
	if err := cleanGeneratedOutput(outDir); err != nil {
		return fmt.Errorf("clean %s: %w", outDir, err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", outDir, err)
	}

	byTag := operationsByTag(spec)
	documents := make([]generatedDocument, 0, len(spec.Tags))
	for _, tag := range spec.Tags {
		operations := byTag[tag.Name]
		if len(operations) == 0 {
			continue
		}
		document := generatedDocument{
			Slug:    slugify(tag.Name),
			Title:   tag.Name,
			Summary: tag.Description,
		}
		documents = append(documents, document)
		if err := writeFile(filepath.Join(outDir, document.Slug+".md"), renderTagDocument(tag, operations)); err != nil {
			return err
		}
	}
	if len(documents) == 0 {
		return fmt.Errorf("OpenAPI contract does not define tagged operations")
	}

	catalog := generatedCatalog{
		Title:       spec.Info.Title,
		Version:     spec.Info.Version,
		Description: spec.Info.Description,
		Documents:   documents,
	}
	encodedCatalog, err := json.MarshalIndent(catalog, "", "  ")
	if err != nil {
		return fmt.Errorf("encode API documentation catalog: %w", err)
	}
	if err := writeFile(filepath.Join(outDir, "catalog.json"), string(encodedCatalog)+"\n"); err != nil {
		return err
	}
	if err := writeFile(filepath.Join(outDir, "index.md"), renderIndexDocument(catalog)); err != nil {
		return err
	}
	return writeBytes(filepath.Join(outDir, "openapi.yaml"), source)
}

func cleanGeneratedOutput(outDir string) error {
	entries, err := os.ReadDir(outDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		path := filepath.Join(outDir, entry.Name())
		if entry.Name() == "catalog.json" || entry.Name() == "index.md" || entry.Name() == "openapi.yaml" {
			if err := os.Remove(path); err != nil {
				return err
			}
			continue
		}
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.HasPrefix(string(contents), generatedMarkdownMarker) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

func operationsByTag(spec openAPISpec) map[string][]taggedOperation {
	byTag := make(map[string][]taggedOperation, len(spec.Tags))
	for path, pathItem := range spec.Paths {
		for method, value := range pathItem {
			method = strings.ToUpper(method)
			if !isHTTPMethod(method) {
				continue
			}
			for _, tag := range value.Tags {
				byTag[tag] = append(byTag[tag], taggedOperation{Path: path, Method: method, Value: value})
			}
		}
	}
	for tag := range byTag {
		sort.Slice(byTag[tag], func(i, j int) bool {
			if byTag[tag][i].Path == byTag[tag][j].Path {
				return byTag[tag][i].Method < byTag[tag][j].Method
			}
			return byTag[tag][i].Path < byTag[tag][j].Path
		})
	}
	return byTag
}

func renderIndexDocument(catalog generatedCatalog) string {
	var markdown strings.Builder
	markdown.WriteString(generatedMarkdownMarker + "\n\n")
	markdown.WriteString("# API reference\n\n")
	if catalog.Description != "" {
		markdown.WriteString(strings.TrimSpace(catalog.Description) + "\n\n")
	}
	markdown.WriteString("[Download the OpenAPI schema](/docs/openapi.yaml)\n\n")
	markdown.WriteString("## Resources\n\n")
	for _, document := range catalog.Documents {
		markdown.WriteString(fmt.Sprintf("- [%s](/docs/api/%s)", document.Title, document.Slug))
		if document.Summary != "" {
			markdown.WriteString(": " + document.Summary)
		}
		markdown.WriteString("\n")
	}
	return strings.TrimRight(markdown.String(), "\n") + "\n"
}

func renderTagDocument(tag openAPITag, operations []taggedOperation) string {
	var markdown strings.Builder
	markdown.WriteString(generatedMarkdownMarker + "\n\n")
	markdown.WriteString("# " + tag.Name + "\n\n")
	if tag.Description != "" {
		markdown.WriteString(strings.TrimSpace(tag.Description) + "\n\n")
	}
	for _, operation := range operations {
		title := operation.Value.Summary
		if title == "" {
			title = operation.Method + " " + operation.Path
		}
		markdown.WriteString("## " + title + "\n\n")
		markdown.WriteString(fmt.Sprintf("`%s %s`\n\n", operation.Method, operation.Path))
		if operation.Value.Description != "" {
			markdown.WriteString(strings.TrimSpace(operation.Value.Description) + "\n\n")
		}
		writeParameters(&markdown, operation.Value.Parameters)
		writeRequestBody(&markdown, operation.Value.RequestBody)
		writeResponses(&markdown, operation.Value.Responses)
	}
	return strings.TrimRight(markdown.String(), "\n") + "\n"
}

func writeParameters(markdown *strings.Builder, parameters []parameter) {
	if len(parameters) == 0 {
		return
	}
	markdown.WriteString("### Parameters\n\n")
	markdown.WriteString("| Name | In | Required | Type | Description |\n| --- | --- | --- | --- | --- |\n")
	for _, parameter := range parameters {
		required := "No"
		if parameter.Required {
			required = "Yes"
		}
		markdown.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n", parameter.Name, parameter.In, required, schemaType(parameter.Schema), tableText(parameter.Description)))
	}
	markdown.WriteString("\n")
}

func writeRequestBody(markdown *strings.Builder, body requestBody) {
	if len(body.Content) == 0 {
		return
	}
	contentTypes := make([]string, 0, len(body.Content))
	for contentType := range body.Content {
		contentTypes = append(contentTypes, contentType)
	}
	sort.Strings(contentTypes)
	markdown.WriteString("### Request body\n\n")
	if body.Description != "" {
		markdown.WriteString(tableText(body.Description) + "\n\n")
	}
	markdown.WriteString("Content types: `" + strings.Join(contentTypes, "`, `") + "`.\n\n")
}

func writeResponses(markdown *strings.Builder, responses map[string]response) {
	if len(responses) == 0 {
		return
	}
	statuses := make([]string, 0, len(responses))
	for status := range responses {
		statuses = append(statuses, status)
	}
	sort.Strings(statuses)
	markdown.WriteString("### Responses\n\n")
	markdown.WriteString("| Status | Description |\n| --- | --- |\n")
	for _, status := range statuses {
		markdown.WriteString(fmt.Sprintf("| `%s` | %s |\n", status, tableText(responses[status].Description)))
	}
	markdown.WriteString("\n")
}

func schemaType(schema map[string]any) string {
	if reference, ok := schema["$ref"].(string); ok {
		return strings.TrimPrefix(reference, "#/components/schemas/")
	}
	if kind, ok := schema["type"].(string); ok {
		return kind
	}
	return "—"
}

func tableText(value string) string {
	value = strings.ReplaceAll(strings.TrimSpace(value), "|", "\\|")
	return strings.ReplaceAll(value, "\n", " ")
}

func slugify(value string) string {
	var slug strings.Builder
	lastDash := true
	for _, character := range strings.ToLower(value) {
		if unicode.IsLetter(character) || unicode.IsDigit(character) {
			slug.WriteRune(character)
			lastDash = false
			continue
		}
		if !lastDash {
			slug.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(slug.String(), "-")
}

func isHTTPMethod(method string) bool {
	switch method {
	case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "TRACE":
		return true
	default:
		return false
	}
}

func writeFile(path, contents string) error {
	return writeBytes(path, []byte(contents))
}

func writeBytes(path string, contents []byte) error {
	if err := os.WriteFile(path, contents, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
