// Command openapidocgen turns the generated LeapView OpenAPI contract into
// the Markdown sources consumed by the public documentation site.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

const generatedMarkdownMarker = "<!-- Code generated by internal/tools/openapidocgen; DO NOT EDIT. -->"

func main() {
	specPath := flag.String("spec", "api/gen/openapi.yaml", "OpenAPI YAML source")
	outDir := flag.String("out", "docs/api", "generated Markdown output directory")
	flag.Parse()
	if err := generate(*specPath, *outDir); err != nil {
		fmt.Fprintf(os.Stderr, "generate OpenAPI documentation: %v\n", err)
		os.Exit(1)
	}
}

type openAPISpec struct {
	Info struct {
		Title       string `yaml:"title"`
		Version     string `yaml:"version"`
		Description string `yaml:"description"`
	} `yaml:"info"`
	Tags       []openAPITag                    `yaml:"tags"`
	Paths      map[string]map[string]operation `yaml:"paths"`
	Components struct {
		Schemas map[string]any `yaml:"schemas"`
	} `yaml:"components"`
}

type openAPITag struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

type operation struct {
	OperationID   string              `yaml:"operationId"`
	Summary       string              `yaml:"summary"`
	Description   string              `yaml:"description"`
	Tags          []string            `yaml:"tags"`
	Parameters    []parameter         `yaml:"parameters"`
	RequestBody   requestBody         `yaml:"requestBody"`
	Responses     map[string]response `yaml:"responses"`
	Authorization map[string]any      `yaml:"x-authz"`
	Tool          toolMetadata        `yaml:"x-apigen-tool"`
}

type parameter struct {
	Name        string         `yaml:"name"`
	In          string         `yaml:"in"`
	Required    bool           `yaml:"required"`
	Description string         `yaml:"description"`
	Schema      map[string]any `yaml:"schema"`
}

type requestBody struct {
	Description string         `yaml:"description"`
	Required    bool           `yaml:"required"`
	Content     map[string]any `yaml:"content"`
}

type response struct {
	Description string         `yaml:"description"`
	Content     map[string]any `yaml:"content"`
}

type toolMetadata struct {
	Name         string `yaml:"name" json:"name,omitempty"`
	Effect       string `yaml:"effect" json:"effect,omitempty"`
	Confirmation string `yaml:"confirmation" json:"confirmation,omitempty"`
}

type operationManifest struct {
	SchemaVersion int                `json:"schemaVersion"`
	APIVersion    string             `json:"apiVersion"`
	Operations    []machineOperation `json:"operations"`
	Schemas       map[string]any     `json:"schemas"`
}

type machineOperation struct {
	OperationID   string              `json:"operationId"`
	Method        string              `json:"method"`
	Path          string              `json:"path"`
	Summary       string              `json:"summary"`
	Description   string              `json:"description"`
	Tags          []string            `json:"tags"`
	Effect        string              `json:"effect"`
	Confirmation  string              `json:"confirmation"`
	Authorization map[string]any      `json:"authorization,omitempty"`
	Tool          *toolMetadata       `json:"tool,omitempty"`
	Parameters    []machineParameter  `json:"parameters"`
	RequestBody   *machineRequestBody `json:"requestBody,omitempty"`
	Responses     []machineResponse   `json:"responses"`
}

type machineParameter struct {
	Name        string         `json:"name"`
	In          string         `json:"in"`
	Required    bool           `json:"required"`
	Description string         `json:"description"`
	Schema      map[string]any `json:"schema,omitempty"`
}

type machineRequestBody struct {
	Required    bool             `json:"required"`
	Description string           `json:"description"`
	Content     []machineContent `json:"content"`
}

type machineResponse struct {
	Status      string           `json:"status"`
	Description string           `json:"description"`
	Content     []machineContent `json:"content"`
}

type machineContent struct {
	ContentType string         `json:"contentType"`
	Schema      map[string]any `json:"schema,omitempty"`
}

type generatedCatalog struct {
	Title       string              `json:"title"`
	Version     string              `json:"version"`
	Description string              `json:"description"`
	Documents   []generatedDocument `json:"documents"`
}

type generatedDocument struct {
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

type taggedOperation struct {
	Path   string
	Method string
	Value  operation
}

func generate(specPath, outDir string) error {
	source, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", specPath, err)
	}
	var spec openAPISpec
	if err := yaml.Unmarshal(source, &spec); err != nil {
		return fmt.Errorf("decode %s: %w", specPath, err)
	}
	if err := cleanGeneratedOutput(outDir); err != nil {
		return fmt.Errorf("clean %s: %w", outDir, err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", outDir, err)
	}

	byTag := operationsByTag(spec)
	documents := make([]generatedDocument, 0, len(spec.Tags))
	for _, tag := range spec.Tags {
		operations := byTag[tag.Name]
		if len(operations) == 0 {
			continue
		}
		document := generatedDocument{
			Slug:    slugify(tag.Name),
			Title:   tag.Name,
			Summary: tag.Description,
		}
		documents = append(documents, document)
		if err := writeFile(filepath.Join(outDir, document.Slug+".md"), renderTagDocument(tag, operations)); err != nil {
			return err
		}
	}
	if len(documents) == 0 {
		return fmt.Errorf("OpenAPI contract does not define tagged operations")
	}
	operations, err := machineOperations(spec)
	if err != nil {
		return err
	}
	encodedOperations, err := json.MarshalIndent(operationManifest{SchemaVersion: 1, APIVersion: spec.Info.Version, Operations: operations, Schemas: spec.Components.Schemas}, "", "  ")
	if err != nil {
		return fmt.Errorf("encode API operation manifest: %w", err)
	}
	if err := writeBytes(filepath.Join(outDir, "operations.json"), append(encodedOperations, '\n')); err != nil {
		return err
	}

	catalog := generatedCatalog{
		Title:       spec.Info.Title,
		Version:     spec.Info.Version,
		Description: spec.Info.Description,
		Documents:   documents,
	}
	encodedCatalog, err := json.MarshalIndent(catalog, "", "  ")
	if err != nil {
		return fmt.Errorf("encode API documentation catalog: %w", err)
	}
	if err := writeFile(filepath.Join(outDir, "catalog.json"), string(encodedCatalog)+"\n"); err != nil {
		return err
	}
	if err := writeFile(filepath.Join(outDir, "index.md"), renderIndexDocument(catalog)); err != nil {
		return err
	}
	return writeBytes(filepath.Join(outDir, "openapi.yaml"), source)
}

func cleanGeneratedOutput(outDir string) error {
	entries, err := os.ReadDir(outDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		path := filepath.Join(outDir, entry.Name())
		if entry.Name() == "catalog.json" || entry.Name() == "index.md" || entry.Name() == "openapi.yaml" || entry.Name() == "operations.json" {
			if err := os.Remove(path); err != nil {
				return err
			}
			continue
		}
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		contents, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.HasPrefix(string(contents), generatedMarkdownMarker) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

func machineOperations(spec openAPISpec) ([]machineOperation, error) {
	operations := []machineOperation{}
	seen := map[string]struct{}{}
	for path, pathItem := range spec.Paths {
		for method, value := range pathItem {
			method = strings.ToUpper(method)
			if !isHTTPMethod(method) {
				continue
			}
			if value.OperationID == "" {
				return nil, fmt.Errorf("%s %s is missing operationId", method, path)
			}
			if _, exists := seen[value.OperationID]; exists {
				return nil, fmt.Errorf("duplicate operationId %q", value.OperationID)
			}
			seen[value.OperationID] = struct{}{}
			effect := value.Tool.Effect
			if effect == "" {
				effect = defaultOperationEffect(method)
			}
			confirmation := value.Tool.Confirmation
			if confirmation == "" {
				confirmation = defaultOperationConfirmation(effect)
			}
			parameters := make([]machineParameter, 0, len(value.Parameters))
			for _, parameter := range value.Parameters {
				parameters = append(parameters, machineParameter{Name: parameter.Name, In: parameter.In, Required: parameter.Required, Description: parameter.Description, Schema: parameter.Schema})
			}
			var body *machineRequestBody
			if len(value.RequestBody.Content) > 0 {
				body = &machineRequestBody{Required: value.RequestBody.Required, Description: value.RequestBody.Description, Content: machineContents(value.RequestBody.Content)}
			}
			statuses := make([]string, 0, len(value.Responses))
			for status := range value.Responses {
				statuses = append(statuses, status)
			}
			sort.Strings(statuses)
			responses := make([]machineResponse, 0, len(statuses))
			for _, status := range statuses {
				response := value.Responses[status]
				responses = append(responses, machineResponse{Status: status, Description: response.Description, Content: machineContents(response.Content)})
			}
			var tool *toolMetadata
			if value.Tool.Name != "" || value.Tool.Effect != "" || value.Tool.Confirmation != "" {
				copy := value.Tool
				tool = &copy
			}
			operations = append(operations, machineOperation{
				OperationID: value.OperationID, Method: method, Path: path, Summary: value.Summary,
				Description: value.Description, Tags: append([]string(nil), value.Tags...), Effect: effect,
				Confirmation: confirmation, Authorization: value.Authorization, Tool: tool,
				Parameters: parameters, RequestBody: body, Responses: responses,
			})
		}
	}
	sort.Slice(operations, func(i, j int) bool { return operations[i].OperationID < operations[j].OperationID })
	return operations, nil
}

func machineContents(content map[string]any) []machineContent {
	contentTypes := make([]string, 0, len(content))
	for contentType := range content {
		contentTypes = append(contentTypes, contentType)
	}
	sort.Strings(contentTypes)
	contents := make([]machineContent, 0, len(contentTypes))
	for _, contentType := range contentTypes {
		entry, _ := content[contentType].(map[string]any)
		schema, _ := entry["schema"].(map[string]any)
		contents = append(contents, machineContent{ContentType: contentType, Schema: schema})
	}
	return contents
}

func defaultOperationEffect(method string) string {
	switch method {
	case "GET", "HEAD", "OPTIONS":
		return "read"
	case "PUT":
		return "idempotent-write"
	case "DELETE":
		return "destructive"
	default:
		return "write"
	}
}

func defaultOperationConfirmation(effect string) string {
	switch effect {
	case "destructive":
		return "required"
	case "write", "idempotent-write":
		return "conditional"
	default:
		return "never"
	}
}

func operationsByTag(spec openAPISpec) map[string][]taggedOperation {
	byTag := make(map[string][]taggedOperation, len(spec.Tags))
	for path, pathItem := range spec.Paths {
		for method, value := range pathItem {
			method = strings.ToUpper(method)
			if !isHTTPMethod(method) {
				continue
			}
			for _, tag := range value.Tags {
				byTag[tag] = append(byTag[tag], taggedOperation{Path: path, Method: method, Value: value})
			}
		}
	}
	for tag := range byTag {
		sort.Slice(byTag[tag], func(i, j int) bool {
			if byTag[tag][i].Path == byTag[tag][j].Path {
				return byTag[tag][i].Method < byTag[tag][j].Method
			}
			return byTag[tag][i].Path < byTag[tag][j].Path
		})
	}
	return byTag
}

func renderIndexDocument(catalog generatedCatalog) string {
	var markdown strings.Builder
	markdown.WriteString(generatedMarkdownMarker + "\n\n")
	markdown.WriteString("# API reference\n\n")
	if catalog.Description != "" {
		markdown.WriteString(strings.TrimSpace(catalog.Description) + "\n\n")
	}
	markdown.WriteString("[Download the OpenAPI schema](/docs/openapi.yaml)\n\n")
	markdown.WriteString("For agents and tooling, use the [versioned operation manifest](/docs/api/operations.json) or the read-only [documentation MCP](/mcp). Focused operation slices are available at `/docs/api/operations/{operationId}.json` and `.md`.\n\n")
	markdown.WriteString("## Resources\n\n")
	for _, document := range catalog.Documents {
		markdown.WriteString(fmt.Sprintf("- [%s](/docs/api/%s)", document.Title, document.Slug))
		if document.Summary != "" {
			markdown.WriteString(": " + document.Summary)
		}
		markdown.WriteString("\n")
	}
	return strings.TrimRight(markdown.String(), "\n") + "\n"
}

func renderTagDocument(tag openAPITag, operations []taggedOperation) string {
	var markdown strings.Builder
	commonErrors := commonErrorResponses(operations)
	markdown.WriteString(generatedMarkdownMarker + "\n\n")
	markdown.WriteString("# " + tag.Name + "\n\n")
	if tag.Description != "" {
		markdown.WriteString(strings.TrimSpace(tag.Description) + "\n\n")
	}
	markdown.WriteString("## Operations\n\n")
	if len(commonErrors) > 0 {
		markdown.WriteString("Each operation lists its specific responses. See [Common error responses](#common-error-responses) for errors shared by every operation on this page.\n\n")
	}
	for _, operation := range operations {
		title := operation.Value.Summary
		if title == "" {
			title = operation.Method + " " + operation.Path
		}
		markdown.WriteString("### " + title + "\n\n")
		markdown.WriteString(fmt.Sprintf("`%s %s`\n\n", operation.Method, operation.Path))
		if operation.Value.Description != "" {
			markdown.WriteString(strings.TrimSpace(operation.Value.Description) + "\n\n")
		}
		writeOperationMetadata(&markdown, operation)
		writeParameters(&markdown, operation.Value.Parameters)
		writeRequestBody(&markdown, operation.Value.RequestBody)
		writeResponses(&markdown, operation.Value.Responses, commonErrors)
	}
	if len(commonErrors) > 0 {
		markdown.WriteString("## Common error responses\n\n")
		markdown.WriteString("These error responses apply to every operation on this page.\n\n")
		writeResponseTable(&markdown, commonErrors)
	}
	return strings.TrimRight(markdown.String(), "\n") + "\n"
}

func commonErrorResponses(operations []taggedOperation) map[string]response {
	if len(operations) < 2 {
		return nil
	}
	common := make(map[string]response)
	for status, candidate := range operations[0].Value.Responses {
		if !isErrorResponseStatus(status) {
			continue
		}
		shared := true
		for _, operation := range operations[1:] {
			other, exists := operation.Value.Responses[status]
			if !exists || !reflect.DeepEqual(candidate, other) {
				shared = false
				break
			}
		}
		if shared {
			common[status] = candidate
		}
	}
	return common
}

func isErrorResponseStatus(status string) bool {
	return status == "default" || (len(status) == 3 && (status[0] == '4' || status[0] == '5'))
}

func writeOperationMetadata(markdown *strings.Builder, tagged taggedOperation) {
	effect := tagged.Value.Tool.Effect
	if effect == "" {
		effect = defaultOperationEffect(tagged.Method)
	}
	confirmation := tagged.Value.Tool.Confirmation
	if confirmation == "" {
		confirmation = defaultOperationConfirmation(effect)
	}
	markdown.WriteString("Operation ID: `" + tagged.Value.OperationID + "`  \n")
	markdown.WriteString("Effect: `" + effect + "`  \n")
	markdown.WriteString("Confirmation: `" + confirmation + "`  \n")
	if privilege, ok := tagged.Value.Authorization["privilege"]; ok {
		markdown.WriteString("Required privilege: `" + fmt.Sprint(privilege) + "`  \n")
	}
	markdown.WriteString("Focused reference: [JSON](/docs/api/operations/" + tagged.Value.OperationID + ".json) · [Markdown](/docs/api/operations/" + tagged.Value.OperationID + ".md)\n\n")
}

func writeParameters(markdown *strings.Builder, parameters []parameter) {
	if len(parameters) == 0 {
		return
	}
	markdown.WriteString("#### Parameters\n\n")
	markdown.WriteString("| Name | In | Required | Type | Description |\n| --- | --- | --- | --- | --- |\n")
	for _, parameter := range parameters {
		required := "No"
		if parameter.Required {
			required = "Yes"
		}
		markdown.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n", parameter.Name, parameter.In, required, schemaType(parameter.Schema), tableText(parameter.Description)))
	}
	markdown.WriteString("\n")
}

func writeRequestBody(markdown *strings.Builder, body requestBody) {
	if len(body.Content) == 0 {
		return
	}
	contentTypes := make([]string, 0, len(body.Content))
	for contentType := range body.Content {
		contentTypes = append(contentTypes, contentType)
	}
	sort.Strings(contentTypes)
	markdown.WriteString("#### Request body\n\n")
	if body.Description != "" {
		markdown.WriteString(tableText(body.Description) + "\n\n")
	}
	markdown.WriteString("Content types: `" + strings.Join(contentTypes, "`, `") + "`.\n\n")
}

func writeResponses(markdown *strings.Builder, responses, commonErrors map[string]response) {
	if len(responses) == 0 {
		return
	}
	operationResponses := make(map[string]response, len(responses))
	for status, value := range responses {
		if _, common := commonErrors[status]; !common {
			operationResponses[status] = value
		}
	}
	markdown.WriteString("#### Responses\n\n")
	if len(operationResponses) > 0 {
		writeResponseTable(markdown, operationResponses)
	}
}

func writeResponseTable(markdown *strings.Builder, responses map[string]response) {
	statuses := make([]string, 0, len(responses))
	for status := range responses {
		statuses = append(statuses, status)
	}
	sort.Strings(statuses)
	markdown.WriteString("| Status | Description |\n| --- | --- |\n")
	for _, status := range statuses {
		markdown.WriteString(fmt.Sprintf("| `%s` | %s |\n", status, tableText(responses[status].Description)))
	}
	markdown.WriteString("\n")
}

func schemaType(schema map[string]any) string {
	if reference, ok := schema["$ref"].(string); ok {
		return strings.TrimPrefix(reference, "#/components/schemas/")
	}
	if kind, ok := schema["type"].(string); ok {
		return kind
	}
	return "—"
}

func tableText(value string) string {
	value = strings.ReplaceAll(strings.TrimSpace(value), "|", "\\|")
	return strings.ReplaceAll(value, "\n", " ")
}

func slugify(value string) string {
	var slug strings.Builder
	lastDash := true
	for _, character := range strings.ToLower(value) {
		if unicode.IsLetter(character) || unicode.IsDigit(character) {
			slug.WriteRune(character)
			lastDash = false
			continue
		}
		if !lastDash {
			slug.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(slug.String(), "-")
}

func isHTTPMethod(method string) bool {
	switch method {
	case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "TRACE":
		return true
	default:
		return false
	}
}

func writeFile(path, contents string) error {
	return writeBytes(path, []byte(contents))
}

func writeBytes(path string, contents []byte) error {
	if err := os.WriteFile(path, contents, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
