// Package siteassets owns the browser assets for the public LibreDash site.
package siteassets

import (
	"embed"
	"io/fs"
)

// files includes authored CSS and the production JavaScript generated by
// scripts/build_site.ts before the site binary is compiled.
//
//go:embed static
var files embed.FS

// Static returns the embedded contents of site/static.
func Static() fs.FS {
	return sub("static")
}

// Shared returns the embedded design-system assets copied into the site build.
func Shared() fs.FS {
	return sub("static/shared")
}

func sub(path string) fs.FS {
	static, err := fs.Sub(files, path)
	if err != nil {
		panic(err)
	}
	return static
}
