// Package siteassets owns the browser assets for the public LibreDash site.
package siteassets

import (
	"embed"
	"fmt"
	"io/fs"
	"path"
)

// files includes authored CSS and the production JavaScript generated by
// scripts/build_site.ts before the site binary is compiled.
//
//go:embed static
var files embed.FS

// Static returns the embedded contents of site/static.
func Static() fs.FS {
	return sub("static")
}

// Shared returns the embedded design-system assets copied into the site build.
func Shared() fs.FS {
	return sub("static/shared")
}

// IntegrationLogo returns a trusted vendored SVG for inline rendering. Inline
// SVGs inherit the site's Primer-backed color variables, unlike SVGs loaded
// through an img element.
func IntegrationLogo(name string) (string, error) {
	if name == "" || path.Base(name) != name {
		return "", fmt.Errorf("invalid integration logo name %q", name)
	}
	contents, err := files.ReadFile("static/vendor/integrations/" + name + ".svg")
	if err != nil {
		return "", fmt.Errorf("read integration logo %q: %w", name, err)
	}
	return string(contents), nil
}

// MCPMark returns the official, trusted Model Context Protocol mark for inline
// rendering. The mark uses currentColor so the containing interface tile can
// source its foreground from the site's Primer-backed tokens.
func MCPMark() (string, error) {
	contents, err := files.ReadFile("static/vendor/mcp-mark.svg")
	if err != nil {
		return "", fmt.Errorf("read MCP mark: %w", err)
	}
	return string(contents), nil
}

func sub(path string) fs.FS {
	static, err := fs.Sub(files, path)
	if err != nil {
		panic(err)
	}
	return static
}
