package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	uisignals "github.com/Yacobolo/libredash/internal/ui/signals"
)

const (
	schemaOut = "schemas/signals/ui-signals.schema.json"
	tsOut     = "web/generated/signals/index.ts"
)

type generator struct {
	definitions map[string]reflect.Type
	seen        map[reflect.Type]struct{}
}

type genField struct {
	Name     string
	Type     reflect.Type
	Required bool
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	g := &generator{definitions: map[string]reflect.Type{}, seen: map[reflect.Type]struct{}{}}
	names := sortedContractNames()
	for _, name := range names {
		g.collect(reflect.TypeOf(uisignals.ContractTypes()[name]))
	}
	if err := writeJSONSchema(g, names); err != nil {
		return err
	}
	if err := writeTypeScript(g, names); err != nil {
		return err
	}
	return nil
}

func sortedContractNames() []string {
	contracts := uisignals.ContractTypes()
	names := make([]string, 0, len(contracts))
	for name := range contracts {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func (g *generator) collect(t reflect.Type) {
	t = deref(t)
	if t.Kind() == reflect.Slice || t.Kind() == reflect.Array {
		g.collect(t.Elem())
		return
	}
	if t.Kind() == reflect.Map {
		g.collect(t.Elem())
		return
	}
	if t.Kind() != reflect.Struct || !isSupportedStruct(t) {
		return
	}
	if _, ok := g.seen[t]; ok {
		return
	}
	g.seen[t] = struct{}{}
	g.definitions[typeName(t)] = t
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() || jsonFieldName(field) == "-" {
			continue
		}
		g.collect(field.Type)
	}
}

func writeJSONSchema(g *generator, roots []string) error {
	defs := map[string]any{}
	names := sortedDefinitionNames(g.definitions)
	for _, name := range names {
		defs[name] = g.schemaForStruct(g.definitions[name])
	}
	rootAnyOf := make([]any, 0, len(roots))
	for _, root := range roots {
		rootAnyOf = append(rootAnyOf, map[string]any{"$ref": "#/$defs/" + root})
	}
	doc := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$id":     "https://libredash.local/schemas/ui-signals.schema.json",
		"title":   "LibreDash UI Signals",
		"anyOf":   rootAnyOf,
		"$defs":   defs,
	}
	return writeJSONFile(schemaOut, doc)
}

func writeTypeScript(g *generator, roots []string) error {
	var out bytes.Buffer
	out.WriteString("// Code generated by go run ./internal/tools/uisignalsgen; DO NOT EDIT.\n\n")
	out.WriteString("export type JsonObject = Record<string, unknown>\n\n")
	names := sortedDefinitionNames(g.definitions)
	for _, name := range names {
		t := g.definitions[name]
		out.WriteString("export interface " + name + " {\n")
		for _, field := range generatedFields(t) {
			optional := ""
			if !field.Required {
				optional = "?"
			}
			out.WriteString("  " + field.Name + optional + ": " + g.tsType(field.Type) + "\n")
		}
		out.WriteString("}\n\n")
	}
	out.WriteString("export type UISignalEnvelope = " + strings.Join(roots, " | ") + "\n")
	return writeFile(tsOut, out.Bytes())
}

func (g *generator) schemaForStruct(t reflect.Type) map[string]any {
	properties := map[string]any{}
	required := []string{}
	for _, field := range generatedFields(t) {
		properties[field.Name] = g.schemaForType(field.Type)
		if field.Required {
			required = append(required, field.Name)
		}
	}
	sort.Strings(required)
	out := map[string]any{
		"type":                 "object",
		"additionalProperties": false,
		"properties":           properties,
	}
	if len(required) > 0 {
		out["required"] = required
	}
	return out
}

func (g *generator) schemaForType(t reflect.Type) any {
	t = deref(t)
	switch t.Kind() {
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Slice, reflect.Array:
		return map[string]any{"type": "array", "items": g.schemaForType(t.Elem())}
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return map[string]any{}
		}
		return map[string]any{"type": "object", "additionalProperties": g.schemaForType(t.Elem())}
	case reflect.Interface:
		return map[string]any{}
	case reflect.Struct:
		if !isSupportedStruct(t) {
			return map[string]any{}
		}
		return map[string]any{"$ref": "#/$defs/" + typeName(t)}
	default:
		return map[string]any{}
	}
}

func (g *generator) tsType(t reflect.Type) string {
	t = deref(t)
	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Slice, reflect.Array:
		return g.tsType(t.Elem()) + "[]"
	case reflect.Map:
		if t.Key().Kind() != reflect.String {
			return "JsonObject"
		}
		return "Record<string, " + g.tsType(t.Elem()) + ">"
	case reflect.Interface:
		return "unknown"
	case reflect.Struct:
		if !isSupportedStruct(t) {
			return "unknown"
		}
		return typeName(t)
	default:
		return "unknown"
	}
}

func sortedDefinitionNames(definitions map[string]reflect.Type) []string {
	names := make([]string, 0, len(definitions))
	for name := range definitions {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func deref(t reflect.Type) reflect.Type {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	return t
}

func isSupportedStruct(t reflect.Type) bool {
	pkg := t.PkgPath()
	return pkg == "github.com/Yacobolo/libredash/internal/ui/signals" ||
		pkg == "github.com/Yacobolo/libredash/internal/dashboard" ||
		pkg == "github.com/Yacobolo/libredash/internal/dashboard/report"
}

func typeName(t reflect.Type) string {
	if t.PkgPath() == "github.com/Yacobolo/libredash/internal/ui/signals" {
		return t.Name()
	}
	return exportName(path.Base(t.PkgPath())) + t.Name()
}

func exportName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return r == '-' || r == '_' || r == '.'
	})
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func jsonFieldName(field reflect.StructField) string {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "-"
	}
	if tag == "" {
		if field.Anonymous {
			return ""
		}
		return strings.ToLower(field.Name[:1]) + field.Name[1:]
	}
	name := strings.Split(tag, ",")[0]
	if name == "" {
		return strings.ToLower(field.Name[:1]) + field.Name[1:]
	}
	return name
}

func jsonOmitEmpty(field reflect.StructField) bool {
	tag := field.Tag.Get("json")
	for _, part := range strings.Split(tag, ",")[1:] {
		if part == "omitempty" {
			return true
		}
	}
	return false
}

func generatedFields(t reflect.Type) []genField {
	t = deref(t)
	fields := []genField{}
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() || jsonFieldName(field) == "-" {
			continue
		}
		if field.Anonymous && field.Tag.Get("json") == "" {
			fields = append(fields, generatedFields(field.Type)...)
			continue
		}
		fields = append(fields, genField{
			Name:     jsonFieldName(field),
			Type:     field.Type,
			Required: !jsonOmitEmpty(field),
		})
	}
	return fields
}

func writeJSONFile(name string, value any) error {
	var out bytes.Buffer
	encoder := json.NewEncoder(&out)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(value); err != nil {
		return err
	}
	return writeFile(name, out.Bytes())
}

func writeFile(name string, content []byte) error {
	if filepath.Ext(name) == ".go" {
		formatted, err := format.Source(content)
		if err != nil {
			return err
		}
		content = formatted
	}
	if err := os.MkdirAll(filepath.Dir(name), 0o755); err != nil {
		return err
	}
	if len(content) == 0 || content[len(content)-1] != '\n' {
		content = append(content, '\n')
	}
	return os.WriteFile(name, content, 0o644)
}
