// Command clidocgen renders the Cobra command tree into public Markdown docs.
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Yacobolo/libredash/internal/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

type catalog struct {
	Title     string     `json:"title"`
	Documents []document `json:"documents"`
}
type document struct {
	Slug    string `json:"slug"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

func main() {
	out := flag.String("out", "docs/reference/cli", "generated Markdown output directory")
	flag.Parse()
	if err := generate(cli.NewCommand(context.Background()), *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(root *cobra.Command, out string) error {
	if err := os.RemoveAll(out); err != nil {
		return err
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	items := []document{}
	var visit func(*cobra.Command, []string) error
	visit = func(command *cobra.Command, path []string) error {
		if command.Hidden {
			return nil
		}
		if command != root {
			slug := strings.Join(path, "-")
			item := document{Slug: slug, Title: "libredash " + strings.Join(path, " "), Summary: command.Short}
			items = append(items, item)
			if err := os.WriteFile(filepath.Join(out, slug+".md"), []byte(render(command, item)), 0o644); err != nil {
				return err
			}
		}
		children := command.Commands()
		sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
		for _, child := range children {
			if err := visit(child, append(path, child.Name())); err != nil {
				return err
			}
		}
		return nil
	}
	if err := visit(root, nil); err != nil {
		return err
	}
	sort.Slice(items, func(i, j int) bool { return items[i].Title < items[j].Title })
	encoded, err := json.MarshalIndent(catalog{Title: "CLI reference", Documents: items}, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(out, "catalog.json"), append(encoded, '\n'), 0o644); err != nil {
		return err
	}
	var index strings.Builder
	index.WriteString("<!-- Code generated by internal/tools/clidocgen; DO NOT EDIT. -->\n\n# CLI reference\n\n")
	index.WriteString("The complete reference for the `libredash` command-line interface.\n\n## Commands\n\n")
	for _, item := range items {
		index.WriteString(fmt.Sprintf("- [%s](/docs/cli/%s): %s\n", item.Title, item.Slug, item.Summary))
	}
	return os.WriteFile(filepath.Join(out, "index.md"), []byte(index.String()), 0o644)
}

func render(command *cobra.Command, item document) string {
	var out strings.Builder
	out.WriteString("<!-- Code generated by internal/tools/clidocgen; DO NOT EDIT. -->\n\n# " + item.Title + "\n\n")
	if command.Long != "" {
		out.WriteString(strings.TrimSpace(command.Long))
	} else {
		out.WriteString(command.Short)
	}
	out.WriteString("\n\n## Usage\n\n```sh\n" + command.UseLine() + "\n```\n")
	writeFlags(&out, "Options", command.LocalFlags())
	if inherited := command.InheritedFlags(); inherited.HasFlags() {
		writeFlags(&out, "Inherited options", inherited)
	}
	if len(command.Example) > 0 {
		out.WriteString("\n## Examples\n\n```sh\n" + strings.TrimSpace(command.Example) + "\n```\n")
	}
	children := visibleChildren(command)
	if len(children) > 0 {
		out.WriteString("\n## Subcommands\n\n")
		for _, child := range children {
			out.WriteString(fmt.Sprintf("- `libredash %s`: %s\n", child.Name(), child.Short))
		}
	}
	return out.String()
}

func writeFlags(out *strings.Builder, heading string, flags *pflag.FlagSet) {
	if !flags.HasFlags() {
		return
	}
	out.WriteString("\n## " + heading + "\n\n| Flag | Type | Default | Description |\n| --- | --- | --- | --- |\n")
	flags.VisitAll(func(value *pflag.Flag) {
		name := "`--" + value.Name + "`"
		if value.Shorthand != "" {
			name = "`-" + value.Shorthand + "`, " + name
		}
		out.WriteString(fmt.Sprintf("| %s | %s | `%s` | %s |\n", name, value.Value.Type(), value.DefValue, value.Usage))
	})
}

func visibleChildren(command *cobra.Command) []*cobra.Command {
	children := []*cobra.Command{}
	for _, child := range command.Commands() {
		if !child.Hidden {
			children = append(children, child)
		}
	}
	return children
}
