// Code generated by internal/tools/configgen; DO NOT EDIT.

package config

import (
	"time"

	"github.com/Yacobolo/libredash/internal/configspec"
)

type Config struct {
	// AddrFallback Compatibility listen-address alias used after LIBREDASH_ADDR.
	AddrFallback string `env:"ADDR"`
	// Addr HTTP listen address.
	Addr string `env:"LIBREDASH_ADDR"`
	// AgentAPIKey API key for the configured agent model provider.
	AgentAPIKey string `env:"LIBREDASH_AGENT_API_KEY"`
	// AgentBaseURL OpenAI-compatible agent API base URL.
	AgentBaseURL string `env:"LIBREDASH_AGENT_BASE_URL" envDefault:"https://api.openai.com/v1"`
	// AgentModel Agent model identifier.
	AgentModel string `env:"LIBREDASH_AGENT_MODEL"`
	// AllowedHosts Comma- or whitespace-separated exact hosts and wildcard suffixes accepted in production.
	AllowedHosts string `env:"LIBREDASH_ALLOWED_HOSTS"`
	// APIToken API token used by non-interactive CLI commands.
	APIToken string `env:"LIBREDASH_API_TOKEN"`
	// APITokenOnlyAuth Disable browser authentication and accept API tokens only.
	APITokenOnlyAuth bool `env:"LIBREDASH_API_TOKEN_ONLY_AUTH"`
	// AssetVersion Optional browser asset cache-busting version override.
	AssetVersion string `env:"LIBREDASH_ASSET_VERSION"`
	// AzureCallbackURL HTTPS callback URL registered with Azure AD or Entra ID.
	AzureCallbackURL string `env:"LIBREDASH_AZURE_CALLBACK_URL"`
	// AzureClientID Azure AD or Entra ID OAuth client identifier.
	AzureClientID string `env:"LIBREDASH_AZURE_CLIENT_ID"`
	// AzureSecret Azure AD or Entra ID OAuth client secret.
	AzureSecret string `env:"LIBREDASH_AZURE_CLIENT_SECRET"`
	// AzureTenant Optional Azure AD or Entra ID tenant identifier.
	AzureTenant string `env:"LIBREDASH_AZURE_TENANT"`
	// BootstrapEmail Email assigned to the production bootstrap administrator.
	BootstrapEmail string `env:"LIBREDASH_BOOTSTRAP_ADMIN_EMAIL"`
	// CatalogPath Legacy dashboard catalog path override.
	CatalogPath string `env:"LIBREDASH_CATALOG_PATH"`
	// CLIConfig Path to the local CLI target and token configuration file.
	CLIConfig string `env:"LIBREDASH_CLI_CONFIG"`
	// CookieSecureRaw Secure-cookie override; defaults to true for production browser authentication.
	CookieSecureRaw string `env:"LIBREDASH_COOKIE_SECURE"`
	// CSRFKey Key used for CSRF protection and OAuth state cookies; production requires at least 32 characters.
	CSRFKey string `env:"LIBREDASH_CSRF_KEY"`
	// DataDir Directory containing source data files.
	DataDir string `env:"LIBREDASH_DATA_DIR" envDefault:".data/olist"`
	// DevAuthBypass Bypass authentication in development; forbidden in production.
	DevAuthBypass bool `env:"LIBREDASH_DEV_AUTH_BYPASS" envDefault:"false"`
	// DuckDBDir Directory containing workspace DuckDB runtime files.
	DuckDBDir string `env:"LIBREDASH_DUCKDB_DIR"`
	// DuckDBPath Explicit legacy DuckDB database path override.
	DuckDBPath string `env:"LIBREDASH_DUCKDB_PATH"`
	// DuckLakeCatalog Path to the single global DuckLake catalog.
	DuckLakeCatalog string `env:"LIBREDASH_DUCKLAKE_CATALOG_PATH"`
	// ExecJobLeaseTimeout Lease duration before an abandoned refresh job may be reclaimed.
	ExecJobLeaseTimeout time.Duration `env:"LIBREDASH_EXEC_JOB_LEASE_TIMEOUT" envDefault:"2m"`
	// ExecMaxQueuedReads Maximum queued interactive read queries; negative disables queuing.
	ExecMaxQueuedReads int `env:"LIBREDASH_EXEC_MAX_QUEUED_READS" envDefault:"64"`
	// ExecMaxQueuedWrites Maximum queued refresh jobs; negative disables queuing.
	ExecMaxQueuedWrites int `env:"LIBREDASH_EXEC_MAX_QUEUED_WRITES" envDefault:"64"`
	// ExecMaxRunningReads Maximum concurrently running interactive read queries.
	ExecMaxRunningReads int `env:"LIBREDASH_EXEC_MAX_RUNNING_READS" envDefault:"4"`
	// ExecMaxRunningWrites Maximum concurrently running refresh jobs.
	ExecMaxRunningWrites int `env:"LIBREDASH_EXEC_MAX_RUNNING_WRITES" envDefault:"1"`
	// ExecReadQueueTimeout Maximum time an interactive read may wait in the queue.
	ExecReadQueueTimeout time.Duration `env:"LIBREDASH_EXEC_READ_QUEUE_TIMEOUT" envDefault:"30s"`
	// ExecReadTimeout Maximum execution time for an interactive read query.
	ExecReadTimeout time.Duration `env:"LIBREDASH_EXEC_READ_TIMEOUT" envDefault:"2m"`
	// HealthcheckURL Explicit readiness URL used by the healthcheck command.
	HealthcheckURL string `env:"LIBREDASH_HEALTHCHECK_URL"`
	// HomeDir Instance state directory containing databases, artifacts, and runtime files.
	HomeDir string `env:"LIBREDASH_HOME" envDefault:".libredash"`
	// LocalAuth Enable administrator-managed local browser authentication.
	LocalAuth bool `env:"LIBREDASH_LOCAL_AUTH"`
	// MetricsBearerToken Bearer token protecting the Prometheus metrics endpoint; production requires at least 32 characters.
	MetricsBearerToken string `env:"LIBREDASH_METRICS_BEARER_TOKEN"`
	// OIDCCallbackURL HTTPS callback URL registered with the generic OIDC provider.
	OIDCCallbackURL string `env:"LIBREDASH_OIDC_CALLBACK_URL"`
	// OIDCClientID Generic OIDC client identifier.
	OIDCClientID string `env:"LIBREDASH_OIDC_CLIENT_ID"`
	// OIDCSecret Generic OIDC client secret.
	OIDCSecret string `env:"LIBREDASH_OIDC_CLIENT_SECRET"`
	// OIDCIssuerURL HTTPS issuer URL for the generic OIDC provider.
	OIDCIssuerURL string `env:"LIBREDASH_OIDC_ISSUER_URL"`
	// OIDCProviderID Route-safe identifier for the generic OIDC provider.
	OIDCProviderID string `env:"LIBREDASH_OIDC_PROVIDER_ID" envDefault:"oidc"`
	// OIDCScopes Comma- or whitespace-separated additional OIDC scopes.
	OIDCScopes string `env:"LIBREDASH_OIDC_SCOPES"`
	// Production Enable production serving and validation behavior.
	Production bool `env:"LIBREDASH_PRODUCTION" envDefault:"false"`
	// SCIMBearerToken Bearer token enabling SCIM provisioning; production requires at least 32 characters when set.
	SCIMBearerToken string `env:"LIBREDASH_SCIM_BEARER_TOKEN"`
	// Target Default LibreDash API target URL.
	Target string `env:"LIBREDASH_TARGET"`
	// TokenHashKey Optional dedicated key for deterministic API-token fingerprints; falls back to the CSRF key.
	TokenHashKey string `env:"LIBREDASH_TOKEN_HASH_KEY"`
	// TrustProxyHeaders Trust client-address headers only when a trusted proxy overwrites them.
	TrustProxyHeaders bool `env:"LIBREDASH_TRUST_PROXY_HEADERS" envDefault:"false"`
	// Port Compatibility port alias used after LIBREDASH_ADDR and ADDR.
	Port string `env:"PORT"`
}

func (c Config) catalogValues() map[string]any {
	return map[string]any{
		configspec.EnvADDR:                              c.AddrFallback,
		configspec.EnvLIBREDASH_ADDR:                    c.Addr,
		configspec.EnvLIBREDASH_AGENT_API_KEY:           c.AgentAPIKey,
		configspec.EnvLIBREDASH_AGENT_BASE_URL:          c.AgentBaseURL,
		configspec.EnvLIBREDASH_AGENT_MODEL:             c.AgentModel,
		configspec.EnvLIBREDASH_ALLOWED_HOSTS:           c.AllowedHosts,
		configspec.EnvLIBREDASH_API_TOKEN:               c.APIToken,
		configspec.EnvLIBREDASH_API_TOKEN_ONLY_AUTH:     c.APITokenOnlyAuth,
		configspec.EnvLIBREDASH_ASSET_VERSION:           c.AssetVersion,
		configspec.EnvLIBREDASH_AZURE_CALLBACK_URL:      c.AzureCallbackURL,
		configspec.EnvLIBREDASH_AZURE_CLIENT_ID:         c.AzureClientID,
		configspec.EnvLIBREDASH_AZURE_CLIENT_SECRET:     c.AzureSecret,
		configspec.EnvLIBREDASH_AZURE_TENANT:            c.AzureTenant,
		configspec.EnvLIBREDASH_BOOTSTRAP_ADMIN_EMAIL:   c.BootstrapEmail,
		configspec.EnvLIBREDASH_CATALOG_PATH:            c.CatalogPath,
		configspec.EnvLIBREDASH_CLI_CONFIG:              c.CLIConfig,
		configspec.EnvLIBREDASH_COOKIE_SECURE:           c.CookieSecureRaw,
		configspec.EnvLIBREDASH_CSRF_KEY:                c.CSRFKey,
		configspec.EnvLIBREDASH_DATA_DIR:                c.DataDir,
		configspec.EnvLIBREDASH_DEV_AUTH_BYPASS:         c.DevAuthBypass,
		configspec.EnvLIBREDASH_DUCKDB_DIR:              c.DuckDBDir,
		configspec.EnvLIBREDASH_DUCKDB_PATH:             c.DuckDBPath,
		configspec.EnvLIBREDASH_DUCKLAKE_CATALOG_PATH:   c.DuckLakeCatalog,
		configspec.EnvLIBREDASH_EXEC_JOB_LEASE_TIMEOUT:  c.ExecJobLeaseTimeout,
		configspec.EnvLIBREDASH_EXEC_MAX_QUEUED_READS:   c.ExecMaxQueuedReads,
		configspec.EnvLIBREDASH_EXEC_MAX_QUEUED_WRITES:  c.ExecMaxQueuedWrites,
		configspec.EnvLIBREDASH_EXEC_MAX_RUNNING_READS:  c.ExecMaxRunningReads,
		configspec.EnvLIBREDASH_EXEC_MAX_RUNNING_WRITES: c.ExecMaxRunningWrites,
		configspec.EnvLIBREDASH_EXEC_READ_QUEUE_TIMEOUT: c.ExecReadQueueTimeout,
		configspec.EnvLIBREDASH_EXEC_READ_TIMEOUT:       c.ExecReadTimeout,
		configspec.EnvLIBREDASH_HEALTHCHECK_URL:         c.HealthcheckURL,
		configspec.EnvLIBREDASH_HOME:                    c.HomeDir,
		configspec.EnvLIBREDASH_LOCAL_AUTH:              c.LocalAuth,
		configspec.EnvLIBREDASH_METRICS_BEARER_TOKEN:    c.MetricsBearerToken,
		configspec.EnvLIBREDASH_OIDC_CALLBACK_URL:       c.OIDCCallbackURL,
		configspec.EnvLIBREDASH_OIDC_CLIENT_ID:          c.OIDCClientID,
		configspec.EnvLIBREDASH_OIDC_CLIENT_SECRET:      c.OIDCSecret,
		configspec.EnvLIBREDASH_OIDC_ISSUER_URL:         c.OIDCIssuerURL,
		configspec.EnvLIBREDASH_OIDC_PROVIDER_ID:        c.OIDCProviderID,
		configspec.EnvLIBREDASH_OIDC_SCOPES:             c.OIDCScopes,
		configspec.EnvLIBREDASH_PRODUCTION:              c.Production,
		configspec.EnvLIBREDASH_SCIM_BEARER_TOKEN:       c.SCIMBearerToken,
		configspec.EnvLIBREDASH_TARGET:                  c.Target,
		configspec.EnvLIBREDASH_TOKEN_HASH_KEY:          c.TokenHashKey,
		configspec.EnvLIBREDASH_TRUST_PROXY_HEADERS:     c.TrustProxyHeaders,
		configspec.EnvPORT:                              c.Port,
	}
}
