// Code generated by internal/tools/configgen; DO NOT EDIT.

package config

import (
	"time"

	"github.com/Yacobolo/libredash/internal/configspec"
)

type Config struct {
	// Addr HTTP listen address.
	Addr string `env:"LIBREDASH_ADDR"`
	// AgentAPIKey API key for the configured agent model provider.
	AgentAPIKey string `env:"LIBREDASH_AGENT_API_KEY"`
	// AgentBaseURL OpenAI-compatible agent API base URL.
	AgentBaseURL string `env:"LIBREDASH_AGENT_BASE_URL" envDefault:"https://api.openai.com/v1"`
	// AgentModel Agent model identifier.
	AgentModel string `env:"LIBREDASH_AGENT_MODEL"`
	// AllowedHosts Comma- or whitespace-separated exact hosts and wildcard suffixes accepted in production.
	AllowedHosts string `env:"LIBREDASH_ALLOWED_HOSTS"`
	// APIToken API token used by non-interactive CLI commands.
	APIToken string `env:"LIBREDASH_API_TOKEN"`
	// APITokenOnlyAuth Disable browser authentication and accept API tokens only.
	APITokenOnlyAuth bool `env:"LIBREDASH_API_TOKEN_ONLY_AUTH"`
	// AssetVersion Optional browser asset cache-busting version override.
	AssetVersion string `env:"LIBREDASH_ASSET_VERSION"`
	// AzureCallbackURL HTTPS callback URL registered with Azure AD or Entra ID.
	AzureCallbackURL string `env:"LIBREDASH_AZURE_CALLBACK_URL"`
	// AzureClientID Azure AD or Entra ID OAuth client identifier.
	AzureClientID string `env:"LIBREDASH_AZURE_CLIENT_ID"`
	// AzureSecret Azure AD or Entra ID OAuth client secret.
	AzureSecret string `env:"LIBREDASH_AZURE_CLIENT_SECRET"`
	// AzureTenant Optional Azure AD or Entra ID tenant identifier.
	AzureTenant string `env:"LIBREDASH_AZURE_TENANT"`
	// BootstrapEmail Email assigned to the production bootstrap administrator.
	BootstrapEmail string `env:"LIBREDASH_BOOTSTRAP_ADMIN_EMAIL"`
	// CLIConfig Path to the local CLI target and token configuration file.
	CLIConfig string `env:"LIBREDASH_CLI_CONFIG"`
	// CookieSecureRaw Secure-cookie override; defaults to true for production browser authentication.
	CookieSecureRaw string `env:"LIBREDASH_COOKIE_SECURE"`
	// CSRFKey Key used for CSRF protection and OAuth state cookies; production requires at least 32 characters.
	CSRFKey string `env:"LIBREDASH_CSRF_KEY"`
	// DevAPIToken Static bearer credential accepted by the public API in development; replace the development default on shared machines.
	DevAPIToken string `env:"LIBREDASH_DEV_API_TOKEN" envDefault:"dev"`
	// DevAuthBypass Bypass authentication in development; forbidden in production.
	DevAuthBypass bool `env:"LIBREDASH_DEV_AUTH_BYPASS" envDefault:"false"`
	// DuckDBDir Directory containing workspace DuckDB runtime files.
	DuckDBDir string `env:"LIBREDASH_DUCKDB_DIR"`
	// DuckLakeCatalog Path to the single global DuckLake catalog.
	DuckLakeCatalog string `env:"LIBREDASH_DUCKLAKE_CATALOG_PATH"`
	// ExecJobLeaseTimeout Lease duration before an abandoned refresh job may be reclaimed.
	ExecJobLeaseTimeout time.Duration `env:"LIBREDASH_EXEC_JOB_LEASE_TIMEOUT" envDefault:"2m"`
	// ExecMaxQueuedReads Maximum queued interactive read queries; negative disables queuing.
	ExecMaxQueuedReads int `env:"LIBREDASH_EXEC_MAX_QUEUED_READS" envDefault:"64"`
	// ExecMaxQueuedWrites Maximum queued refresh jobs; negative disables queuing.
	ExecMaxQueuedWrites int `env:"LIBREDASH_EXEC_MAX_QUEUED_WRITES" envDefault:"64"`
	// ExecMaxRunningReads Maximum concurrently running interactive read queries.
	ExecMaxRunningReads int `env:"LIBREDASH_EXEC_MAX_RUNNING_READS" envDefault:"4"`
	// ExecMaxRunningWrites Maximum concurrently running refresh jobs.
	ExecMaxRunningWrites int `env:"LIBREDASH_EXEC_MAX_RUNNING_WRITES" envDefault:"1"`
	// ExecReadQueueTimeout Maximum time an interactive read may wait in the queue.
	ExecReadQueueTimeout time.Duration `env:"LIBREDASH_EXEC_READ_QUEUE_TIMEOUT" envDefault:"30s"`
	// ExecReadTimeout Maximum execution time for an interactive read query.
	ExecReadTimeout time.Duration `env:"LIBREDASH_EXEC_READ_TIMEOUT" envDefault:"2m"`
	// HealthcheckURL Explicit readiness URL used by the healthcheck command.
	HealthcheckURL string `env:"LIBREDASH_HEALTHCHECK_URL"`
	// HomeDir Instance state directory containing databases, artifacts, and runtime files.
	HomeDir string `env:"LIBREDASH_HOME" envDefault:".libredash"`
	// LocalAuth Enable administrator-managed local browser authentication.
	LocalAuth bool `env:"LIBREDASH_LOCAL_AUTH"`
	// ManagedDataBackend Storage backend for project-global managed data; supported values are local and s3.
	ManagedDataBackend string `env:"LIBREDASH_MANAGED_DATA_BACKEND" envDefault:"local"`
	// ManagedDataDir Private local root for managed-data objects, upload staging, and verified runtime views; S3 deployments use it as the runtime cache.
	ManagedDataDir string `env:"LIBREDASH_MANAGED_DATA_DIR" envDefault:".libredash/managed-data"`
	// ManagedDataGCGracePeriod Minimum age of unreferenced managed-data objects before garbage collection.
	ManagedDataGCGracePeriod time.Duration `env:"LIBREDASH_MANAGED_DATA_GC_GRACE_PERIOD" envDefault:"24h"`
	// ManagedDataGCInterval Interval between managed-data garbage-collection passes.
	ManagedDataGCInterval time.Duration `env:"LIBREDASH_MANAGED_DATA_GC_INTERVAL" envDefault:"1h"`
	// ManagedDataMaxFiles Maximum number of files in one managed-data revision.
	ManagedDataMaxFiles int `env:"LIBREDASH_MANAGED_DATA_MAX_FILES" envDefault:"10000"`
	// ManagedDataMaxFileBytes Maximum size in bytes of one managed-data file.
	ManagedDataMaxFileBytes int64 `env:"LIBREDASH_MANAGED_DATA_MAX_FILE_BYTES" envDefault:"1073741824"`
	// ManagedDataMaxRevisionBytes Maximum total size in bytes of one managed-data revision.
	ManagedDataMaxRevisionBytes int64 `env:"LIBREDASH_MANAGED_DATA_MAX_REVISION_BYTES" envDefault:"10737418240"`
	// ManagedDataMinFreeBytes Minimum free bytes required before accepting local managed-data uploads.
	ManagedDataMinFreeBytes int64 `env:"LIBREDASH_MANAGED_DATA_MIN_FREE_BYTES" envDefault:"5368709120"`
	// ManagedDataS3AccessKeyID Optional S3 access-key identifier for managed-data storage.
	ManagedDataS3AccessKeyID string `env:"LIBREDASH_MANAGED_DATA_S3_ACCESS_KEY_ID"`
	// ManagedDataS3Bucket S3 bucket used for managed-data objects and staging.
	ManagedDataS3Bucket string `env:"LIBREDASH_MANAGED_DATA_S3_BUCKET"`
	// ManagedDataS3Endpoint Optional S3-compatible endpoint URL.
	ManagedDataS3Endpoint string `env:"LIBREDASH_MANAGED_DATA_S3_ENDPOINT"`
	// ManagedDataS3PathStyle Use path-style addressing for S3-compatible managed-data storage.
	ManagedDataS3PathStyle bool `env:"LIBREDASH_MANAGED_DATA_S3_PATH_STYLE" envDefault:"false"`
	// ManagedDataS3Prefix Object-key prefix for managed data in the configured S3 bucket.
	ManagedDataS3Prefix string `env:"LIBREDASH_MANAGED_DATA_S3_PREFIX" envDefault:"managed-data"`
	// ManagedDataS3Region S3 region used for managed-data requests.
	ManagedDataS3Region string `env:"LIBREDASH_MANAGED_DATA_S3_REGION"`
	// ManagedDataS3SecretAccessKey Optional S3 secret access key for managed-data storage.
	ManagedDataS3SecretAccessKey string `env:"LIBREDASH_MANAGED_DATA_S3_SECRET_ACCESS_KEY"`
	// ManagedDataS3SessionToken Optional temporary S3 session token for managed-data storage.
	ManagedDataS3SessionToken string `env:"LIBREDASH_MANAGED_DATA_S3_SESSION_TOKEN"`
	// ManagedDataUploadSessionTTL Lifetime of an incomplete managed-data upload session.
	ManagedDataUploadSessionTTL time.Duration `env:"LIBREDASH_MANAGED_DATA_UPLOAD_SESSION_TTL" envDefault:"24h"`
	// MetricsBearerToken Bearer token protecting the Prometheus metrics endpoint; production requires at least 32 characters.
	MetricsBearerToken string `env:"LIBREDASH_METRICS_BEARER_TOKEN"`
	// OIDCCallbackURL HTTPS callback URL registered with the generic OIDC provider.
	OIDCCallbackURL string `env:"LIBREDASH_OIDC_CALLBACK_URL"`
	// OIDCClientID Generic OIDC client identifier.
	OIDCClientID string `env:"LIBREDASH_OIDC_CLIENT_ID"`
	// OIDCSecret Generic OIDC client secret.
	OIDCSecret string `env:"LIBREDASH_OIDC_CLIENT_SECRET"`
	// OIDCIssuerURL HTTPS issuer URL for the generic OIDC provider.
	OIDCIssuerURL string `env:"LIBREDASH_OIDC_ISSUER_URL"`
	// OIDCProviderID Route-safe identifier for the generic OIDC provider.
	OIDCProviderID string `env:"LIBREDASH_OIDC_PROVIDER_ID" envDefault:"oidc"`
	// OIDCScopes Comma- or whitespace-separated additional OIDC scopes.
	OIDCScopes string `env:"LIBREDASH_OIDC_SCOPES"`
	// Production Enable production serving and validation behavior.
	Production bool `env:"LIBREDASH_PRODUCTION" envDefault:"false"`
	// QueryCacheMaxBytes Maximum retained bytes for governed interactive query results per semantic model runtime.
	QueryCacheMaxBytes int `env:"LIBREDASH_QUERY_CACHE_MAX_BYTES" envDefault:"67108864"`
	// QueryCacheMaxEntries Maximum governed interactive query result entries retained per semantic model runtime.
	QueryCacheMaxEntries int `env:"LIBREDASH_QUERY_CACHE_MAX_ENTRIES" envDefault:"256"`
	// SCIMBearerToken Bearer token enabling SCIM provisioning; production requires at least 32 characters when set.
	SCIMBearerToken string `env:"LIBREDASH_SCIM_BEARER_TOKEN"`
	// Target Default LibreDash API target URL.
	Target string `env:"LIBREDASH_TARGET"`
	// TokenHashKey Optional dedicated key for deterministic API-token fingerprints; falls back to the CSRF key.
	TokenHashKey string `env:"LIBREDASH_TOKEN_HASH_KEY"`
	// TrustProxyHeaders Trust client-address headers only when a trusted proxy overwrites them.
	TrustProxyHeaders bool `env:"LIBREDASH_TRUST_PROXY_HEADERS" envDefault:"false"`
}

func (c Config) catalogValues() map[string]any {
	return map[string]any{
		configspec.EnvLIBREDASH_ADDR:                              c.Addr,
		configspec.EnvLIBREDASH_AGENT_API_KEY:                     c.AgentAPIKey,
		configspec.EnvLIBREDASH_AGENT_BASE_URL:                    c.AgentBaseURL,
		configspec.EnvLIBREDASH_AGENT_MODEL:                       c.AgentModel,
		configspec.EnvLIBREDASH_ALLOWED_HOSTS:                     c.AllowedHosts,
		configspec.EnvLIBREDASH_API_TOKEN:                         c.APIToken,
		configspec.EnvLIBREDASH_API_TOKEN_ONLY_AUTH:               c.APITokenOnlyAuth,
		configspec.EnvLIBREDASH_ASSET_VERSION:                     c.AssetVersion,
		configspec.EnvLIBREDASH_AZURE_CALLBACK_URL:                c.AzureCallbackURL,
		configspec.EnvLIBREDASH_AZURE_CLIENT_ID:                   c.AzureClientID,
		configspec.EnvLIBREDASH_AZURE_CLIENT_SECRET:               c.AzureSecret,
		configspec.EnvLIBREDASH_AZURE_TENANT:                      c.AzureTenant,
		configspec.EnvLIBREDASH_BOOTSTRAP_ADMIN_EMAIL:             c.BootstrapEmail,
		configspec.EnvLIBREDASH_CLI_CONFIG:                        c.CLIConfig,
		configspec.EnvLIBREDASH_COOKIE_SECURE:                     c.CookieSecureRaw,
		configspec.EnvLIBREDASH_CSRF_KEY:                          c.CSRFKey,
		configspec.EnvLIBREDASH_DEV_API_TOKEN:                     c.DevAPIToken,
		configspec.EnvLIBREDASH_DEV_AUTH_BYPASS:                   c.DevAuthBypass,
		configspec.EnvLIBREDASH_DUCKDB_DIR:                        c.DuckDBDir,
		configspec.EnvLIBREDASH_DUCKLAKE_CATALOG_PATH:             c.DuckLakeCatalog,
		configspec.EnvLIBREDASH_EXEC_JOB_LEASE_TIMEOUT:            c.ExecJobLeaseTimeout,
		configspec.EnvLIBREDASH_EXEC_MAX_QUEUED_READS:             c.ExecMaxQueuedReads,
		configspec.EnvLIBREDASH_EXEC_MAX_QUEUED_WRITES:            c.ExecMaxQueuedWrites,
		configspec.EnvLIBREDASH_EXEC_MAX_RUNNING_READS:            c.ExecMaxRunningReads,
		configspec.EnvLIBREDASH_EXEC_MAX_RUNNING_WRITES:           c.ExecMaxRunningWrites,
		configspec.EnvLIBREDASH_EXEC_READ_QUEUE_TIMEOUT:           c.ExecReadQueueTimeout,
		configspec.EnvLIBREDASH_EXEC_READ_TIMEOUT:                 c.ExecReadTimeout,
		configspec.EnvLIBREDASH_HEALTHCHECK_URL:                   c.HealthcheckURL,
		configspec.EnvLIBREDASH_HOME:                              c.HomeDir,
		configspec.EnvLIBREDASH_LOCAL_AUTH:                        c.LocalAuth,
		configspec.EnvLIBREDASH_MANAGED_DATA_BACKEND:              c.ManagedDataBackend,
		configspec.EnvLIBREDASH_MANAGED_DATA_DIR:                  c.ManagedDataDir,
		configspec.EnvLIBREDASH_MANAGED_DATA_GC_GRACE_PERIOD:      c.ManagedDataGCGracePeriod,
		configspec.EnvLIBREDASH_MANAGED_DATA_GC_INTERVAL:          c.ManagedDataGCInterval,
		configspec.EnvLIBREDASH_MANAGED_DATA_MAX_FILES:            c.ManagedDataMaxFiles,
		configspec.EnvLIBREDASH_MANAGED_DATA_MAX_FILE_BYTES:       c.ManagedDataMaxFileBytes,
		configspec.EnvLIBREDASH_MANAGED_DATA_MAX_REVISION_BYTES:   c.ManagedDataMaxRevisionBytes,
		configspec.EnvLIBREDASH_MANAGED_DATA_MIN_FREE_BYTES:       c.ManagedDataMinFreeBytes,
		configspec.EnvLIBREDASH_MANAGED_DATA_S3_ACCESS_KEY_ID:     c.ManagedDataS3AccessKeyID,
		configspec.EnvLIBREDASH_MANAGED_DATA_S3_BUCKET:            c.ManagedDataS3Bucket,
		configspec.EnvLIBREDASH_MANAGED_DATA_S3_ENDPOINT:          c.ManagedDataS3Endpoint,
		configspec.EnvLIBREDASH_MANAGED_DATA_S3_PATH_STYLE:        c.ManagedDataS3PathStyle,
		configspec.EnvLIBREDASH_MANAGED_DATA_S3_PREFIX:            c.ManagedDataS3Prefix,
		configspec.EnvLIBREDASH_MANAGED_DATA_S3_REGION:            c.ManagedDataS3Region,
		configspec.EnvLIBREDASH_MANAGED_DATA_S3_SECRET_ACCESS_KEY: c.ManagedDataS3SecretAccessKey,
		configspec.EnvLIBREDASH_MANAGED_DATA_S3_SESSION_TOKEN:     c.ManagedDataS3SessionToken,
		configspec.EnvLIBREDASH_MANAGED_DATA_UPLOAD_SESSION_TTL:   c.ManagedDataUploadSessionTTL,
		configspec.EnvLIBREDASH_METRICS_BEARER_TOKEN:              c.MetricsBearerToken,
		configspec.EnvLIBREDASH_OIDC_CALLBACK_URL:                 c.OIDCCallbackURL,
		configspec.EnvLIBREDASH_OIDC_CLIENT_ID:                    c.OIDCClientID,
		configspec.EnvLIBREDASH_OIDC_CLIENT_SECRET:                c.OIDCSecret,
		configspec.EnvLIBREDASH_OIDC_ISSUER_URL:                   c.OIDCIssuerURL,
		configspec.EnvLIBREDASH_OIDC_PROVIDER_ID:                  c.OIDCProviderID,
		configspec.EnvLIBREDASH_OIDC_SCOPES:                       c.OIDCScopes,
		configspec.EnvLIBREDASH_PRODUCTION:                        c.Production,
		configspec.EnvLIBREDASH_QUERY_CACHE_MAX_BYTES:             c.QueryCacheMaxBytes,
		configspec.EnvLIBREDASH_QUERY_CACHE_MAX_ENTRIES:           c.QueryCacheMaxEntries,
		configspec.EnvLIBREDASH_SCIM_BEARER_TOKEN:                 c.SCIMBearerToken,
		configspec.EnvLIBREDASH_TARGET:                            c.Target,
		configspec.EnvLIBREDASH_TOKEN_HASH_KEY:                    c.TokenHashKey,
		configspec.EnvLIBREDASH_TRUST_PROXY_HEADERS:               c.TrustProxyHeaders,
	}
}
